using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;

[assembly: AssemblyTrademark("")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyProduct("")]
[assembly: ComVisible(false)]
[assembly: SuppressIldasm]
[assembly: AssemblyFileVersion("1.27.2835.6155")]
[assembly: Guid("50513de4-eaab-4069-9d2a-129ec1790810")]
[assembly: AssemblyTitle("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyVersion("1.27.2835.6155")]
