namespace ManualMapInjection.Injection.Win32;

public enum DllCharacteristicsType : ushort
{
	RES_0 = 1,
	RES_1 = 2,
	RES_2 = 4,
	RES_3 = 8,
	IMAGE_DLL_CHARACTERISTICS_DYNAMIC_BASE = 0x40,
	IMAGE_DLL_CHARACTERISTICS_FORCE_INTEGRITY = 0x80,
	IMAGE_DLL_CHARACTERISTICS_NX_COMPAT = 0x100,
	IMAGE_DLLCHARACTERISTICS_NO_ISOLATION = 0x200,
	IMAGE_DLLCHARACTERISTICS_NO_SEH = 0x400,
	IMAGE_DLLCHARACTERISTICS_NO_BIND = 0x800,
	RES_4 = 0x1000,
	IMAGE_DLLCHARACTERISTICS_WDM_DRIVER = 0x2000,
	IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x8000
}
