using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace _0xHR3d3mand;

[CompilerGenerated]
[TypeIdentifier("728ab348-217d-11da-b2a4-000e7bbb2b09", "CERTENROLLLib.EncodingType")]
public enum EncodingType
{
	XCN_CRYPT_STRING_BASE64HEADER = 0,
	XCN_CRYPT_STRING_BASE64 = 1,
	XCN_CRYPT_STRING_BINARY = 2,
	XCN_CRYPT_STRING_BASE64REQUESTHEADER = 3,
	XCN_CRYPT_STRING_HEX = 4,
	XCN_CRYPT_STRING_HEXASCII = 5,
	XCN_CRYPT_STRING_BASE64_ANY = 6,
	XCN_CRYPT_STRING_ANY = 7,
	XCN_CRYPT_STRING_HEX_ANY = 8,
	XCN_CRYPT_STRING_BASE64X509CRLHEADER = 9,
	XCN_CRYPT_STRING_HEXADDR = 10,
	XCN_CRYPT_STRING_HEXASCIIADDR = 11,
	XCN_CRYPT_STRING_HEXRAW = 12,
	XCN_CRYPT_STRING_NOCRLF = 1073741824,
	XCN_CRYPT_STRING_NOCR = int.MinValue
}
