namespace wcBHUEjJsvNmvYsNjyUWlFukWdNNZNUnRnWPjWPJRyJOHcOhMLh2;

public class ficken
{
	public static string fakeString = "oSHfArhcIgEbXBNthXVwXPdEIlwENQikRcDatnwsUIQZaahvgXGYZpxzPcwoVDoRXtkVYNZUACCpYdEIebxQkjkBEdlrQhxqtYbGPmwsXLxwMhALyOkTfxHOiJqVCHdtflVabXTSEfSyLOOwDzScXDlWrnxgVBPpIerAlzJAUsoaEicuUTsdPbvCaZJOzNWdpCQHwnkdPrhFolrikdlbjMAGIPAmQVbhvlKcrvXGIonxTQnPIADwBUUCcjYHNYmUqZjdAoROfFtUzcNRBLDpsEGBqhZhxpSJbthUHkotJOqVBadZwgfcvXCLtIMspJrPMJSgVTkrwjFDoKZqeaKqkQoeRvAZxVeaxAjRhXeDWOFlsYxIIvooYaFVvOozskUAeEgNBijhWguwlcLSYRrcHQcwVnvtIElLTehNSKhzmgsRGjKtcwBATSToCJRnMQzrVJCgVYZnKRPAykQLDcqldLRblSkjSTMvHaWXHDydwnQccsQrSgKKznokRAVcNQvQetTxoTeZDmPQUOZScSqMjcWuMLfhIwqGRZYIzsdZbLhmyypcAcaUAJHcxyLCNXrhWjYVQqtJPqKyVJWnwcGFvvfisWlaHAleuZqpztmjJrejZigNCxgLqLLAdQCUfsbpfFdVtGOcQwWerWijPxxjtANInQlJRreqpPdteluVJeUUPHjgHtfIVSVFRvIDvelysFOBSPeDdCApFTTFGfcxlvvxUyCJDRAESvBjTHnSoBEtrFZYBcWpcNmWkrGtmuambVwjrJMYRjiKQcfozDhAUkBfjFZBaUFTBsrwiQGRpXySECfilsUInzrQtraMKkYWEpjxKJgJXplXMJAGzRqIZWGbbBcQPUheZBoptHxBllLXoteKRumTUpXIIhwjHpTcigYkukmStOxOkJMHxrZvInjKEGHlloUVrJOhvTqGhuAgRixYuOLpqxuVXnGODaGeTBwBVFmEbsooNdSwiIRwCEFUoTkhnBdgNvmqLVdP";
}
