namespace eRgfvqXMjSCmTgpcZnDeiuIsvZuQjEYRTGnJMDeZHHBuxkNVkRsvlQm;

public interface srscGcecOFMNuDGqJYHtMMqFvdhaBoxonCUuNKUGIWCifaPa
{
	void yppVyNnOtDRBQLhubGpBSIIbIgNeWcegJvXbOnyqricNlEsHw(byte[] IAdftNvvPlU, byte[] NMPhHQnYQswvzqgLdexjnLHNsbdAEmLfMAINYqNRNjDHmeEPmb);
}
