using System.ComponentModel;

namespace Gecko.WebIDL;

public enum TelephonyCallDisconnectedReason
{
	[Description("BadNumber")]
	BadNumber,
	[Description("NoRouteToDestination")]
	NoRouteToDestination,
	[Description("ChannelUnacceptable")]
	ChannelUnacceptable,
	[Description("OperatorDeterminedBarring")]
	OperatorDeterminedBarring,
	[Description("NormalCallClearing")]
	NormalCallClearing,
	[Description("Busy")]
	Busy,
	[Description("NoUserResponding")]
	NoUserResponding,
	[Description("UserAlertingNoAnswer")]
	UserAlertingNoAnswer,
	[Description("CallRejected")]
	CallRejected,
	[Description("NumberChanged")]
	NumberChanged,
	[Description("CallRejectedDestinationFeature")]
	CallRejectedDestinationFeature,
	[Description("PreEmption")]
	PreEmption,
	[Description("DestinationOutOfOrder")]
	DestinationOutOfOrder,
	[Description("InvalidNumberFormat")]
	InvalidNumberFormat,
	[Description("FacilityRejected")]
	FacilityRejected,
	[Description("ResponseToStatusEnquiry")]
	ResponseToStatusEnquiry,
	[Description("Congestion")]
	Congestion,
	[Description("NetworkOutOfOrder")]
	NetworkOutOfOrder,
	[Description("NetworkTempFailure")]
	NetworkTempFailure,
	[Description("SwitchingEquipCongestion")]
	SwitchingEquipCongestion,
	[Description("AccessInfoDiscarded")]
	AccessInfoDiscarded,
	[Description("RequestedChannelNotAvailable")]
	RequestedChannelNotAvailable,
	[Description("ResourceUnavailable")]
	ResourceUnavailable,
	[Description("QosUnavailable")]
	QosUnavailable,
	[Description("RequestedFacilityNotSubscribed")]
	RequestedFacilityNotSubscribed,
	[Description("IncomingCallsBarredWithinCug")]
	IncomingCallsBarredWithinCug,
	[Description("BearerCapabilityNotAuthorized")]
	BearerCapabilityNotAuthorized,
	[Description("BearerCapabilityNotAvailable")]
	BearerCapabilityNotAvailable,
	[Description("BearerNotImplemented")]
	BearerNotImplemented,
	[Description("ServiceNotAvailable")]
	ServiceNotAvailable,
	[Description("IncomingCallExceeded")]
	IncomingCallExceeded,
	[Description("RequestedFacilityNotImplemented")]
	RequestedFacilityNotImplemented,
	[Description("UnrestrictedBearerNotAvailable")]
	UnrestrictedBearerNotAvailable,
	[Description("ServiceNotImplemented")]
	ServiceNotImplemented,
	[Description("InvalidTransactionId")]
	InvalidTransactionId,
	[Description("NotCugMember")]
	NotCugMember,
	[Description("IncompatibleDestination")]
	IncompatibleDestination,
	[Description("InvalidTransitNetworkSelection")]
	InvalidTransitNetworkSelection,
	[Description("SemanticallyIncorrectMessage")]
	SemanticallyIncorrectMessage,
	[Description("InvalidMandatoryInfo")]
	InvalidMandatoryInfo,
	[Description("MessageTypeNotImplemented")]
	MessageTypeNotImplemented,
	[Description("MessageTypeIncompatibleProtocolState")]
	MessageTypeIncompatibleProtocolState,
	[Description("InfoElementNotImplemented")]
	InfoElementNotImplemented,
	[Description("ConditionalIe")]
	ConditionalIe,
	[Description("MessageIncompatibleProtocolState")]
	MessageIncompatibleProtocolState,
	[Description("RecoveryOnTimerExpiry")]
	RecoveryOnTimerExpiry,
	[Description("Protocol")]
	Protocol,
	[Description("Interworking")]
	Interworking,
	[Description("Barred")]
	Barred,
	[Description("FDNBlocked")]
	FDNBlocked,
	[Description("SubscriberUnknown")]
	SubscriberUnknown,
	[Description("DeviceNotAccepted")]
	DeviceNotAccepted,
	[Description("ModifiedDial")]
	ModifiedDial,
	[Description("CdmaLockedUntilPowerCycle")]
	CdmaLockedUntilPowerCycle,
	[Description("CdmaDrop")]
	CdmaDrop,
	[Description("CdmaIntercept")]
	CdmaIntercept,
	[Description("CdmaReorder")]
	CdmaReorder,
	[Description("CdmaSoReject")]
	CdmaSoReject,
	[Description("CdmaRetryOrder")]
	CdmaRetryOrder,
	[Description("CdmaAcess")]
	CdmaAcess,
	[Description("CdmaPreempted")]
	CdmaPreempted,
	[Description("CdmaNotEmergency")]
	CdmaNotEmergency,
	[Description("CdmaAccessBlocked")]
	CdmaAccessBlocked,
	[Description("Unspecified")]
	Unspecified
}
