using System;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;

internal delegate int _0001(object);
internal delegate int _0002(object, int);
internal delegate char _0003(object, int);
internal delegate string _0004(string, string);
internal delegate string _0005(Environment.SpecialFolder);
internal delegate string _0006(string);
internal delegate string _0007(object);
internal delegate bool _0008(string, string);
internal delegate void _000E(string, string);
internal delegate void _000F(object);
internal delegate string _0010(byte[]);
internal delegate void _0011(object, string);
internal delegate string _0012(object, string, string);
internal delegate Encoding _0013();
internal delegate void _0014(string, string, Encoding);
internal delegate bool _0015(string);
internal delegate void _0016(string, byte[]);
internal delegate Process _0017(string);
internal delegate SettingsBase _0018(SettingsBase);
internal delegate string _0019(string, string, string);
internal delegate string _001A(string, object[]);
internal delegate bool _001B(Version, Version);
internal delegate string _001C(object, int, int);
internal delegate bool _001D(string, ref int);
internal delegate bool _001E(char);
internal delegate Type _001F(RuntimeTypeHandle);
internal delegate int _007F(Type);
internal delegate bool _0080(IntPtr, IntPtr);
internal delegate long _0081(byte[], int);
internal delegate int _0082(byte[], int);
internal delegate string _0083(object, byte[]);
internal delegate string _0084(object, char[]);
internal delegate string _0086(object, byte[], int, int);
internal delegate int _0087(string);
internal delegate Assembly _0088();
internal delegate Stream _0089(object, string);
internal delegate long _008A(object);
internal delegate int _008B(long);
internal delegate int _008C(object, byte[], int, int);
internal delegate bool _008D(object);
internal delegate void _008E(object, string, string);
internal delegate Type _008F(object);
internal delegate StringBuilder _0090(object, char);
internal delegate StringBuilder _0091(object, string);
internal delegate Module _0092(object);
internal delegate Assembly _0093(object);
internal delegate Type _0094(object, string);
internal delegate Guid _0095(object);
internal delegate AssemblyName _0096(object);
internal delegate int _0097(object, string);
internal delegate DateTime _0098();
internal delegate bool _0099(Guid, Guid);
internal delegate Guid _009A();
internal delegate Version _009B();
internal delegate OperatingSystem _009C();
internal delegate Version _009D(object);
internal delegate PlatformID _009E(object);
internal delegate Exception _009F(object);
