using System;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Text;
using System.Windows.Forms;

internal delegate void _0001(object, bool);
internal delegate void _0002(object, FormBorderStyle);
internal delegate void _0003(int);
internal delegate void _0004(object);
internal delegate Assembly _0005();
internal delegate string _0006(object);
internal delegate string _0007(object, string, string);
internal delegate bool _0008(object, string);
internal delegate string[] _000E(object, char[]);
internal delegate string _000F(string, string);
internal delegate DateTime _0010(object);
internal delegate string _0011(string, string, string);
internal delegate long _0012(object);
internal delegate long _0013(long);
internal delegate double _0014(double, double);
internal delegate double _0015(double);
internal delegate int _0016(double);
internal delegate double _0017(double, int);
internal delegate int _0018(long);
internal delegate Process[] _0019();
internal delegate int _001A(object);
internal delegate bool _001B(object);
internal delegate bool _001C(string);
internal delegate DirectoryInfo _001D(string);
internal delegate string _001E(string);
internal delegate void _001F(object, FileAttributes);
internal delegate char _007F(string);
internal delegate string _0080(object, int, char);
internal delegate string _0081(string[]);
internal delegate int _0082(object, byte[], int, int);
internal delegate void _0083(object, byte[], int, int);
internal delegate string _0084(string, string, string, string);
internal delegate ImageFormat _0086();
internal delegate void _0087(object, Stream, ImageFormat);
internal delegate byte[] _0088(object);
internal delegate object _0089(object, Delegate, object[]);
internal delegate void _008A();
internal delegate void _008B(bool);
internal delegate void _008C(Form);
internal delegate OperatingSystem _008D();
internal delegate Version _008E(object);
internal delegate string _008F();
internal delegate void _0090(Array, RuntimeFieldHandle);
internal delegate Type _0091(RuntimeTypeHandle);
internal delegate Assembly _0092(object);
internal delegate object _0093(object, string, CultureInfo);
internal delegate SettingsBase _0094(SettingsBase);
internal delegate string[] _0095(string);
internal delegate int _0096(byte[], int);
internal delegate Encoding _0097();
internal delegate string _0098(object, byte[], int, int);
internal delegate bool _0099(string, string);
internal delegate DateTime _009A();
internal delegate byte[] _009B(int);
internal delegate void _009C(object, Array, int);
internal delegate Screen _009D();
internal delegate Rectangle _009E(object);
internal delegate Graphics _009F(Image);
