using System;

namespace NAudio.MediaFoundation;

[Flags]
public enum _MFT_OUTPUT_DATA_BUFFER_FLAGS
{
	None = 0,
	MFT_OUTPUT_DATA_BUFFER_INCOMPLETE = 0x1000000,
	MFT_OUTPUT_DATA_BUFFER_FORMAT_CHANGE = 0x100,
	MFT_OUTPUT_DATA_BUFFER_STREAM_END = 0x200,
	MFT_OUTPUT_DATA_BUFFER_NO_SAMPLE = 0x300
}
