using System;

namespace NAudio.MediaFoundation;

[Flags]
public enum MF_SOURCE_READER_FLAG
{
	None = 0,
	MF_SOURCE_READERF_ERROR = 1,
	MF_SOURCE_READERF_ENDOFSTREAM = 2,
	MF_SOURCE_READERF_NEWSTREAM = 4,
	MF_SOURCE_READERF_NATIVEMEDIATYPECHANGED = 0x10,
	MF_SOURCE_READERF_CURRENTMEDIATYPECHANGED = 0x20,
	MF_SOURCE_READERF_STREAMTICK = 0x100,
	MF_SOURCE_READERF_ALLEFFECTSREMOVED = 0x200
}
