using System.Collections.ObjectModel;

namespace QQCaptor.Tools;

internal class CityType
{
	public Collection<ShengTypeInfo> m_shenTypeList = new Collection<ShengTypeInfo>();

	public int GetSengCount()
	{
		return m_shenTypeList.Count;
	}

	public ShengTypeInfo GetShengTypeInfoByIndex(int index)
	{
		if (index >= m_shenTypeList.Count)
		{
			return null;
		}
		return m_shenTypeList[index];
	}

	public int GetCityCount(int indexSheng)
	{
		if (indexSheng >= m_shenTypeList.Count)
		{
			return 0;
		}
		return m_shenTypeList[indexSheng].m_cityTypeList.Count;
	}

	public CityTypeInfo GetCityTypeInfoByIndex(int indexSheng, int index)
	{
		if (indexSheng >= m_shenTypeList.Count)
		{
			return null;
		}
		if (index >= m_shenTypeList[indexSheng].m_cityTypeList.Count)
		{
			return null;
		}
		return m_shenTypeList[indexSheng].m_cityTypeList[index];
	}

	public CityType()
	{
		CityTypeInfo cityTypeInfo = null;
		Collection<CityTypeInfo> collection = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "1100");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("东城", "1101");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("西城", "1102");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("崇文", "1103");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宣武", "1104");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("朝阳", "1105");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("丰台", "1106");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("石景山", "1107");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("海淀", "1108");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("门头沟", "1109");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("房山", "1111");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("通州", "1112");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("顺义", "1113");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("昌平", "1121");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大兴", "1124");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("平谷", "1126");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("怀柔", "1127");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("密云", "1128");
		collection.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("延庆", "1129");
		collection.Add(cityTypeInfo);
		AddShen("北京", "11", collection);
		Collection<CityTypeInfo> collection2 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "3100");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黄浦", "3101");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南区", "3102");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("卢湾", "3103");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("徐汇", "3104");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("长宁", "3105");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("静安", "3106");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("普陀", "3107");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("闸北", "3108");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("虹口", "3109");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("杨浦", "3110");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("闵行", "3112");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宝山", "3113");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("嘉定", "3114");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("浦东新区", "3115");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("金山", "3116");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("松江", "3117");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南汇", "3125");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("奉贤", "3126");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("青浦", "3129");
		collection2.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("崇明", "3130");
		collection2.Add(cityTypeInfo);
		AddShen("上海", "31", collection2);
		Collection<CityTypeInfo> collection3 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "4400");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("广州", "4401");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("韶关", "4402");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("深圳", "4403");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("珠海", "4404");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("汕头", "4405");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("佛山", "4406");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("江门", "4407");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("湛江", "4408");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("茂名", "4409");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("肇庆", "4412");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("惠州", "4413");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("梅州", "4414");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("汕尾", "4415");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("河源", "4416");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阳江", "4417");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("清远", "4418");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("东莞", "4419");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("中山", "4420");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("潮州", "4451");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("揭阳", "4452");
		collection3.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("云浮", "4453");
		collection3.Add(cityTypeInfo);
		AddShen("广东", "44", collection3);
		Collection<CityTypeInfo> collection4 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "3400");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("合肥", "3401");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("芜湖", "3402");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("蚌埠", "3403");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("淮南", "3404");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("马鞍山", "3405");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("淮北", "3406");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("铜陵", "3407");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("安庆", "3408");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黄山", "3410");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("滁州", "3411");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阜阳", "3412");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宿州", "3413");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("巢湖", "3414");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("六安", "3415");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("亳州", "3416");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("池州", "3417");
		collection4.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宣城", "3418");
		collection4.Add(cityTypeInfo);
		AddShen("安徽", "34", collection4);
		Collection<CityTypeInfo> collection5 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "5000");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("万州", "5001");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("涪陵", "5002");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("渝中", "5003");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大渡口", "5004");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("江北", "5005");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("沙坪坝", "5006");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("九龙坡", "5007");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南岸", "5008");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("北碚", "5009");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("万盛", "5010");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("双桥", "5011");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("渝北", "5012");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("巴南", "5013");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("长寿", "5021");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("綦江", "5022");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("潼南", "5023");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("铜梁", "5024");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大足", "5025");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("荣昌", "5026");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("璧山", "5027");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("梁平", "5028");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("城口", "5029");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("丰都", "5030");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("垫江", "5031");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("武隆", "5032");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("忠县", "5033");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("开县", "5034");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("云阳", "5035");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("奉节", "5036");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("巫山", "5037");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("巫溪", "5038");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黔江", "5039");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("石柱", "5040");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("秀山", "5041");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("酉阳", "5042");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("彭水", "5043");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("江津", "5081");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("合川", "5082");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("永川", "5083");
		collection5.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南川", "5084");
		collection5.Add(cityTypeInfo);
		AddShen("重庆", "50", collection5);
		Collection<CityTypeInfo> collection6 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "3500");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("福州", "3501");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("厦门", "3502");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("莆田", "3503");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("三明", "3504");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("泉州", "3505");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("漳州", "3506");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南平", "3507");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("龙岩", "3508");
		collection6.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宁德", "3509");
		collection6.Add(cityTypeInfo);
		AddShen("福建", "35", collection6);
		Collection<CityTypeInfo> collection7 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "4600");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("海口", "4601");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("三亚", "4602");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("五指山", "4603");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("琼海", "4604");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("儋州", "4605");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("文昌", "4606");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("万宁", "4607");
		collection7.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("东方", "4608");
		collection7.Add(cityTypeInfo);
		AddShen("海南", "46", collection7);
		Collection<CityTypeInfo> collection8 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "1300");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("石家庄", "1301");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("唐山", "1302");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("秦皇岛", "1303");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("邯郸", "1304");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("邢台", "1305");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("保定", "1306");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("张家口", "1307");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("承德", "1308");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("沧州", "1309");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("廊坊", "1310");
		collection8.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("衡水", "1311");
		collection8.Add(cityTypeInfo);
		AddShen("河北", "13", collection8);
		Collection<CityTypeInfo> collection9 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "4100");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("郑州", "4101");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("开封", "4102");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("洛阳", "4103");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("平顶山", "4104");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("安阳", "4105");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("鹤壁", "4106");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("新乡", "4107");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("焦作", "4108");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("濮阳", "4109");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("许昌", "4110");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("漯河", "4111");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("三门峡", "4112");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南阳", "4113");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("商丘", "4114");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("信阳", "4115");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("周口", "4116");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("驻马店", "4117");
		collection9.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("济源", "4118");
		collection9.Add(cityTypeInfo);
		AddShen("河南", "41", collection9);
		Collection<CityTypeInfo> collection10 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "2300");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("哈尔滨", "2301");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("齐齐哈尔", "2302");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("鸡西", "2303");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("鹤岗", "2304");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("双鸭山", "2305");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大庆", "2306");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("伊春", "2307");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("佳木斯", "2308");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("七台河", "2309");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("牡丹江", "2310");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黑河", "2311");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("绥化", "2312");
		collection10.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大兴安岭", "2327");
		collection10.Add(cityTypeInfo);
		AddShen("黑龙江", "23", collection10);
		Collection<CityTypeInfo> collection11 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "4200");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("武汉", "4201");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黄石", "4202");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("十堰", "4203");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宜昌", "4205");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("襄樊", "4206");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("鄂州", "4207");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("荆门", "4208");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("孝感", "4209");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("荆州", "4210");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黄冈", "4211");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("咸宁", "4212");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("随州", "4213");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("恩施", "4228");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("仙桃", "4229");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("潜江", "4230");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("天门", "4231");
		collection11.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("神农架", "4232");
		collection11.Add(cityTypeInfo);
		AddShen("湖北", "42", collection11);
		Collection<CityTypeInfo> collection12 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "4300");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("长沙", "4301");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("株洲", "4302");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("湘潭", "4303");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("衡阳", "4304");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("邵阳", "4305");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("岳阳", "4306");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("常德", "4307");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("张家界", "4308");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("益阳", "4309");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("郴州", "4310");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("永州", "4311");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("怀化", "4312");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("娄底", "4313");
		collection12.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("湘西", "4331");
		collection12.Add(cityTypeInfo);
		AddShen("湖南", "43", collection12);
		Collection<CityTypeInfo> collection13 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "6200");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("兰州", "6201");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("嘉峪关", "6202");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("金昌", "6203");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("白银", "6204");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("天水", "6205");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("武威", "6206");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("张掖", "6207");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("平凉", "6208");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("酒泉", "6209");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("庆阳", "6210");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("定西", "6211");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("陇南", "6212");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("临夏", "6229");
		collection13.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("甘南", "6230");
		collection13.Add(cityTypeInfo);
		AddShen("甘肃", "62", collection13);
		Collection<CityTypeInfo> collection14 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "4500");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南宁", "4501");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("柳州", "4502");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("桂林", "4503");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("梧州", "4504");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("北海", "4505");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("防城港", "4506");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("钦州", "4507");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("贵港", "4508");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("玉林", "4509");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("百色", "4510");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("贺州", "4511");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("河池", "4512");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("来宾", "4513");
		collection14.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("崇左", "4514");
		collection14.Add(cityTypeInfo);
		AddShen("广西", "45", collection14);
		Collection<CityTypeInfo> collection15 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "5200");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("贵阳", "5201");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("六盘水", "5202");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("遵义", "5203");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("安顺", "5204");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("铜仁", "5222");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黔西南", "5223");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("毕节", "5224");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黔东南", "5226");
		collection15.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黔南", "5227");
		collection15.Add(cityTypeInfo);
		AddShen("贵州", "52", collection15);
		Collection<CityTypeInfo> collection16 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "2200");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("长春", "2201");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("吉林", "2202");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("四平", "2203");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("辽源", "2204");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("通化", "2205");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("白山", "2206");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("松原", "2207");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("白城", "2208");
		collection16.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("延边", "2224");
		collection16.Add(cityTypeInfo);
		AddShen("吉林", "22", collection16);
		Collection<CityTypeInfo> collection17 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "3600");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南昌", "3601");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("景德镇", "3602");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("萍乡", "3603");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("九江", "3604");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("新余", "3605");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("鹰潭", "3606");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("赣州", "3607");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("吉安", "3608");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宜春", "3609");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("抚州", "3610");
		collection17.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("上饶", "3611");
		collection17.Add(cityTypeInfo);
		AddShen("江西", "36", collection17);
		Collection<CityTypeInfo> collection18 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "3200");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南京", "3201");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("无锡", "3202");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("徐州", "3203");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("常州", "3204");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("苏州", "3205");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南通", "3206");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("连云港", "3207");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("淮安", "3208");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("盐城", "3209");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("扬州", "3210");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("镇江", "3211");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("泰州", "3212");
		collection18.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宿迁", "3213");
		collection18.Add(cityTypeInfo);
		AddShen("江苏", "32", collection18);
		Collection<CityTypeInfo> collection19 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "2100");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("沈阳", "2101");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大连", "2102");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("鞍山", "2103");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("抚顺", "2104");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("本溪", "2105");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("丹东", "2106");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("锦州", "2107");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("营口", "2108");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阜新", "2109");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("辽阳", "2110");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("盘锦", "2111");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("铁岭", "2112");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("朝阳", "2113");
		collection19.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("葫芦岛", "2114");
		collection19.Add(cityTypeInfo);
		AddShen("辽宁", "21", collection19);
		Collection<CityTypeInfo> collection20 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "1500");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("呼和浩特", "1501");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("包头", "1502");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("乌海", "1503");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("赤峰", "1504");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("通辽", "1505");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("鄂尔多斯", "1506");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("呼伦贝尔", "1507");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("巴彦淖尔", "1508");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("乌兰察布", "1509");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("兴安", "1522");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("锡林郭勒", "1525");
		collection20.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阿拉善", "1529");
		collection20.Add(cityTypeInfo);
		AddShen("内蒙古", "15", collection20);
		Collection<CityTypeInfo> collection21 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "6400");
		collection21.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("银川", "6401");
		collection21.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("石嘴山", "6402");
		collection21.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("吴忠", "6403");
		collection21.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("固原", "6404");
		collection21.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("中卫", "6405");
		collection21.Add(cityTypeInfo);
		AddShen("宁夏", "64", collection21);
		Collection<CityTypeInfo> collection22 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "6300");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("西宁", "6301");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("海东", "6321");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("海北", "6322");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黄南", "6323");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("海南", "6325");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("果洛", "6326");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("玉树", "6327");
		collection22.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("海西", "6328");
		collection22.Add(cityTypeInfo);
		AddShen("青海", "63", collection22);
		Collection<CityTypeInfo> collection23 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "3700");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("济南", "3701");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("青岛", "3702");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("淄博", "3703");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("枣庄", "3704");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("东营", "3705");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("烟台", "3706");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("潍坊", "3707");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("济宁", "3708");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("泰安", "3709");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("威海", "3710");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("日照", "3711");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("莱芜", "3712");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("临沂", "3713");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("德州", "3714");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("聊城", "3715");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("滨州", "3716");
		collection23.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("菏泽", "3717");
		collection23.Add(cityTypeInfo);
		AddShen("山东", "37", collection23);
		Collection<CityTypeInfo> collection24 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "1400");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("太原", "1401");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大同", "1402");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阳泉", "1403");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("长治", "1404");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("晋城", "1405");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("朔州", "1406");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("晋中", "1407");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("运城", "1408");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("忻州", "1409");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("临汾", "1410");
		collection24.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("吕梁", "1411");
		collection24.Add(cityTypeInfo);
		AddShen("山西", "14", collection24);
		Collection<CityTypeInfo> collection25 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "6100");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("西安", "6101");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("铜川", "6102");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宝鸡", "6103");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("咸阳", "6104");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("渭南", "6105");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("延安", "6106");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("汉中", "6107");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("榆林", "6108");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("安康", "6109");
		collection25.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("商洛", "6110");
		collection25.Add(cityTypeInfo);
		AddShen("陕西", "61", collection25);
		Collection<CityTypeInfo> collection26 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "5100");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("成都", "5101");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("自贡", "5103");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("攀枝花", "5104");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("泸州", "5105");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("德阳", "5106");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("绵阳", "5107");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("广元", "5108");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("遂宁", "5109");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("内江", "5110");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("乐山", "5111");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南充", "5113");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("眉山", "5114");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宜宾", "5115");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("广安", "5116");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("达州", "5117");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("雅安", "5118");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("巴中", "5119");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("资阳", "5120");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阿坝", "5132");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("甘孜", "5133");
		collection26.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("凉山", "5134");
		collection26.Add(cityTypeInfo);
		AddShen("四川", "51", collection26);
		Collection<CityTypeInfo> collection27 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "1200");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("和平", "1201");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("河东", "1202");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("河西", "1203");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南开", "1204");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("河北", "1205");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("红桥", "1206");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("塘沽", "1207");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("汉沽", "1208");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大港", "1209");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("东丽", "1210");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("西青", "1211");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("津南", "1212");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("北辰", "1213");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宁河", "1221");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("武清", "1222");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("静海", "1223");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宝坻", "1224");
		collection27.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("蓟县", "1225");
		collection27.Add(cityTypeInfo);
		AddShen("天津", "12", collection27);
		Collection<CityTypeInfo> collection28 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "5400");
		collection28.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("拉萨", "5401");
		collection28.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("昌都", "5421");
		collection28.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("山南", "5422");
		collection28.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("日喀则", "5423");
		collection28.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("那曲", "5424");
		collection28.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阿里", "5425");
		collection28.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("林芝", "5426");
		collection28.Add(cityTypeInfo);
		AddShen("西藏", "54", collection28);
		Collection<CityTypeInfo> collection29 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "6500");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("乌鲁木齐", "6501");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("克拉玛依", "6502");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("吐鲁番", "6521");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("哈密", "6522");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("昌吉", "6523");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("博尔塔拉", "6527");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("巴音郭楞", "6528");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阿克苏", "6529");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("克孜勒苏", "6530");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("喀什", "6531");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("和田", "6532");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("伊犁", "6540");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("塔城", "6542");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阿勒泰", "6543");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("石河子", "6544");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("阿拉尔", "6545");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("图木舒克", "6546");
		collection29.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("五家渠", "6547");
		collection29.Add(cityTypeInfo);
		AddShen("新疆", "65", collection29);
		Collection<CityTypeInfo> collection30 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "5300");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("昆明", "5301");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("曲靖", "5303");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("玉溪", "5304");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("保山", "5305");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("昭通", "5306");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("丽江", "5307");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("思茅", "5308");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("临沧", "5309");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("楚雄", "5323");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("红河", "5325");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("文山", "5326");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("西双版纳", "5328");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大理", "5329");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("德宏", "5331");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("怒江傈", "5333");
		collection30.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("迪庆", "5334");
		collection30.Add(cityTypeInfo);
		AddShen("云南", "53", collection30);
		Collection<CityTypeInfo> collection31 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "3300");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("杭州", "3301");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宁波", "3302");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("温州", "3303");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("嘉兴", "3304");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("湖州", "3305");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("绍兴", "3306");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("金华", "3307");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("衢州", "3308");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("舟山", "3309");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台州", "3310");
		collection31.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("丽水", "3311");
		collection31.Add(cityTypeInfo);
		AddShen("浙江", "33", collection31);
		Collection<CityTypeInfo> collection32 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "7100");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台北市", "7101");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("高雄市", "7102");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("基隆市", "7103");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台中市", "7104");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台南市", "7105");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("新竹市", "7106");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("嘉义市", "7107");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台北县", "7108");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("宜兰县", "7109");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("新竹县", "7110");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("桃园县", "7111");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("苗栗县", "7112");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台中县", "7113");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("彰化县", "7114");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南投县", "7115");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("嘉义县", "7116");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("云林县", "7117");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台南县", "7118");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("高雄县", "7119");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("屏东县", "7120");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("台东县", "7121");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("花莲县", "7122");
		collection32.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("澎湖县", "7123");
		collection32.Add(cityTypeInfo);
		AddShen("台湾", "71", collection32);
		Collection<CityTypeInfo> collection33 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "8100");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("中西区", "8101");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("东区", "8102");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("九龙城区", "8103");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("观塘区", "8104");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("南区", "8105");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("深水区", "8106");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("湾仔区", "8107");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("黄大仙区", "8108");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("油尖旺区", "8109");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("离岛区", "8110");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("葵青区", "8111");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("北区", "8112");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("西贡区", "8113");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("沙田区", "8114");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("屯门区", "8115");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大埔区", "8116");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("荃湾区", "8117");
		collection33.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("元朗区", "8118");
		collection33.Add(cityTypeInfo);
		AddShen("香港", "81", collection33);
		Collection<CityTypeInfo> collection34 = new Collection<CityTypeInfo>();
		cityTypeInfo = new CityTypeInfo("不限", "8200");
		collection34.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("花地玛堂区", "8201");
		collection34.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("圣安多尼堂区", "8202");
		collection34.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("大堂区", "8203");
		collection34.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("望德堂区", "8204");
		collection34.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("风顺堂区", "8205");
		collection34.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("嘉模堂区", "8206");
		collection34.Add(cityTypeInfo);
		cityTypeInfo = new CityTypeInfo("圣方济各堂区", "8207");
		collection34.Add(cityTypeInfo);
		AddShen("澳门", "82", collection34);
	}

	public void AddShen(string shenname, string code, Collection<CityTypeInfo> cityTypeList)
	{
		ShengTypeInfo item = new ShengTypeInfo(shenname, code, cityTypeList);
		m_shenTypeList.Add(item);
	}
}
