using System;

namespace Alphaleonis.Win32.Security;

[Flags]
internal enum SECURITY_INFORMATION : uint
{
	None = 0u,
	OWNER_SECURITY_INFORMATION = 1u,
	GROUP_SECURITY_INFORMATION = 2u,
	DACL_SECURITY_INFORMATION = 4u,
	SACL_SECURITY_INFORMATION = 8u,
	LABEL_SECURITY_INFORMATION = 0x10u,
	ATTRIBUTE_SECURITY_INFORMATION = 0x20u,
	SCOPE_SECURITY_INFORMATION = 0x40u,
	BACKUP_SECURITY_INFORMATION = 0x10000u,
	UNPROTECTED_SACL_SECURITY_INFORMATION = 0x10000000u,
	UNPROTECTED_DACL_SECURITY_INFORMATION = 0x20000000u,
	PROTECTED_SACL_SECURITY_INFORMATION = 0x40000000u,
	PROTECTED_DACL_SECURITY_INFORMATION = 0x80000000u
}
