using System;

namespace Alphaleonis.Win32.Security;

[Flags]
internal enum SECURITY_DESCRIPTOR_CONTROL
{
	None = 0,
	SE_OWNER_DEFAULTED = 1,
	SE_GROUP_DEFAULTED = 2,
	SE_DACL_PRESENT = 4,
	SE_DACL_DEFAULTED = 8,
	SE_SACL_PRESENT = 0x10,
	SE_SACL_DEFAULTED = 0x20,
	SE_DACL_AUTO_INHERIT_REQ = 0x100,
	SE_SACL_AUTO_INHERIT_REQ = 0x200,
	SE_DACL_AUTO_INHERITED = 0x400,
	SE_SACL_AUTO_INHERITED = 0x800,
	SE_DACL_PROTECTED = 0x1000,
	SE_SACL_PROTECTED = 0x2000,
	SE_RM_CONTROL_VALID = 0x4000,
	SE_SELF_RELATIVE = 0x8000
}
