namespace eRgfvqXMjSCmTgpcZnDeiuIsvZuQjEYRTGnJMDeZHHBuxkNVkRsvlQm2;

public class ficken
{
	public static string fakeString = "PFluOUlGNTvmDlLCzBPOyEqSEedCNImuwSsupofBvpsBcNCruXeGgvglpsQJRITfGaPKTrmlwotjmOPQBLiPEGnbMgfWyvJMvnVcXRxdLSkScWZADahgAeAaMOYNlpMaEGNYTNSKneeLwvYPhFtxnDlrMVpjTKSvgjnvjaGPhxSwZOErQjFFVpMbvwmXxJQClIFmhCFgYEpQKPrXrYsJemzQxmaNOIryGpkrjrjnDzGrZWqFeoGzqhyYiOPUCSspmRjvFaOZOffFGiRBWvIzcRizRliuCpLLgrehMVadzGLlbSsaWoYgkSnvJKDuStxztuzoeJObvEZvgWxZShxorEAndJycrGlgjmRHteWnzWLFTRoMmEBKWihPTlkukLKOtTlUfQFOlkOuSVumuMQMeAkbebNhTBcOmWmZGuGwYNzLtNWXRYayUXKSJjQdcyVKiaiVJuFagtNrayHrfPpUBETomtqwDCtASPCtEbowtZrAjtRkCyYmiaiEgTJqejwEanylWoMdBSBBmsfTBfUfDhsRGYnLsYskCNAWUGooMULpzHrNOQPZoraSUGFXabLDArYzRiYURGsIwcsZGzXBitVkMIbnbqnKihOiISVFRUhIYrwSoGrAejuhvNMjgKTAsIzonkqOErKolnmvljZvZMGYNHMUgMyhbHpqRiEepCWMzgViBqXXLyAGbAAFxwISSCnDXVDdFUfwPUzHMEsPOBwDgIpqHYGTUeTXSrkGNUrQseQhbTTTdTdrgKxpGmwHnmCKaBOutMbUkFkcRioOeNPbaCQiUVaAyKCfCggzeyzrRjhAzvxxXICAwBJxLGAxMBwzceALbPJGnyjRvpJzyCCPicIbwIOyYcEqNHxuVLviYWmYrScvXbZjYGrawzptalHlTTdNRoEMhtRmPKJDGtBWcvrhqxYvvciNobexPoDIxmcEOekLPMNHJLiyBVxuqireleYOGmOrPSzQsMtlmmGJpBdCSFVTRispVXtK";
}
