using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;

[assembly: AssemblyCompany("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyProduct("")]
[assembly: NeutralResourcesLanguage("ps-AF")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyTitle("")]
[assembly: ComVisible(true)]
[assembly: AssemblyKeyName("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyVersion("0.0.0.0")]
