using System.ComponentModel;

namespace ns27;

internal enum Enum2
{
	[Description("")]
	const_0,
	[Description("Sniper_AWM_")]
	const_1,
	[Description("Sniper_AWM")]
	const_2,
	[Description("Sniper_QBU")]
	const_3,
	[Description("Sniper_SLR")]
	const_4,
	[Description("Sniper_SKS")]
	const_5,
	[Description("Sniper_Mini14")]
	const_6,
	[Description("Sniper_M24")]
	const_7,
	[Description("Sniper_Kar98k")]
	const_8,
	[Description("Sniper_VSS")]
	const_9,
	[Description("Sniper_Win94")]
	const_10,
	[Description("Rifle_AUG_C")]
	const_11,
	[Description("Rifle_M762")]
	const_12,
	[Description("SCAR-L")]
	const_13,
	[Description("Rifle_M4")]
	const_14,
	[Description("Rifle_M16A4")]
	const_15,
	[Description("Rifle_Mk47")]
	const_16,
	[Description("Rifle_G3")]
	const_17,
	[Description("Rifle_QBZ")]
	const_18,
	[Description("Rifle_AKM")]
	const_19,
	[Description("Rifle_Groza")]
	const_20,
	[Description("Rifle_AUG_")]
	const_21,
	[Description("Rifle_DP28")]
	const_22,
	[Description("Rifle_M249")]
	const_23,
	[Description("Rifle_M249_")]
	const_24,
	[Description("Rifle_Mk14_")]
	const_25,
	[Description("Rifle_Mk14")]
	const_26,
	[Description("ShotGun_S12K")]
	const_27,
	[Description("ShotGun_DP12")]
	const_28,
	[Description("ShotGun_S686")]
	const_29,
	[Description("ShotGun_S1897")]
	const_30,
	[Description("ShotGun_SawedOff")]
	const_31,
	[Description("M_PP19")]
	const_32,
	[Description("Tommy_Gun")]
	const_33,
	[Description("MP5K_")]
	const_34,
	[Description("UMP9_")]
	const_35,
	[Description("Vector_")]
	const_36,
	[Description("_Uzi_")]
	const_37,
	[Description("Pistol_R1895")]
	const_38,
	[Description("Pistol_Vz61")]
	const_39,
	[Description("Pistol_P92")]
	const_40,
	[Description("Pistol_P18C")]
	const_41,
	[Description("Pistol_R4")]
	const_42,
	[Description("Pistol_P1911")]
	const_43,
	[Description("Pistol_D_Eagle")]
	const_44,
	[Description("WEP_CrossBow")]
	const_45,
	[Description("WEP_Sickle")]
	const_46,
	[Description("WEP_Machete")]
	const_47,
	[Description("WEP_Cowbar")]
	const_48,
	[Description("WEP_Pan")]
	const_49,
	[Description("WEP_Pan")]
	const_50,
	[Description("Ammo_762mm")]
	const_51,
	[Description("Ammo_45ACP")]
	const_52,
	[Description("Ammo_556mm")]
	const_53,
	[Description("Ammo_9mm")]
	const_54,
	[Description("Ammo_300Magnum")]
	const_55,
	[Description("Ammo_12Guage")]
	const_56,
	[Description("Ammo_Bolt")]
	const_57,
	[Description("QK_Mid_FlashHider")]
	const_58,
	[Description("QK_FlashHider_Rifle")]
	const_59,
	[Description("QK_Compensator_Rifle")]
	const_60,
	[Description("QK_Mid_Compensator")]
	const_61,
	[Description("QT_Tactical_Rifle")]
	const_62,
	[Description("QK_DuckBill")]
	const_63,
	[Description("QK_Sniper_FlashHider")]
	const_64,
	[Description("QK_Mid_Suppressor")]
	const_65,
	[Description("QT_Sniper_Pickup")]
	const_66,
	[Description("QK_Choke")]
	const_67,
	[Description("QT_UZI_Pickup")]
	const_68,
	[Description("QK_Sniper_Compensator")]
	const_69,
	[Description("QK_Sniper_Suppressor")]
	const_70,
	[Description("QK_Suppressor_Rifle")]
	const_71,
	[Description("DJ_Sniper_Mag7")]
	const_72,
	[Description("DJ_Mid_E")]
	const_73,
	[Description("DJ_Mid_Q")]
	const_74,
	[Description("DJ_Sniper_Mag")]
	const_75,
	[Description("DJ_Sniper_QuicMag")]
	const_76,
	[Description("DJ_Mag30_Rifle")]
	const_77,
	[Description("DJ_QuicMag40_Rifle")]
	const_78,
	[Description("DJ_Mag40_Rifle")]
	const_79,
	[Description("DJ_Mid_EQ")]
	const_80,
	[Description("ZDD_Crossbow_Q")]
	const_81,
	[Description("ZDD_Sniper")]
	const_82,
	[Description("Scope_8x")]
	const_83,
	[Description("Scope_2x")]
	const_84,
	[Description("Scope_Redot")]
	const_85,
	[Description("Scope_3x")]
	const_86,
	[Description("Scope_Holo")]
	const_87,
	[Description("Scope_6x")]
	const_88,
	[Description("Scope_4x")]
	const_89,
	[Description("Bag Lv3")]
	const_90,
	[Description("Bag_Lv3")]
	const_91,
	[Description("Bag_Lv2")]
	const_92,
	[Description("Bag_Lv2")]
	const_93,
	[Description("BP_Bag_Lv1")]
	const_94,
	[Description("BP_Bag_Lv1_")]
	const_95,
	[Description("BP_Armor_Lv1")]
	const_96,
	[Description("BP_Armor_Lv1_")]
	const_97,
	[Description("Armor_Lv3")]
	const_98,
	[Description("Armor_Lv3")]
	const_99,
	[Description("Armor_Lv2")]
	const_100,
	[Description("Armor_Lv2")]
	const_101,
	[Description("Helmet_Lv3")]
	const_102,
	[Description("Helmet_Lv3")]
	const_103,
	[Description("Helmet_Lv2")]
	const_104,
	[Description("Helmet_Lv2")]
	const_105,
	[Description("BP_Helmet_Lv1")]
	const_106,
	[Description("BP_Helmet_Lv1_")]
	const_107,
	[Description("Grenade_Shoulei_")]
	const_108,
	[Description("Grenade_Shoulei")]
	const_109,
	[Description("Grenade_Smoke_")]
	const_110,
	[Description("Grenade_Smoke")]
	const_111,
	[Description("Grenade_Burn_")]
	const_112,
	[Description("Grenade_Burn")]
	const_113,
	[Description("Grenade_Apple_")]
	const_114,
	[Description("PainKiller_")]
	const_115,
	[Description("AdrenalinInjection_")]
	const_116,
	[Description("EnergyDrink_")]
	const_117,
	[Description("Firstaid_")]
	const_118,
	[Description("Bandage_")]
	const_119,
	[Description("Player_Pawn")]
	const_120,
	[Description("PlayerPawn_ZNQ")]
	const_121,
	[Description("WB_ThumbGrip")]
	const_122,
	[Description("WB_Lasersight")]
	const_123,
	[Description("WB_Angled")]
	const_124,
	[Description("WB_LightGrip")]
	const_125,
	[Description("WB_HalfGrip")]
	const_126,
	[Description("WB_Vertical_Rifle")]
	const_127,
	[Description("Game_Coin")]
	const_128,
	[Description("BlindBo_xMachine")]
	const_129,
	[Description("MiniGame_Machine")]
	const_130,
	[Description("Grenade_ColorBall")]
	const_131,
	[Description("Air_Drop")]
	const_132,
	[Description("First_Aidbox")]
	const_133,
	[Description("Ammo_Flare")]
	const_134,
	[Description("BP_Bag_Lv3_Inbox")]
	const_135,
	[Description("BP_Bag_Lv2_Inbox")]
	const_136,
	[Description("BP_Bag_Lv1")]
	const_137,
	[Description("QK_Mid_Compensator")]
	const_138,
	[Description("BP_Helmet_Lv2")]
	const_139,
	[Description("BP_Ghillie_4")]
	const_140,
	[Description("BP_Ghillie_1")]
	const_141,
	[Description("BP_Ghillie_2")]
	const_142,
	[Description("BP_Ghillie_3")]
	const_143,
	[Description("Pistol_Flaregun")]
	const_144,
	[Description("Air_Drop_Box")]
	const_145,
	[Description("Player_DeadInventoryBox")]
	const_146,
	[Description("GasCan_Destructible")]
	const_147,
	[Description("Create_Box")]
	const_148,
	[Description("[Bag] Lv.3")]
	const_149,
	[Description("[Bag] Lv.2")]
	const_150,
	[Description("[Armor] Lv.2")]
	const_151,
	[Description("[Armor] Lv.3")]
	const_152,
	[Description("[Armor] Lv.3")]
	const_153,
	[Description("[Armor] Lv.2")]
	const_154,
	[Description("[Rifle] SCAR-L")]
	const_155
}
