using System;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Windows.Forms;

internal delegate Type _0001(RuntimeTypeHandle);
internal delegate Assembly _0002(object);
internal delegate SettingsBase _0003(SettingsBase);
internal delegate void _0004(object, double);
internal delegate void _0005(object, bool);
internal delegate void _0006(object);
internal delegate Assembly _0007();
internal delegate string _0008(object);
internal delegate string _000E(object, string, string);
internal delegate bool _000F(object, string);
internal delegate void _0010();
internal delegate void _0011(bool);
internal delegate void _0012(Form);
internal delegate bool _0013(string, string);
internal delegate int _0014(string);
internal delegate Stream _0015(object, string);
internal delegate long _0016(object);
internal delegate int _0017(long);
internal delegate int _0018(object, byte[], int, int);
internal delegate Encoding _0019();
internal delegate string _001A(object, byte[], int, int);
internal delegate byte[] _001B(string);
internal delegate string _001C(string);
internal delegate string[] _001D(string);
internal delegate byte[] _001E(object, string);
internal delegate SHA256 _001F();
internal delegate byte[] _007F(object, byte[]);
internal delegate void _0080(string, byte[]);
internal delegate string _0081(string, string, string);
internal delegate void _0082(string, string);
internal delegate string _0083();
internal delegate string[] _0084();
internal delegate void _0086(Array, RuntimeFieldHandle);
internal delegate void _0087(object, int);
internal delegate int _0088(object);
internal delegate byte[] _0089(object, int);
internal delegate void _008A(object, byte[]);
internal delegate void _008B(object, CipherMode);
internal delegate ICryptoTransform _008C(object);
internal delegate void _008D(object, byte[], int, int);
internal delegate byte[] _008E(object);
internal delegate void _008F(object, SizeF);
internal delegate void _0090(object, AutoScaleMode);
internal delegate void _0091(object, Size);
internal delegate void _0092(object, string);
internal delegate void _0093(object, EventHandler);
internal delegate void _0094(object);
internal delegate string _0095(object, byte[]);
internal delegate string _0096(string, string);
internal delegate void _0097(string, string[]);
internal delegate Process _0098(string);
internal delegate void _0099(object, ProcessWindowStyle);
internal delegate Process _009A(ProcessStartInfo);
internal delegate int _009B(object, int);
internal delegate char _009C(object, int);
internal delegate StringBuilder _009D(object, char);
