using System;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;

internal delegate int _0001(object);
internal delegate int _0002(object, int);
internal delegate char _0003(object, int);
internal delegate string _0004(string, string);
internal delegate DateTime _0005();
internal delegate string _0006(Environment.SpecialFolder);
internal delegate DateTime _0007(string);
internal delegate string _0008(object, int, int);
internal delegate string _000E(object, int);
internal delegate int _000F(string);
internal delegate string _0010(object);
internal delegate string _0011(string, string, string);
internal delegate void _0012(string, DateTime);
internal delegate string _0013(string);
internal delegate bool _0014(string, string);
internal delegate void _0015(string, string);
internal delegate void _0016(object);
internal delegate string _0017(byte[]);
internal delegate void _0018(object, string);
internal delegate string _0019(object, string, string);
internal delegate Encoding _001A();
internal delegate void _001B(string, string, Encoding);
internal delegate bool _001C(string);
internal delegate void _001D(string, byte[]);
internal delegate Process _001E(string);
internal delegate SettingsBase _001F(SettingsBase);
internal delegate string _007F(string, object[]);
internal delegate bool _0080(Version, Version);
internal delegate bool _0081(string, ref int);
internal delegate bool _0082(char);
internal delegate Type _0083(RuntimeTypeHandle);
internal delegate int _0084(Type);
internal delegate bool _0086(IntPtr, IntPtr);
internal delegate long _0087(byte[], int);
internal delegate int _0088(byte[], int);
internal delegate string _0089(object, byte[]);
internal delegate string _008A(object, char[]);
internal delegate string _008B(object, byte[], int, int);
internal delegate Assembly _008C();
internal delegate Stream _008D(object, string);
internal delegate long _008E(object);
internal delegate int _008F(long);
internal delegate int _0090(object, byte[], int, int);
internal delegate bool _0091(object);
internal delegate void _0092(object, string, string);
internal delegate Type _0093(object);
internal delegate StringBuilder _0094(object, char);
internal delegate StringBuilder _0095(object, string);
internal delegate Module _0096(object);
internal delegate Assembly _0097(object);
internal delegate Type _0098(object, string);
internal delegate Guid _0099(object);
internal delegate AssemblyName _009A(object);
internal delegate int _009B(object, string);
internal delegate bool _009C(Guid, Guid);
internal delegate Guid _009D();
internal delegate Version _009E();
internal delegate OperatingSystem _009F();
