using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Windows.Forms;
using Microsoft.CSharp.RuntimeBinder;

internal delegate void _0001();
internal delegate void _0002(bool);
internal delegate void _0003(Form);
internal delegate string _0004(string, string, string);
internal delegate Encoding _0005();
internal delegate string _0006(object, byte[], int, int);
internal delegate byte[] _0007(string);
internal delegate string _0008(string);
internal delegate void _000E(int);
internal delegate AppDomain _000F();
internal delegate Assembly _0010(object, byte[]);
internal delegate Type _0011(object, string);
internal delegate object _0012(Type);
internal delegate Type _0013(RuntimeTypeHandle);
internal delegate CSharpArgumentInfo _0014(CSharpArgumentInfoFlags, string);
internal delegate CallSiteBinder _0015(CSharpBinderFlags, string, IEnumerable<Type>, Type, IEnumerable<CSharpArgumentInfo>);
internal delegate void _0016(object);
internal delegate Assembly _0017();
internal delegate object _0018(object, string);
internal delegate void _0019(object);
internal delegate string _001A(string, string);
internal delegate int _001B(object);
internal delegate void _001C(Array, RuntimeFieldHandle);
internal delegate void _001D(object, int);
internal delegate byte[] _001E(object, string);
internal delegate byte[] _001F(object, int);
internal delegate void _007F(object, byte[]);
internal delegate void _0080(object, CipherMode);
internal delegate ICryptoTransform _0081(object);
internal delegate void _0082(object, byte[], int, int);
internal delegate byte[] _0083(object);
internal delegate long _0084(byte[], int);
internal delegate int _0086(byte[], int);
internal delegate string _0087(object, byte[]);
internal delegate string _0088(object, char[]);
internal delegate bool _0089(string, string);
internal delegate int _008A(string);
internal delegate Stream _008B(object, string);
internal delegate long _008C(object);
internal delegate int _008D(long);
internal delegate int _008E(object, byte[], int, int);
