namespace Orcus.Native.Display;

public enum DISPLAYCONFIG_MODE_INFO_TYPE : uint
{
	DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE = 1u,
	DISPLAYCONFIG_MODE_INFO_TYPE_TARGET = 2u,
	DISPLAYCONFIG_MODE_INFO_TYPE_FORCE_UINT32 = uint.MaxValue
}
