namespace Orcus.Native.Display;

public enum DISPLAYCONFIG_DEVICE_INFO_TYPE : uint
{
	DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1u,
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2u,
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE = 3u,
	DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME = 4u,
	DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE = 5u,
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE = 6u,
	DISPLAYCONFIG_DEVICE_INFO_FORCE_UINT32 = uint.MaxValue
}
