namespace Orcus.Native.Display;

public enum DISPLAYCONFIG_ROTATION : uint
{
	DISPLAYCONFIG_ROTATION_IDENTITY = 1u,
	DISPLAYCONFIG_ROTATION_ROTATE90 = 2u,
	DISPLAYCONFIG_ROTATION_ROTATE180 = 3u,
	DISPLAYCONFIG_ROTATION_ROTATE270 = 4u,
	DISPLAYCONFIG_ROTATION_FORCE_UINT32 = uint.MaxValue
}
