namespace Orcus.Native.Display;

public enum DISPLAYCONFIG_PIXELFORMAT : uint
{
	DISPLAYCONFIG_PIXELFORMAT_8BPP = 1u,
	DISPLAYCONFIG_PIXELFORMAT_16BPP = 2u,
	DISPLAYCONFIG_PIXELFORMAT_24BPP = 3u,
	DISPLAYCONFIG_PIXELFORMAT_32BPP = 4u,
	DISPLAYCONFIG_PIXELFORMAT_NONGDI = 5u,
	DISPLAYCONFIG_PIXELFORMAT_FORCE_UINT32 = uint.MaxValue
}
