namespace Orcus.Native.Display;

public enum DISPLAYCONFIG_SCANLINE_ORDERING : uint
{
	DISPLAYCONFIG_SCANLINE_ORDERING_UNSPECIFIED = 0u,
	DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE = 1u,
	DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED = 2u,
	DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_UPPERFIELDFIRST = 2u,
	DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_LOWERFIELDFIRST = 3u,
	DISPLAYCONFIG_SCANLINE_ORDERING_FORCE_UINT32 = uint.MaxValue
}
