namespace Orcus.Native.Display;

public enum DISPLAYCONFIG_SCALING : uint
{
	DISPLAYCONFIG_SCALING_IDENTITY = 1u,
	DISPLAYCONFIG_SCALING_CENTERED = 2u,
	DISPLAYCONFIG_SCALING_STRETCHED = 3u,
	DISPLAYCONFIG_SCALING_ASPECTRATIOCENTEREDMAX = 4u,
	DISPLAYCONFIG_SCALING_CUSTOM = 5u,
	DISPLAYCONFIG_SCALING_PREFERRED = 128u,
	DISPLAYCONFIG_SCALING_FORCE_UINT32 = uint.MaxValue
}
