namespace Orcus.Native;

public enum DiFunction
{
	SelectDevice = 1,
	InstallDevice = 2,
	AssignResources = 3,
	Properties = 4,
	Remove = 5,
	FirstTimeSetup = 6,
	FoundDevice = 7,
	SelectClassDrivers = 8,
	ValidateClassDrivers = 9,
	InstallClassDrivers = 10,
	CalcDiskSpace = 11,
	DestroyPrivateData = 12,
	ValidateDriver = 13,
	Detect = 15,
	InstallWizard = 16,
	DestroyWizardData = 17,
	PropertyChange = 18,
	EnableClass = 19,
	DetectVerify = 20,
	InstallDeviceFiles = 21,
	UnRemove = 22,
	SelectBestCompatDrv = 23,
	AllowInstall = 24,
	RegisterDevice = 25,
	NewDeviceWizardPreSelect = 26,
	NewDeviceWizardSelect = 27,
	NewDeviceWizardPreAnalyze = 28,
	NewDeviceWizardPostAnalyze = 29,
	NewDeviceWizardFinishInstall = 30,
	Unused1 = 31,
	InstallInterfaces = 32,
	DetectCancel = 33,
	RegisterCoInstallers = 34,
	AddPropertyPageAdvanced = 35,
	AddPropertyPageBasic = 36,
	Reserved1 = 37,
	Troubleshooter = 38,
	PowerMessageWake = 39,
	AddRemotePropertyPageAdvanced = 40,
	UpdateDriverUI = 41,
	Reserved2 = 48
}
