namespace MySqlX.Communication;

internal enum ClientMessageId
{
	CON_CAPABILITIES_GET = 1,
	CON_CAPABILITIES_SET = 2,
	CON_CLOSE = 3,
	SESS_AUTHENTICATE_START = 4,
	SESS_AUTHENTICATE_CONTINUE = 5,
	SESS_RESET = 6,
	SESS_CLOSE = 7,
	SQL_STMT_EXECUTE = 12,
	CRUD_FIND = 17,
	CRUD_INSERT = 18,
	CRUD_UPDATE = 19,
	CRUD_DELETE = 20,
	EXPECT_OPEN = 24,
	EXPECT_CLOSE = 25,
	COMPRESSION = 46
}
