using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;

[assembly: Guid("05584398-1516-45e4-a7da-4e2099d661c2")]
[assembly: ComVisible(false)]
[assembly: AssemblyFileVersion("7.701.43.3")]
[assembly: NeutralResourcesLanguage("fo-FO")]
[assembly: AssemblyTrademark("umrturmeutmrtu")]
[assembly: AssemblyProduct("tumert")]
[assembly: AssemblyCompany("tumrtu")]
[assembly: AssemblyDescription("umertum")]
[assembly: AssemblyCopyright("tumrtu")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTitle("serheruru")]
[assembly: AssemblyVersion("4.701.43.3")]
