namespace IntelliLock.Licensing;

[Attribute1(CBPJIFOEJODEDAIKFEHLINCOJEILAOPJLPJM = true, MILJMOALDHJBDENJEIFBOPJBAHHFENPIBGJJ = true, GPLINEOBJKEEECKFEIKDKBKILCBHDFGDIEPC = true)]
internal enum LicenseLocation
{
	[Attribute1(CBPJIFOEJODEDAIKFEHLINCOJEILAOPJLPJM = true, GPLINEOBJKEEECKFEIKDKBKILCBHDFGDIEPC = false)]
	Inbuilt,
	[Attribute1(CBPJIFOEJODEDAIKFEHLINCOJEILAOPJLPJM = true, GPLINEOBJKEEECKFEIKDKBKILCBHDFGDIEPC = false)]
	ExternalAssembly,
	[Attribute1(CBPJIFOEJODEDAIKFEHLINCOJEILAOPJLPJM = true, GPLINEOBJKEEECKFEIKDKBKILCBHDFGDIEPC = false)]
	HDD
}
