using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace _0xHSli2ken;

[CompilerGenerated]
[TypeIdentifier("728ab348-217d-11da-b2a4-000e7bbb2b09", "CERTENROLLLib.CERTENROLL_PROPERTYID")]
public enum CERTENROLL_PROPERTYID
{
	XCN_PROPERTYID_NONE = 0,
	XCN_CERT_KEY_PROV_HANDLE_PROP_ID = 1,
	XCN_CERT_KEY_PROV_INFO_PROP_ID = 2,
	XCN_CERT_SHA1_HASH_PROP_ID = 3,
	XCN_CERT_MD5_HASH_PROP_ID = 4,
	XCN_CERT_HASH_PROP_ID = 3,
	XCN_CERT_KEY_CONTEXT_PROP_ID = 5,
	XCN_CERT_KEY_SPEC_PROP_ID = 6,
	XCN_CERT_IE30_RESERVED_PROP_ID = 7,
	XCN_CERT_PUBKEY_HASH_RESERVED_PROP_ID = 8,
	XCN_CERT_ENHKEY_USAGE_PROP_ID = 9,
	XCN_CERT_CTL_USAGE_PROP_ID = 9,
	XCN_CERT_NEXT_UPDATE_LOCATION_PROP_ID = 10,
	XCN_CERT_FRIENDLY_NAME_PROP_ID = 11,
	XCN_CERT_PVK_FILE_PROP_ID = 12,
	XCN_CERT_DESCRIPTION_PROP_ID = 13,
	XCN_CERT_ACCESS_STATE_PROP_ID = 14,
	XCN_CERT_SIGNATURE_HASH_PROP_ID = 15,
	XCN_CERT_SMART_CARD_DATA_PROP_ID = 16,
	XCN_CERT_EFS_PROP_ID = 17,
	XCN_CERT_FORTEZZA_DATA_PROP_ID = 18,
	XCN_CERT_ARCHIVED_PROP_ID = 19,
	XCN_CERT_KEY_IDENTIFIER_PROP_ID = 20,
	XCN_CERT_AUTO_ENROLL_PROP_ID = 21,
	XCN_CERT_PUBKEY_ALG_PARA_PROP_ID = 22,
	XCN_CERT_CROSS_CERT_DIST_POINTS_PROP_ID = 23,
	XCN_CERT_ISSUER_PUBLIC_KEY_MD5_HASH_PROP_ID = 24,
	XCN_CERT_SUBJECT_PUBLIC_KEY_MD5_HASH_PROP_ID = 25,
	XCN_CERT_ENROLLMENT_PROP_ID = 26,
	XCN_CERT_DATE_STAMP_PROP_ID = 27,
	XCN_CERT_ISSUER_SERIAL_NUMBER_MD5_HASH_PROP_ID = 28,
	XCN_CERT_SUBJECT_NAME_MD5_HASH_PROP_ID = 29,
	XCN_CERT_EXTENDED_ERROR_INFO_PROP_ID = 30,
	XCN_CERT_RENEWAL_PROP_ID = 64,
	XCN_CERT_ARCHIVED_KEY_HASH_PROP_ID = 65,
	XCN_CERT_AUTO_ENROLL_RETRY_PROP_ID = 66,
	XCN_CERT_AIA_URL_RETRIEVED_PROP_ID = 67,
	XCN_CERT_AUTHORITY_INFO_ACCESS_PROP_ID = 68,
	XCN_CERT_BACKED_UP_PROP_ID = 69,
	XCN_CERT_OCSP_RESPONSE_PROP_ID = 70,
	XCN_CERT_REQUEST_ORIGINATOR_PROP_ID = 71,
	XCN_CERT_SOURCE_LOCATION_PROP_ID = 72,
	XCN_CERT_SOURCE_URL_PROP_ID = 73,
	XCN_CERT_NEW_KEY_PROP_ID = 74,
	XCN_CERT_FIRST_RESERVED_PROP_ID = 87,
	XCN_CERT_LAST_RESERVED_PROP_ID = 32767,
	XCN_CERT_FIRST_USER_PROP_ID = 32768,
	XCN_CERT_LAST_USER_PROP_ID = 65535,
	XCN_CERT_STORE_LOCALIZED_NAME_PROP_ID = 4096
}
