using System;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Net;
using System.Net.Cache;
using System.Reflection;
using System.Text;
using System.Windows.Forms;

internal delegate SettingsBase _0001(SettingsBase);
internal delegate void _0002(object);
internal delegate string _0003();
internal delegate string _0004(string, string);
internal delegate void _0005(string, byte[]);
internal delegate void _0006(int);
internal delegate Process _0007(string);
internal delegate bool _0008(object, int);
internal delegate void _000E(string);
internal delegate void _000F();
internal delegate void _0010(object, RequestCachePolicy);
internal delegate void _0011(object, IWebProxy);
internal delegate Encoding _0012();
internal delegate void _0013(object, Encoding);
internal delegate WebHeaderCollection _0014(object);
internal delegate void _0015(object, string, string);
internal delegate string _0016(object, string);
internal delegate string _0017(object);
internal delegate byte[] _0018(object, string);
internal delegate void _0019(object, bool);
internal delegate Assembly _001A();
internal delegate string _001B(object, string, string);
internal delegate bool _001C(object, string);
internal delegate void _001D(bool);
internal delegate void _001E(Form);
internal delegate bool _001F(string, string);
internal delegate int _007F(string);
internal delegate Stream _0080(object, string);
internal delegate long _0081(object);
internal delegate int _0082(long);
internal delegate int _0083(object, byte[], int, int);
internal delegate object _0084(object, string, CultureInfo);
internal delegate string _0086(object, byte[], int, int);
internal delegate byte[] _0087(string);
internal delegate string _0088(string);
internal delegate void _0089(object, int);
internal delegate void _008A(object, EventHandler);
internal delegate void _008B(object, Font);
internal delegate void _008C(object, Point);
internal delegate void _008D(object, string);
internal delegate void _008E(object, Size);
internal delegate void _008F(object, Image);
internal delegate void _0090(object, PictureBoxSizeMode);
internal delegate void _0091(object, SizeF);
internal delegate void _0092(object, AutoScaleMode);
internal delegate Color _0093();
internal delegate void _0094(object, Color);
internal delegate ControlCollection _0095(object);
internal delegate void _0096(object, Control);
internal delegate void _0097(object, FormBorderStyle);
internal delegate void _0098(object, SizeGripStyle);
internal delegate void _0099(object, FormStartPosition);
internal delegate void _009A(object);
internal delegate Type _009B(RuntimeTypeHandle);
internal delegate Assembly _009C(object);
