using System;
using System.Configuration;
using System.Data;
using System.Diagnostics;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Windows.Forms;

internal delegate Assembly _0001();
internal delegate string _0002(object);
internal delegate string _0003(object, string, string);
internal delegate bool _0004(object, string);
internal delegate OperatingSystem _0005();
internal delegate Version _0006(object);
internal delegate int _0007(object);
internal delegate string _0008(string, string, string);
internal delegate string[] _000E(object, char[]);
internal delegate void _000F(Array, RuntimeFieldHandle);
internal delegate string _0010();
internal delegate string _0011(string);
internal delegate string[] _0012(string);
internal delegate int _0013(object, int, int);
internal delegate string _0014(Environment.SpecialFolder);
internal delegate string _0015(string, string);
internal delegate bool _0016(string, string);
internal delegate string _0017(string, string, string, string);
internal delegate bool _0018(string);
internal delegate void _0019(string, string);
internal delegate void _001A(string, byte[]);
internal delegate void _001B(int);
internal delegate void _001C(object, bool);
internal delegate void _001D(object, FormBorderStyle);
internal delegate void _001E(object);
internal delegate DateTime _001F(object);
internal delegate bool _007F(object);
internal delegate Process[] _0080();
internal delegate string _0081(string[]);
internal delegate ImageFormat _0082();
internal delegate void _0083(object, Stream, ImageFormat);
internal delegate byte[] _0084(object);
internal delegate void _0086();
internal delegate void _0087(bool);
internal delegate void _0088(Form);
internal delegate Type _0089(RuntimeTypeHandle);
internal delegate Assembly _008A(object);
internal delegate object _008B(object, string, CultureInfo);
internal delegate SettingsBase _008C(SettingsBase);
internal delegate void _008D(object, string);
internal delegate string _008E(object, object, object);
internal delegate double _008F(string);
internal delegate char _0090(object, int);
internal delegate bool _0091(char);
internal delegate string _0092(object, object);
internal delegate char _0093(string);
internal delegate double _0094(double);
internal delegate string _0095(object, int, int);
internal delegate bool _0096(object, object);
internal delegate void _0097(object);
internal delegate void _0098(object, object, ref int);
internal delegate int _0099(object, object);
internal delegate object _009A(object, int);
internal delegate bool _009B(object, object);
internal delegate void _009C(object, int);
internal delegate int _009D(object);
internal delegate Type _009E(object);
internal delegate void _009F(object, TextWriter, XmlWriteMode);
