namespace MySqlX.Communication;

internal enum ServerMessageId
{
	OK = 0,
	ERROR = 1,
	CONN_CAPABILITIES = 2,
	SESS_AUTHENTICATE_CONTINUE = 3,
	SESS_AUTHENTICATE_OK = 4,
	NOTICE = 11,
	RESULTSET_COLUMN_META_DATA = 12,
	RESULTSET_ROW = 13,
	RESULTSET_FETCH_DONE = 14,
	RESULTSET_FETCH_SUSPENDED = 15,
	RESULTSET_FETCH_DONE_MORE_RESULTSETS = 16,
	SQL_STMT_EXECUTE_OK = 17,
	RESULTSET_FETCH_DONE_MORE_OUT_PARAMS = 18,
	COMPRESSION = 19
}
